### PR TITLE
add bitbucket custom template integration

### LINKED ISSUE #3739: Add BitBucket support to download nuclei templates
**Please describe your feature request:**

Add support for Bitbucket in order to run/update custom templates from private BitBucket repository as is you do with Gitlab,Github

### PR DESCRIPTION
**Pull request by dogancanbakir**
## Proposed changes

This PR adds Bitbucket custom template integration. Closes #3739.
This integration requires authentication.
```console
export BITBUCKET_TEMPLATE_REPO=nuclei-bb-integration/custom-nuclei-templates
export BITBUCKET_TOKEN=<TOKEN>
go run . -ut

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.8

                projectdiscovery.io

[INF] No new updates found for nuclei templates
[INF] Repo nuclei-bb-integration/custom-nuclei-templates cloned successfully at /home/vscode/nuclei-templates/bitbucket/custom-nuclei-templates
```

doc: https://github.com/projectdiscovery/nuclei-docs/pull/158

## Checklist

- [X] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by Mzack9999 — APPROVED** [review]
lgtm!

Maybe we can change the `ERR` message to `INF` also for bitbucket, or detail it a bit more:
```console
$ go run . -ut
....
[INF] No new updates found for nuclei templates
[ERR] mzack9999/nuclei-templates: already up-to-date
```

To something like:
```console
[INF] bitbucket repository mzack9999/nuclei-templates: already up-to-date
```

**Review by ehsandeep — CHANGES_REQUESTED** [review]
- [ ] download only template files from the repositories, i.e. with `.yaml` extension.
for reference - https://github.com/projectdiscovery/nuclei/blob/bb98eced070f4ae137b8cd2a7f887611bc1b9c93/v2/pkg/external/customtemplates/gitlab.go#L47-L48

**Comment by dogancanbakir** [comment]
@ehsandeep I have been experiencing a recurring issue with the `max_depth` [parameter](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-source/#api-repositories-workspace-repo-slug-src-commit-path-get) as it consistently triggers a `429 Too Many Requests` error whenever I attempt to use it. What do you think of keeping the current implementation as it is for now?

**Review by ehsandeep — CHANGES_REQUESTED** [review]
A couple of tests are failing, looks like some minor changes are required as per the latest changes. cc @dogancanbakir

**Comment by ehsandeep** [comment]
Closing due to known limitations with BitBucket API.

**Pull request closed without merging**
