### PR TITLE
 bug fixes in js , network protocol and flow

### LINKED ISSUE #4285: Incomplete Data Received with Nuclei's JavaScript NetConn ('nuclei/net')
Based on the implementation of Recv() or similar family function it is expected to receive 4096 bytes from the socket by default. However, the number of bytes you want to receive can also be passed as an argument. https://github.com/projectdiscovery/nuclei/blob/main/pkg/js/libs/net/net.go#L116-L117

However, for some reason, the number of bytes specified in the argument are not getting considered. This behavior is only observed when using `OpenTLS` instead of `Open` to open a socket.

### Nuclei version:
[INF] Nuclei Engine Version: v3.0.1

### Current Behavior:

Example:
`nuclei -t simplejs.yaml  -u vps.noob.ninja`

```yaml
id: js_test

info:
  name: Testing JS
  author: rahulmaini
  severity: info


javascript:
  - code: |
      let m = require('nuclei/net');
      let name=Host+':'+Port;
      let conn = m.OpenTLS('tcp', name);
      conn.Send('GET / HTTP/1.1\r\nHost:'+name+'\r\n\r\n');
      resp = conn.RecvString()
      console.log(resp) // I just get response headers

    args:
      Host: "{{Host}}"
      Port: "443"
```

Outputs:
```
[INF] HTTP/1.1 200 OK
Date: Tue, 24 Oct 2023 08:39:43 GMT
Server: Apache/2.4.18 (Ubuntu)
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Transfer-Encoding: chunked
Content-Type: application/json

```

### Expected Behavior:

Should output

```
[INF] HTTP/1.1 200 OK
Date: Tue, 24 Oct 2023 08:41:13 GMT
Server: Apache/2.4.18 (Ubuntu)
Access-Control-Allow-Origin: *
Transfer-Encoding: chunked
Content-Type: application/json

155
{
    "swagger": "2.0",
    "info": {
        "title": "xxxxxxx",
        "description": "test",
        "version": "2017-06-04T22:56:06+00:00",
        "contact": {
            "name": "test",
            "url": "javascript:alert(document.domain)",
            "email": "xx.team@%0D%0Ajavascript%3Aalert(1)%2F%2F%0A.com"
        }
    }
}


0
```

### Steps To Reproduce:
1. Run the following template with this command `nuclei -t simplejs.yaml  -u vps.noob.ninja`

```yaml
id: js_test

info:
  name: Testing JS
  author: rahulmaini
  severity: info


javascript:
  - code: |
      let m = require('nuclei/net');
      let name=Host+':'+Port;
      let conn = m.OpenTLS('tcp', name);
      conn.Send('GET / HTTP/1.1\r\nHost:'+name+'\r\n\r\n');
      resp = conn.RecvString()
      console.log(resp) // I just get response headers

    args:
      Host: "{{Host}}"
      Port: "443"
```

2. Notice, only response headers are logged:
```
[INF] HTTP/1.1 200 OK
Date: Tue, 24 Oct 2023 08:39:43 GMT
Server: Apache/2.4.18 (Ubuntu)
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Transfer-Encoding: chunked
Content-Type: application/json
```

4.  Re-run with the following template and notice that only after calling RecvString() second time, the response body is logged.
```yaml
id: js_test

info:
  name: Testing JS
  author: rahulmaini
  severity: info


javascript:
  - code: |
      let m = require('nuclei/net');
      let name=Host+':'+Port;
      let conn = m.OpenTLS('tcp', name);
      conn.Send('GET / HTTP/1.1\r\nHost:'+name+'\r\n\r\n');
      resp = conn.RecvString()
      console.log(resp) // I just get response headers
      resp = conn.RecvString() // upon calling RecvString again
      console.log(resp)      // I'd get response body

    args:
      Host: "{{Host}}"
      Port: "443"
```

Outputs:
```
[INF] HTTP/1.1 200 OK
Date: Tue, 24 Oct 2023 08:38:35 GMT
Server: Apache/2.4.18 (Ubuntu)
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Transfer-Encoding: chunked
Content-Type: application/json

[INF] 155
{
    "swagger": "2.0",
    "info": {
        "title": "xxxxxxx",
        "description": "test",
        "version": "2017-06-04T22:56:06+00:00",
        "contact": {
            "name": "test",
            "url": "javascript:alert(document.domain)",
            "email": "xx.team@%0D%0Ajavascript%3Aalert(1)%2F%2F%0A.com"
        }
    }
}
```

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
### Proposed Changes
- closes #4285 
- `TCP` is stream protocol and when we call `conn.Read` it reads whatever is available at that moment in buffer and does not necessarily mean everything sent by server.  same is the case if we specify `conn.Read(N)` 
- this issue is fixed by reading it in a loop (which is general behaviour)
- New change: if no length is specified or N is 0 . then all data sent by server is read

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
### example template

```yaml
id: js_test

info:
  name: Testing JS
  author: rahulmaini
  severity: info


javascript:
  - code: |
      let m = require('nuclei/net');
      let name=Host+':'+Port;
      let conn = m.OpenTLS('tcp', name);
      conn.Send('GET / HTTP/1.1\r\nHost:'+name+'\r\n\r\n');
      resp = conn.RecvString()
      log(resp)

    args:
      Host: "{{Host}}"
      Port: "443"
```

```console
$ ./nuclei -t simplejs.yaml  -u vps.noob.ninja 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2

		projectdiscovery.io

[INF] Current nuclei version: v3.0.2 (latest)
[INF] Current nuclei-templates version: v9.6.8 (latest)
[INF] New templates added in latest release: 79
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[JS] HTTP/1.1 200 OK
Date: Mon, 30 Oct 2023 12:44:01 GMT
Server: Apache/2.4.18 (Ubuntu)
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Transfer-Encoding: chunked
Content-Type: application/json

155
{
    "swagger": "2.0",
    "info": {
        "title": "xxxxxxx",
        "description": "test",
        "version": "2017-06-04T22:56:06+00:00",
        "contact": {
            "name": "test",
            "url": "javascript:alert(document.domain)",
            "email": "xx.team@%0D%0Ajavascript%3Aalert(1)%2F%2F%0A.com"
        }
    }
}


0

[INF] No results found. Better luck next time!
```

**Review by iamnoooob — APPROVED** [review]
Looks good. In the initial commit there was this issue where it would always fetch complete data even on specifying N bytes. But, [this](https://github.com/projectdiscovery/nuclei/pull/4313/files/a93aff3c8ef98ccde1fe01369833feb812b25ca0..9e11d5b12db2bfc9ff9976f95b51d4b5884eca64) just fixed it.

**Comment by tarunKoyalwar** [comment]
## TODO
- [ ] fix same issue in network protocol

```yaml
id: network-port-example

info:
  name: Example Template with Network Port
  author: pdteam
  severity: high
  description: This is an updated description for the network port example.
  reference: https://updated-reference-link

tcp:
  - host: 
      - "tls://{{Hostname}}"
    port: 443
    inputs:
      - data: "GET / HTTP/1.1\r\nHost: {{Hostname}}\r\nConnection: close\r\n\r\n"
    read-size: 5000
    extractors:
    - type: dsl
      dsl:
        - "len(data)"
```

```console
$ ./nuclei -u projectdiscovery.io -t network-https.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2

		projectdiscovery.io

[INF] Current nuclei version: v3.0.2 (latest)
[INF] Current nuclei-templates version: v9.6.8 (latest)
[INF] New templates added in latest release: 79
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[network-port-example] [tcp] [high] projectdiscovery.io:443 [1369]
```

**Comment by tarunKoyalwar** [comment]
## New Changes

- fixed js protocol related issues in flow #4318 
```console
$ ./nuclei -u scanme.sh -t ~/test-templates/jshelper.yaml                                           

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2

		projectdiscovery.io

[INF] Current nuclei version: v3.0.2 (latest)
[INF] Current nuclei-templates version: v9.6.8 (latest)
[INF] New templates added in latest release: 79
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[js_test] [http] [info] https://scanme.sh/6f6b
```
> template available in issue description

- fixed url double encoding issue which caused unit tests to fail ( affected in utils versions between v0.0.58-now ) (refer: https://github.com/projectdiscovery/utils/pull/278) 
- depends on https://github.com/projectdiscovery/utils/pull/275

**Comment by tarunKoyalwar** [comment]
tests are passing locally . only interactsh related test is failing in gh workflow (which is expected)

**Comment by tarunKoyalwar** [comment]
## New Changes
- fixed issue with result in flow templates #4323 
```console
$ TESTS="flow/flow-hide-matcher.yaml" ./run.sh
::group::Build nuclei
::endgroup::
::group::Build nuclei integration-test
::endgroup::
::group::Installing nuclei templates

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2

		projectdiscovery.io

[INF] No new updates found for nuclei templates
[✓] Test "flow/flow-hide-matcher.yaml" passed!
```

**Review by ehsandeep — APPROVED** [review]

**Review by dogancanbakir — APPROVED** [review]
LGTM

**Pull request merged**
