### PR TITLE
add mkdir support in headless screenshot

### LINKED ISSUE #3246: add template option to create new directory if not exists
### Please describe your feature request:

- add template option (in headless protocol and maybe others) `allow-mkdir` or `allow-newdir`  to allow nuclei in creating new directory if path does not exists

### Describe the use case of this feature:

```yaml
id: httpscreenshot

info:
  name: Headless Http Screenshot
  author: tarunKoyalwar
  severity: info
  description: Capture screenshots of URLs
  tags: headless,screenshot

variables:
  suffix: "{{Host}}"
  dir: "screenshots"

headless:
  - steps:
      - action: setheader
        args:
          part: request
          key: "User-Agent"
          value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"

      - action: navigate
        args:
          url: "{{BaseURL}}"

      - action: waitload
      - action: screenshot
        args:
          fullpage: true
          to: "{{dir}}/{{suffix}}"
```

- currently this template fails because nuclei does not create `screenshots` directory

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
## Proposed changes

- screenshots ideally should be saved under `screenshots` directory or custom directory specified by user
- this adds `mkdir` argument under `screenshot` action type in headless mode which creates `directory` and given path if it doesn't exist . This is disabled by default .
- other minor improvements related to test and error handling
- closes #3246 

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
### Example Template
```yaml
id: httpscreenshot

info:
  name: Headless Http Screenshot
  author: tarunKoyalwar
  severity: info
  description: Capture screenshots of URLs
  tags: headless,screenshot

variables:
  suffix: '{{replace(BaseURL,"/","_")}}'
  dir: "screenshots"

headless:
  - steps:
      - action: setheader
        args:
          part: request
          key: "User-Agent"
          value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"

      - action: navigate
        args:
          url: "{{BaseURL}}"

      - action: waitload
      - action: screenshot
        args:
          fullpage: true
          mkdir: true
          to: "{{dir}}/{{suffix}}
```

**Comment by tarunKoyalwar** [comment]
## Default directory

```console
$ ./nuclei -u https://projectdiscovery.io -headless -t ~/test/screenshot.yaml    

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.0

		projectdiscovery.io

[INF] Using Nuclei Engine 2.9.0 (latest)
[INF] Using Nuclei Templates 9.4.0 (latest)
[INF] Templates added in last update: 65
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] Screenshot successfully saved at screenshots/https:__projectdiscovery.io.png
[INF] No results found. Better luck next time!



$  ls screenshots 
https:__projectdiscovery.io.png

```

**Comment by tarunKoyalwar** [comment]
### Save Image to User specified directory
```console
$ ./nuclei -u https://projectdiscovery.io -headless -t ~/test/screenshot.yaml -V "dir=images"

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.0

		projectdiscovery.io

[INF] Using Nuclei Engine 2.9.0 (latest)
[INF] Using Nuclei Templates 9.4.0 (latest)
[INF] Templates added in last update: 65
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] Screenshot successfully saved at images/https:__projectdiscovery.io.png
[INF] No results found. Better luck next time!
```
```console
$ ls images 
https:__projectdiscovery.io.png
```

**Comment by tarunKoyalwar** [comment]
### New changes

- changed version to `v2.9.1-dev` ( it was confusing for anyone to differentiate b/w dev and main releases )

**Review by Mzack9999 — APPROVED** [review]
lgtm!

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
