### PR TITLE
Exclusive Custom Template Update

### PR DESCRIPTION
**Pull request by kchason**
## Proposed changes
Addresses https://github.com/projectdiscovery/nuclei/issues/3705 by adding the new flag, functionality, and documentation (translation needed on the `README_CN.md` and `README_KR.md`).

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by MetzinAround** [comment]
@ehsandeep @kchason had asked us in discord if there was an issue with our CI checks for two PRs. The other one has passed now, somehow, but this one didn't. Any help or advice is appreciated.

**Comment by ehsandeep** [comment]
> @ehsandeep @kchason had asked us in discord if there was an issue with our CI checks for two PRs. The other one has passed now, somehow, but this one didn't. Any help or advice is appreciated.

restarted build runs and it's passing now.

**Review by tarunKoyalwar — COMMENTED** [review]
hii @kchason , thanks for issue & PR but can you eloborate more on this (it feels redundant to me) due to following reasons.

1)  custom templates  update is already supported with `-ut`. there is no overhead at all since official nuclei template update only occurs when there is new update available when using `-duc` or a version check failure we treat available version as latest
2) according to your description this adds support for cases where custom templates are present locally while that is true update errors are non-fatal so using `-ut` will definetly work 
3) also i am not sure about chaining `-duc` with `-uct`. i think we can `-duc: skip update check common for custom templates too`
```
-duc -ut: no templates are downloaded and no checks are performed (current behavior).
-duc -uct: only the custom template providers (if available) are checked and downloaded (proposed behavior).
```
pls do reply if i am missing something!

any thoughts @ehsandeep

**Comment by kchason** [comment]
The goal is to avoid the requests to the `nuclei-templates` project if it's not required. Either the user doesn't want to import templates from the public internet, or they can't. In the latter case, it might fail gracefully, but there's the delay of those requests timing out before moving on.

**Comment by tarunKoyalwar** [comment]
@kchason , request is sent to `nuclei-templates` based on the response received by pdtm version check . 
still this is a valid use case
>  Either the user doesn't want to import templates from the public internet

instead of adding new flags and also adding more granular controls regarding template update sources. we can add env variables like
```console
NUCLEI_TEMPLATES_PUBLIC_UPDATE=false
NUCLEI_TEMPLATES_GITHUB_UPDATE=false
NUCLEI_TEMPLATES_AZURE_UPDATE=false
NUCLEI_TEMPLATES_GITLAB_UPDATE=true
```
this way users have more control over what source to update skip when updating templates
let me know if you are implementing this . thanks

> Note: we should add logic about this in DefaultConfig in effort to centralize configs at v2/pkg/catalog/config

**Comment by kchason** [comment]
That works and achieves the same goal I was going for. I'll create a new branch with an environment variable focused approach.

**Comment by ehsandeep** [comment]
@kchason, thanks; closing this out as you mentioned it will be reworked in a different branch.

**Pull request closed without merging**
