### PR TITLE
scanallip handle edge cases

### LINKED ISSUE #3078: failed to scan all ips reverting to default <nil>
## Bug:

An issue with using `-scan-all-ips` option with a port as input, example: `https://www.hackerone.com:443`

## Error:

```
[ERR] failed to scan all ips reverting to default <nil>
```

### Nuclei version:

`latest`, `dev`

### Steps to reproduce:

```console
nuclei -sa -id tech-detect -u https://www.hackerone.com:443

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.3

		projectdiscovery.io

[ERR] failed to scan all ips reverting to default <nil>
[INF] Using Nuclei Engine 2.8.3 (latest)
[INF] Using Nuclei Templates 9.3.2 (latest)
[INF] Templates added in last update: 57
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[tech-detect:jsdelivr] [http] [info] https://www.hackerone.com:443
[tech-detect:react] [http] [info] https://www.hackerone.com:443
[tech-detect:google-tag-manager] [http] [info] https://www.hackerone.com:443
[tech-detect:cloudflare] [http] [info] https://www.hackerone.com:443
```

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
## Proposed changes

- ScanAllIPs now handles edgecase urls
- Improved error message

closes #3078 
## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
```sh
go run .  -sa -id tech-detect -l domains.txt

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4-dev

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4-dev (development)
[INF] Using Nuclei Templates 9.3.2 (latest)
[INF] Templates added in last update: 57
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 8
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[tech-detect:cloudflare] [http] [info] https://hackerone.com:443/somepath
[tech-detect:cloudflare] [http] [info] https://hackerone.com/home
[tech-detect:cloudflare] [http] [info] https://hackerone.com:443/
[tech-detect:cloudflare] [http] [info] https://hackerone.com:443/
[tech-detect:cloudflare] [http] [info] https://hackerone.com/?with=param
[tech-detect:cloudflare] [http] [info] http://hackerone.com:80/?with=param
[tech-detect:cloudflare] [http] [info] https://hackerone.com/
[tech-detect:cloudflare] [http] [info] https://hackerone.com:443/somepath
[tech-detect:cloudflare] [http] [info] https://hackerone.com/?with=param
[tech-detect:cloudflare] [http] [info] http://hackerone.com:80/?with=param
```

**Comment by tarunKoyalwar** [comment]
Verified with following targets
```yaml
https://hackerone.com/
https://hackerone.com:443/
https://hackerone.com:443/somepath
http://hackerone.com:80/?with=param
hackerone.com/home
```

@ehsandeep  ,I think we should create a integration test since its common to find these kind of urls in automation

**Comment by tarunKoyalwar** [comment]
```yaml
$  go run .  -sa  -id tech-detect -l ~/test/domains.txt -silent                             
[tech-detect:cloudflare] [http] [info] https://hackerone.com:443/path
[tech-detect:cloudflare] [http] [info] https://hackerone.com/
[tech-detect:cloudflare] [http] [info] https://hackerone.com/home
[tech-detect:cloudflare] [http] [info] https://hackerone.com/?with=param
[tech-detect:cloudflare] [http] [info] http://hackerone.com:80/?with=param
[tech-detect:cloudflare] [http] [info] https://hackerone.com/?with=param
[tech-detect:cloudflare] [http] [info] http://hackerone.com:80/?with=param
[tech-detect:cloudflare] [http] [info] https://hackerone.com:443/somepath
[tech-detect:cloudflare] [http] [info] https://hackerone.com:443/
[tech-detect:cloudflare] [http] [info] https://hackerone.com:443/somepath
[tech-detect:cloudflare] [http] [info] https://hackerone.com/home
[tech-detect:cloudflare] [http] [info] https://hackerone.com:443/path
[tech-detect:cloudflare] [http] [info] https://hackerone.com/
[tech-detect:cloudflare] [http] [info] https://hackerone.com:443/
```

**Review by Mzack9999 — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]
```console
./nuclei -sa -id tech-detect -u https://www.hackerone.com:443

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4-dev

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4-dev (development)
[INF] Using Nuclei Templates 9.3.2 (latest)
[INF] Templates added in last update: 57
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 2
[tech-detect:jsdelivr] [http] [info] https://www.hackerone.com:443
[tech-detect:react] [http] [info] https://www.hackerone.com:443
[tech-detect:google-tag-manager] [http] [info] https://www.hackerone.com:443
[tech-detect:cloudflare] [http] [info] https://www.hackerone.com:443
[tech-detect:jsdelivr] [http] [info] https://www.hackerone.com:443
[tech-detect:react] [http] [info] https://www.hackerone.com:443
[tech-detect:google-tag-manager] [http] [info] https://www.hackerone.com:443
[tech-detect:cloudflare] [http] [info] https://www.hackerone.com:443
```

**Pull request merged**
