### PR TITLE
chore(deps): change to github.com/microsoft/go-mssqldb@v1.6.0

### PR DESCRIPTION
**Pull request by Jarnpher553**
change to github.com/microsoft/go-mssqldb@v1.6.0

## Proposed changes

When my project uses github.com/microsoft/go-mssqldb, it conflicts with github.com/denisenkom/go-mssqldb used by nuclei, resulting in the error "panic: sql: Register called twice for driver mssql". The main reason for this issue is that both go-mssqldb packages register a driver with the same name mssql, so I would like to update denisenkom/go-mssqldb to microsoft/go-mssqldb.

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thanks for your contribution @Jarnpher553 , we appreciate it!

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !

**Comment by Jarnpher553** [comment]
Something went wrong, Windows testing failed. 😓

**Comment by tarunKoyalwar** [comment]
now worries @Jarnpher553 , it seems to be flaky , the integration test passed in debug mode

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
