### PR TITLE
fix relative path issue + remove residual code

### LINKED ISSUE #4258: nuclei 3.0.0 Could not find template scanning templates via a file
i just update my nuclei to the version

[INF] Current nuclei version: v3.0.0 (latest)
[INF] Current nuclei-templates version: v9.6.7 (latest)

there's a problem running this command

nuclei -t nuclei-template/ 

[ERR] Could not find template 'nuclei-templates/': could not find template file: no such path found: nuclei-templates/
[INF] Current nuclei version: v3.0.0 (latest)
[INF] Current nuclei-templates version: v9.6.7 (latest)
[INF] Targets loaded for current scan: 43
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan

before the update it was working fine after the update i got this error

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
## Proposed Changes

- fix issue while using relative paths with `-t` flag
- removed residual code ( we already validate/check file access while loading)
- closes #4258

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
## example

```console
$ nuclei -t nuclei-templates          

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2-dev

		projectdiscovery.io

[INF] Current nuclei version: v3.0.2-dev (development)
[INF] Current nuclei-templates version: v9.6.7 (latest)
[INF] New templates added in latest release: 1
[INF] Templates loaded for current scan: 7130
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Executing 7143 signed templates from projectdiscovery/nuclei-templates
[INF] No results found. Better luck next time!
```

```console
$ nuclei -t nuclei-templates/http/cves                                                                                            128 ↵

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2-dev

		projectdiscovery.io

[INF] Current nuclei version: v3.0.2-dev (development)
[INF] Current nuclei-templates version: v9.6.7 (latest)
[INF] New templates added in latest release: 1
[INF] Templates loaded for current scan: 2143
[INF] Executing 2146 signed templates from projectdiscovery/nuclei-templates
[INF] No results found. Better luck next time!
```

**Review by ehsandeep — APPROVED** [review]

**Review by dogancanbakir — APPROVED** [review]
LGTM

**Comment by tarunKoyalwar** [comment]
### New Changes

- fixed relative path issue ( finally found and fixed bug introduced during v3 ->  in `tryResolve` function it was only resolving files and directories were not and resolving happens when relative path is given)
- updated docs about deprecated `-metrics` option and print metrics port in verbose mode
- users can now configure nuclei update and nuclei-templates update timeout with existing `-timeout` flag (default: 30sec)

**Comment by dogancanbakir** [comment]
I came across this while testing a case:
```console
$ go run . -u google.com -id caa-fingerprint -j -or

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2-dev

                projectdiscovery.io

[INF] Current nuclei version: v3.0.2-dev (development)
[INF] Current nuclei-templates version: v9.6.7 (latest)
[INF] Targets loaded for current scan: 1
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan
exit status 1
```

**Comment by tarunKoyalwar** [comment]
@dogancanbakir can you retry again after pulling latest changes . i am not able to reproduce it 

```console
$ go run . -u google.com -id caa-fingerprint -j -or -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2-dev

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[WRN] Excluded 31 templates with known weak matchers / tags excluded from default run using .nuclei-ignore
[INF] Current nuclei version: v3.0.2-dev (development)
[INF] Current nuclei-templates version: v9.6.7 (latest)
[INF] New templates added in latest release: 1
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 1
[VER] [caa-fingerprint] Sent DNS request to google.com
[INF] No results found. Better luck next time!
```


```console
$ ./nuclei -id caa-fingerprint -u scanme.sh -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2-dev

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[WRN] Excluded 31 templates with known weak matchers / tags excluded from default run using .nuclei-ignore
[INF] Current nuclei version: v3.0.2-dev (development)
[INF] Current nuclei-templates version: v9.6.7 (latest)
[INF] New templates added in latest release: 1
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 1
[VER] [caa-fingerprint] Sent DNS request to scanme.sh
[INF] No results found. Better luck next time!
```

**Comment by dogancanbakir** [comment]
Same /shrug
```console
$ git log -1
commit 58dac42f425071dcf083e722e10ee57a68083709 (HEAD -> issue-4258-rel-dir, origin/issue-4258-rel-dir)
Author: Tarun Koyalwar <tarun@projectdiscovery.io>
Date:   Wed Oct 25 23:35:29 2023 +0530

    update stats & metrics docs

$ go run . -u google.com -id caa-fingerprint -j -or

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2-dev

                projectdiscovery.io

[INF] Current nuclei version: v3.0.2-dev (development)
[INF] Current nuclei-templates version: v9.6.7 (latest)
[INF] Targets loaded for current scan: 1
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan
exit status 1

$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/home/vscode/.cache/go-build'
GOENV='/home/vscode/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/workspaces/nuclei/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4129994261=/tmp/go-build -gno-record-gcc-switches'
```

**Comment by dogancanbakir** [comment]
I just tried on darwin host, it works.
```console
go run . -u google.com -id caa-fingerprint -j -or

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2-dev

		projectdiscovery.io

[WRN] Found 6 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v3.0.2-dev (development)
[INF] Current nuclei-templates version: v9.6.7 (latest)
[INF] New templates added in latest release: 1
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 1
[INF] No results found. Better luck next time!
```

**Comment by dogancanbakir** [comment]
Okay, there was a missing escape char in the template on my side; I fixed it, and now it works. LOL

**Review by dogancanbakir — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
