### PR TITLE
Adding docker healthcheck + automatic stats via clistats

### PR DESCRIPTION
**Pull request by Mzack9999**
## Proposed changes
Adding docker healthcheck functionality + clistats version bump with automatic embedded web server exposing status

## Checklist
- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate) - https://github.com/projectdiscovery/nuclei-docs/pull/138

1. Depends on: https://github.com/projectdiscovery/clistats/issues/22
2. Potentially Closes https://github.com/projectdiscovery/nuclei/issues/2811
3. Potentially Closes https://github.com/projectdiscovery/clistats/issues/20
4. Potentially Closes https://github.com/projectdiscovery/clistats/issues/19

### CODE REVIEW

**Review by ehsandeep — COMMENTED** [review]
```console
./nuclei -u example.com -m

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.6

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.6 (latest)
[INF] Using Nuclei Templates 9.3.4 (latest)
[INF] Templates added in last update: 15
[INF] Templates loaded for scan: 4784
[INF] Targets loaded for scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] Templates clustered: 908 (Reduced 837 HTTP Requests)
panic: http: multiple registrations for /metrics

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x107c01d20, {0x10605b54a, 0x8}, {0x106cd7960?, 0x140026be020})
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/net/http/server.go:2503 +0x20c
net/http.(*ServeMux).HandleFunc(...)
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/net/http/server.go:2540
net/http.HandleFunc(...)
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/net/http/server.go:2552
github.com/projectdiscovery/clistats.(*Statistics).Start(0x14000321920, 0x10604a197?, 0xffffffffffffffff)
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/clistats@v0.0.11/clistats.go:134 +0x164
github.com/projectdiscovery/nuclei/v2/pkg/progress.(*StatsTicker).Init(0x1400027c330, 0x106125d1c?, 0x0?, 0x14008640c18?)
	/Users/geekboy/Github/nuclei/v2/pkg/progress/progress.go:109 +0x1e0
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).executeTemplatesInput(0x14000232620, 0x140007e61b0, 0x14000183040)
	/Users/geekboy/Github/nuclei/v2/internal/runner/runner.go:641 +0x32c
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).runStandardEnumeration(_, {{0x0, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, {{0x0, 0x0}}, {{0x0, ...}}, ...}, ...}, ...)
	/Users/geekboy/Github/nuclei/v2/internal/runner/enumerate.go:34 +0x5c
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration(0x14000232620)
	/Users/geekboy/Github/nuclei/v2/internal/runner/runner.go:534 +0x121c
main.main()
	/Users/geekboy/Github/nuclei/v2/cmd/nuclei/main.go:103 +0x48c
```

**Review by Ice3man543 — CHANGES_REQUESTED** [review]
@Mzack9999 as sandeep reported, we need to remove nuclei native `/metrics` registration for stats exporting otherwise it'll give an error for duplicate route

**Comment by Mzack9999** [comment]
The following stats are not currently exposed on the `/metrics` endpoint:
- `duration`
- `rps`
- `percent`

What do you think about adding them natively to `clistats` as they seems a good fit for all tools?

**Review by ehsandeep — CHANGES_REQUESTED** [review]
It works well; since it's the default behavior, we need to ensure nuclei don't stop/fail in case of unexpected failure to start the metrics endpoint; we can also include the metrics endpoint in CLI output, for example:

 

```console
./nuclei -u example.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.8

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.8 (latest)
[INF] Using Nuclei Templates 9.3.5 (latest)
[INF] Templates added in last update: 61
[INF] Templates loaded for scan: 4844
[INF] Targets loaded for scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] Templates clustered: 949 (Reduced 872 Requests)
[INF] Scan metrics: http://127.0.0.1:63636/metrics
[INF] Using Interactsh Server: oast.pro
```

**Comment by Mzack9999** [comment]
The solution might be controversial as almost all options related to stats are now deprecated in favor of an always-enabled http endpoint bound to localhost:
```
# start the tool
$ go run . -u http://192.168.1.1

# query the status
$ curl http://127.0.0.1:63636/metrics
{"startedAt":"2023-02-27T13:03:30.3788196+01:00","duration":"0:00:42","matched":17,"total":7451,"hosts":1,"rps":"33","percent":"18","requests":1412,"errors":86,"templates":5582}
```

**Review by tarunKoyalwar — APPROVED** [review]
lgtm ! 

we probably have to highlight this in next release https://github.com/projectdiscovery/nuclei/pull/3192#issuecomment-1446213508

**Review by ehsandeep — CHANGES_REQUESTED** [review]
- [ ] keep the stats options output the same as before (reuse `/metrics` data?)
- [ ] fixed json response, currently keys are random upon each request.  

```
curl -s http://127.0.0.1:63636/metrics | jq .
{
  "total": 8161,
  "requests": 1206,
  "startedAt": "2023-03-29T01:50:23.966702+05:30",
  "duration": "0:01:04",
  "errors": 91,
  "matched": 7,
  "templates": 5774,
  "hosts": 1,
  "rps": "18",
  "percent": "14"
}
```

**Comment by ehsandeep** [comment]
Closing this one, as we still wanted to keep the same stats behavior as before by reusing newly added callback in clistats project. cc @RamanaReddy0M

**Comment by RamanaReddy0M** [comment]
Just for reference: https://github.com/projectdiscovery/clistats/blob/27f5699dd21b77d8805134ac04c4f5c6db42667a/clistats.go#L195
usage:
https://github.com/projectdiscovery/dnsx/blob/8c37ff804d2b2262643244a50442f319eff3f91f/internal/runner/runner.go#L311

**Pull request closed without merging**
