### PR TITLE
Display tpl contents

### PR DESCRIPTION
**Pull request by vzamanillo**
Implements #2827

## Proposed changes

- New `td` flag to display the highlighted template contents in combination with `tl`

imagen

- Sorted template list by path

imagen

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by ehsandeep — CHANGES_REQUESTED** [review]
@vzamanillo thank you for working on this, few suggestions -

- [x] enable `-tl` option when `-td` option is used implicitly.
- [ ] respect `-no-color` option to disable colors when `-td` is used.

**Comment by vzamanillo** [comment]
* [x]  enable `-tl` option when `-td` option is used implicitly.
* [x]  respect `-no-color` option to disable colors when `-td` is used.

**Comment by vzamanillo** [comment]
By the way, I chose `monokai` as the default style to show the content of the template, if you think it's not the right one or you prefer another one, we have time to change it, you can try em here [Chroma Playground](https://swapoff.org/chroma/playground/)

I have not thought about the option of being able to change it by command line, but it can also be done.

**Review by ehsandeep — APPROVED** [review]
```console
./nuclei -id tls-version -silent -td
```

```bash
Template: /Users/geekboy/nuclei-templates/ssl/tls-version.yaml

id: tls-version

info:
  name: TLS Version
  author: pdteam
  severity: info
  tags: ssl

ssl:
  - address: "{{Host}}:{{Port}}"

    extractors:
      - type: json
        json:
          - ".tls_version"
```

**Comment by vzamanillo** [comment]
> The `-td` flag could also accept an optional `int` parameter to only show a specific number of lines in case you want to look up the descriptions of multiple templates (as shown in the first screenshot in the ticket).

Yep, forgot that.

You mean using an optional integer value of `td` or a new one in combination with `td`,? e.g: `nl` (number or lines)

**Comment by vzamanillo** [comment]
I see, there is no optional value flags for `goflags`

https://github.com/projectdiscovery/goflags/issues/11

**Comment by forgedhallpass** [comment]
@vzamanillo yes, you are right, I forgot that it wasn't yet implemented.

In this case you can either:
1. leave it as-is and post a comment in the goflags ticket with the follow-up work
2. require a number from start where anything <= 0 would mean "show the whole content", otherwise the parameter should indicate the desired amount of template lines

**Comment by vzamanillo** [comment]
@forgedhallpass I am going to investigate how to add the optional flags, it is the optimal solution.

**Review by ravlio — APPROVED** [review]

**Comment by ehsandeep** [comment]
@vzamanillo, we can adapt the changes once https://github.com/projectdiscovery/goflags/issues/11 is implemented.

**Pull request merged**
