### PR TITLE
add stop-at-first-match for headless protocol

### LINKED ISSUE #2991: stop-at-first-match field in headless mode
### Current Behavior:

While running headless template which has `stop-at-first-match: true`, It is giving an error: - 

```
yaml: unmarshal errors:
  line : field stop-at-first-match not found in type headless.Request
```

### Expected Behavior:

It should run the template and stop at first match as expected.

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
## Proposed changes

- adds `stop-at-first-match` option for headless templates

closes #2991 

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
Example Template at https://github.com/projectdiscovery/nuclei/issues/2991#issuecomment-1348513886

**Comment by tarunKoyalwar** [comment]
### when `stop-at-first-match:false` 

```sh
go run . -headless -t headless-stop.yaml -u https://www.evil.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4-dev

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4-dev (development)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[headless-stop] [headless] [low] https://www.evil.com
[headless-stop] [headless] [low] https://www.evil.com
```

### when `stop-at-first-match:true` 

```sh
go run . -headless -t headless-stop.yaml -u https://www.evil.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4-dev

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4-dev (development)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[headless-stop] [headless] [low] https://www.evil.com
```

**Review by Mzack9999 — APPROVED** [review]

**Review by ehsandeep — CHANGES_REQUESTED** [review]
Adapt the changes for `-spm` CLI option, which is used for the same purpose and takes precedence over the template option if specified.

**Comment by tarunKoyalwar** [comment]
```sh
$  ./nuclei -u https://evil.com -t ~/test/headless-stop-false.yaml -headless     

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4-dev

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4-dev (development)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[headless-stop] [headless] [low] https://evil.com
[headless-stop] [headless] [low] https://evil.com


$  ./nuclei -u https://evil.com -t ~/test/headless-stop-false.yaml -headless -spm

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4-dev

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4-dev (development)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[headless-stop] [headless] [low] https://evil.com

```

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
