### PR TITLE
javascript protocol for scripting (includes 15+ proto libs) 

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
## Proposed changes

- based & continutation of js-layer pr by @Ice3man543 
- Complete documentation / api reference etc is available at https://projectdiscovery.github.io/js-proto-docs/ or in (docs)
- more example templates at https://github.com/tarunKoyalwar/nuclei-templates/tree/main/javascript 
- contribution guidelines and docs https://github.com/projectdiscovery/nuclei/blob/7085b47c19dbe3a70b3d4eb23177995bda5c285a/v2/pkg/js/CONTRIBUTE.md
- design and package layout => https://github.com/projectdiscovery/nuclei/blob/feat-js-protocol/v2/pkg/js/DESIGN.md
- devtools https://github.com/projectdiscovery/nuclei/blob/feat-js-protocol/v2/pkg/js/devtools/README.md

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
## Notes

- goja , goja_nodejs don't create github releases and we manually need to update HEAD
- zgrab2 is missing release from 2 years but latest commit is required "[97ba87c](https://github.com/zmap/zgrab2/commit/97ba87c0e70661e1263631288b0cab41acebbbae)"

**Comment by tarunKoyalwar** [comment]
### TODO

- [ ]  add network library based javascript protocol integration test for windows and macos 
- [ ]  complete documentation

**Comment by tarunKoyalwar** [comment]
### Note

- template validate fails because `xpath` matcher support is not yet available in v3-beta branch

**Review by Mzack9999 — APPROVED** [review]

**Review by Ice3man543 — APPROVED** [review]

**Comment by tarunKoyalwar** [comment]
### TODO

- [ ] validate and fix network policy(-lna) in javascript protocol

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
