### PR TITLE
fix aws signer missing template variables

### LINKED ISSUE #3202: AWS Templates Variable issue
### Nuclei version:
2.8.7

### Current Behavior:
The engine is not picking up variables from the templates with the AWS signature.

### Expected Behavior:

The intended functionality should be to work without requiring manual input of the region and service name from cli `nuclei -t templates/sts-get-caller-identity.yaml.` However, it is currently only working when the region and service are manually provided using the flags `-V "service=sts" -V "region=us-east-1"`

```yaml
id: sts-get-caller-identity
info:
  name: STS get-caller-identity
  author: princechaddha
  severity: info

self-contained: true
signature: aws

variables:
  service: sts
  region: us-east-1

requests:
  - raw:
      - |
        POST https://sts.us-east-1.amazonaws.com HTTP/1.1
        Host: sts.us-east-1.amazonaws.com
        Content-Type: application/x-www-form-urlencoded; charset=utf-8
        User-Agent: aws-cli/2.1.28 Python/3.8.8 Darwin/21.6.0 exe/x86_64 prompt/off command/sts.get-caller-identity
        Content-Length: 43

        Action=GetCallerIdentity&Version=2011-06-15

    matchers:
      - type: word
        words:
          - "<GetCallerIdentityResult>"

      - type: status
        status:
          - 200
```

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
## Proposed changes

- Fix issue where aws signer did not use variables from template
- AWS Signer now uses variables from both template itself and CLI with preference given to CLI (i.e can override with CLI option)

closes #3202 

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
```sh
$ ./nuclei -t ~/test/aws-caller.yaml  -v        

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.7

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.7 (latest)
[INF] Using Nuclei Templates 9.3.4 (latest)
[INF] Templates added in last update: 15
[INF] Templates loaded for scan: 1
[VER] [sts-get-caller-identity] Sent HTTP request to https://sts.us-east-1.amazonaws.com
[sts-get-caller-identity] [http] [info] https://sts.us-east-1.amazonaws.com

```

### Template

```yaml
id: sts-get-caller-identity
info:
  name: STS get-caller-identity
  author: princechaddha
  severity: info

self-contained: true
signature: aws

variables:
  service: sts
  region: us-east-1

requests:
  - raw:
      - |
        POST https://sts.us-east-1.amazonaws.com HTTP/1.1
        Host: sts.us-east-1.amazonaws.com
        Content-Type: application/x-www-form-urlencoded; charset=utf-8
        User-Agent: aws-cli/2.1.28 Python/3.8.8 Darwin/21.6.0 exe/x86_64 prompt/off command/sts.get-caller-identity
        Content-Length: 43

        Action=GetCallerIdentity&Version=2011-06-15

    matchers:
      - type: word
        words:
          - "<GetCallerIdentityResult>"

      - type: status
        status:
          - 200  
```

**Comment by tarunKoyalwar** [comment]
@ehsandeep  @princechaddha , Currently these variables are not evaluated , should they be evaluated ??

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
I think `region` should default to `us-east-2` if not specified (could you confirm @princechaddha )

**Comment by princechaddha** [comment]
Yes @Mzack9999 the default region can be `us-east-2` if not specified.

**Comment by princechaddha** [comment]
I can confirm now the variables for AWS are picked up from the templates 

```yaml
pwnmachine@Princes-MacBook-Pro nuclei % sudo go run . -t ~/Documents/GitHub/nuclei-templates/cloud/aws/sts/aws-sts-service.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.7

             projectdiscovery.io

[INF] Using Nuclei Engine 2.8.7 (latest)
[INF] Using Nuclei Templates 9.3.5 (latest)
[INF] Templates added in last update: 61
[INF] Templates loaded for scan: 1
[aws-sts-service] [http] [info] https://sts.amazonaws.com
```

**Comment by tarunKoyalwar** [comment]
@princechaddha  , added following default variables any other defaults you think we should include
```go
var AwsDefaultVars = map[string]interface{}{
	"region":  "us-east-2",
	"service": "sts",
}
```

**Review by Mzack9999 — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
