### PR TITLE
Added support for rate limit per minute

### PR DESCRIPTION
**Pull request by souvikhazra1**
* Added support for rate-limit per minute
* Updated go.uber.org/ratelimit from v0.1.0 to v0.2.0

### CODE REVIEW

**Comment by ehsandeep** [comment]
Thank you @souvikhazra1, can you please highlight the use case of rate-limit per minute instead of seconds?

Also, can you please open a separate PR for env file reading support to make it simple for review? please see the related issue - https://github.com/projectdiscovery/nuclei/issues/643

**Comment by souvikhazra1** [comment]
Hi @ehsandeep, the .env support I don't want to submit now, still working on that, I pushed that by mistake, I have reverted the changes.
For rate-limit per minute the use case is--
* In the case of an application that has a firewall in front of them blocking very frequent requests, in that case even 1 request per second might get blocked.
* In case of an application running under dev environment with very limited resources, 1 request per second can cause the application to hang or even crash.

For these type of scenarios I have introduced rate-limit per minute, basically, it is useful for every scenarios where 1 request per second will be too much requests.

**Comment by ehsandeep** [comment]
thank you @souvikhazra1 for the additional context and update, we will review this asap.

**Review by Ice3man543 — APPROVED** [review]

**Comment by Ice3man543** [comment]
This looks good to me. Merging!

**Pull request merged**
