### PR TITLE
enhance sarif output (closes #2608)

### LINKED ISSUE #2608: Output SARIF format is confusing
```  
 -se, -sarif-export string     file to export results in SARIF format
```
Although nuclei supports exporting to sarif format, it does not conform to the rules of sarif format, and the output result should be placed in the `results` field. But not.

It is confusing, like this.
```
...
"results": [
        {
          "ruleId": "tech-detect-95410662745f9d47610c389af7d617774a98aa0c",
          "ruleIndex": 0,
          "level": "note",
          "message": {
            "text": "http://127.0.0.1:18080"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "README.md"
                },
                "region": {
                  "startLine": 1,
                  "startColumn": 1,
                  "endLine": 1,
                  "endColumn": 1
                }
              },
              "message": {
                "text": "http://127.0.0.1:18080"
              }
            }
          ]
        },
...
```
Sarif Viewer can't view it and get any useful information! 
image

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
# Description

Fix and Enhance Static Analysis Results Interchange Format (SARIF) Output 

closes #2608 

# Changes
- Removed dependency adopted https://github.com/projectdiscovery/sarif
- Enhanced / Extra Output
- Compatible with [GitHub-Sarif](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning) including security related metadata .  (supports https://github.com/projectdiscovery/nuclei-action/issues/43 )

# Run Below Command to verify 

```sh
nuclei -u https://scanme.sh -se report.sarif
```
## Supported Viewers
Generated sarif output is compatible with all available Sarif viewers

1. [Sarif-WebComponent](https://microsoft.github.io/sarif-web-component/)
2. [VSCode-Extension]([Sarif Viewer](https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer))
3. Github repository security -> Code Scanning 

## Note: 
`impact & severity , title  is properly configured in PR .  below screenshots were created using random data to match testcases hence result is messed up actual/new report generated is proper without errors`

github_security
vscode

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
Nuclei will probably be receiving UI soon . Currently there are 2 options available to visualize nuclei outputs using SARIF

### 1) Using SARIF Web Component
Visit [Web-Component](https://microsoft.github.io/sarif-web-component/) and upload generated SARIF file using open at top right corner . 

Example nuclei generated sarif file : https://gist.github.com/tarunKoyalwar/f76fc7b55c29e69b1ea1d02f4d6661a8
UI is clean and Minimal and results are grouped based on templates with hyperlinks to hosts

### 2) Using Github Security page of repo 

~~~yaml
   - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
~~~
can be used along with nuclei-actions or any other method to upload SARIF to security page of that repo . Output location is same as `CodeQL` i.e security -> Code Scanning 

UI has many filters as show in above image and alerts are scoped to organization level

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
merge conflict - `go mod tidy` should suffice

**Review by Mzack9999 — APPROVED** [review]
lgtm!

```console
$ go run . -u https://scanme.sh -se report.sarif
...
[2022-11-30 12:25:39] [self-signed-ssl] [ssl] [low] scanme.sh
```

image

**Comment by tarunKoyalwar** [comment]
Fixed issue related to result title 
Updated result title format
nuclei_sarifgh

**Comment by tarunKoyalwar** [comment]
@ehsandeep  , currently `nuclei-actions` does not upload sarif to security page , maybe we can make it upload to security page by default

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
