### PR TITLE
Add headless chrome based templates support

### PR DESCRIPTION
**Pull request by Ice3man543**
This PR adds supports for the automation of Headless Chrome. This makes nuclei act like how a human would, browsing the website while having the power of Matchers / Extractors / etc.

The support is built around the idea of Actions. Each action is a step the browser can take to reach a point. So, the process of entering the URL into the address bar is the `navigate` action. Clicking a button is a `click` action, text inputs are `text` actions, etc. Chaining these actions together allows nuclei to achieve very complex workflows that would've taken a lot of work to be automated in the same manner using traditional simple HTTP requests.

An example template to navigate to example.com (when provided in input) with a matcher to check if it's the correct site.

```yaml
id: headless-example

info:
  name: headless-example
  author: pd-team
  severity: info

headless:
  - steps:
      - action: navigate
        args:
          url: "{{BaseURL}}"
      - action: waitload
    matchers:
      - type: word
        words:
          - "Example Domain"
```

A slightly more complex template that allows users to login into DVWA in an automated manner by submitting the default `admin:password` pair.

```yaml
id: dvwa-headless-autologin

info:
  name: DVWA Headless AutoLogin
  author: pd-team
  severity: info

headless:
  - steps:
      - args:
          url: "{{BaseURL}}"
        action: navigate
      - action: waitload
      - args:
          by: x
          value: admin
          xpath: /html/body/div/div[2]/form/fieldset/input
        action: text
      - args:
          by: x
          value: password
          xpath: /html/body/div/div[2]/form/fieldset/input[2]
        action: text
      - args:
          by: x
          xpath: /html/body/div/div[2]/form/fieldset
        action:
      - action: waitload
      - args:
          by: x
          xpath: /html/body/div/div[2]/form/fieldset/p/input
        action: click
      - action: waitload
    matchers:
      - type: word
        words:
          - "You have logged in as 'admin'"

```

To explain the last example, these may look a bit complex at first but are very simple at their core. First, the navigation happens to the URL, next we ask the browser to fill the form with an XPath selector. XPath selectors can be very easily generated from chrome while browsing by using **Developer Tools**. Nuclei supports Regex, CSS, JS as well as XPath selectors for element selection. After setting all inputs, we click the submit button and wait for the page to load. At last, a matcher is run to check successful login.

An even more complex scenario that can be very easily accomplished with nuclei is instrumenting the page with custom JS and looking for changes that can identify the state of the page. To do this, nuclei allow you to execute two types of scripts - Hook and Normal. Hook based scripts will be added to each page before the navigation, hence they have complete control over all the page and can override global functions (overriding alert() for XSS detection), etc.

As an example of such complex workflow, let's try to reproduce DVWA's Reflected XSS vulnerability with the means of a template. The below template starts of by logging in, and enters the xss payload in the input.

```yaml
id: dvwa-xss-verification

info:
  name: DVWA Reflected XSS Verification
  author: pd-team
  severity: info

headless:
  - steps:
      - args:
          url: "{{BaseURL}}"
        action: navigate
      - action: waitload

      # Set the hook to override window.data for xss detection
      - action: script
        args:
          hook: true
          code: "window.alert = function() { window.data = 'found' }"
      - args:
          by: x
          value: admin
          xpath: /html/body/div/div[2]/form/fieldset/input
        action: text
      - args:
          by: x
          value: password
          xpath: /html/body/div/div[2]/form/fieldset/input[2]
        action: text
      - args:
          by: x
          xpath: /html/body/div/div[2]/form/fieldset/p/input
        action: click
      - action: waitload
      - args:
          by: x
          xpath: /html/body/div/div[2]/div/ul[2]/li[11]/a
        action: click
      - action: waitload
      - args:
          by: x
          value: '"><svg/onload=alert(1)>'
          xpath: /html/body/div/div[3]/div/div/form/p/input
        action: text
      - args:
          keys: "\r" # Press the enter key on the keyboard
        action: keyboard
      - action: waitload
      - action: script
        name: alert
        args:
          code: "window.data"
    matchers:
      - part: alert
        type: word
        words:
          - "found"
```

The important thing is the below block - 

```yaml
      - action: script
        args:
          hook: true
          code: "window.alert = function() { window.data = 'found' }"
```
This piece of code overwrites the window.alert function with a custom JS function that will be executed on each page whenever the alert is called. Then we call another js script given below - 

```yaml
      - action: script
        name: alert
        args:
          code: "window.data"
```

This code retrieves the value of `window.data` variable and sets it to `alert`, which can then be matched upon by the matcher to check if the XSS occurred.

### TODO

- [ ] Test-cases for the PR
- [ ] UI based visual converter to convert events from things like headless-recorder to nuclei-headless actions. (already WIP).

Thanks to @Mzack9999 for the initial browserdj concept this is built upon on!

### CODE REVIEW

**Comment by ehsandeep** [comment]
Wow @Ice3man543 🔥 🔥

**Comment by geeknik** [comment]
Is there any chance we can see support for a different headless browser like [Zombie.js](http://zombie.js.org/) so we don't have to install google/webkit dependencies for headless chrome which feels gross to us. We have a hard time supporting anything Google related due to their misogynistic business practices (see the recent firings of two female AI ethicists). Thank you.

**Comment by Ice3man543** [comment]
@geeknik this is using chrome's cdp protocol, so that is not going to be an easy task unless we find something that implements the chrome devtools protocol. Do you know of any chrome alternatives that do so?

**Comment by geeknik** [comment]
That's a shame. There are so many great headless browser projects created by people better than Google which don't require a browser or browser dependencies.

**Comment by parthmalhotra** [comment]
> Is there any chance we can see support for a different headless browser like [Zombie.js](http://zombie.js.org/) so we don't have to install google/webkit dependencies for headless chrome which feels gross to us. We have a hard time supporting anything Google related due to their misogynistic business practices (see the recent firings of two female AI ethicists). Thank you.

Well then by that logic you shuldn't use nuclei as its written in Go (By Google) :)

**Comment by geeknik** [comment]
> Well then by that logic you shuldn't use nuclei as its written in Go (By Google) :)

Excellent, I see that I'm no longer welcome here so I'll take my contributions elsewhere.

**Pull request merged**
