### PR TITLE
Circular References in OpenAPI 3.0 fixed

### PR DESCRIPTION
**Pull request by trypa11**
## Proposed changes
Fixing #5285 

It was a bug in the parsing process of the kin-openapi package which has been resolved in the new version, kin-openapi 1.126.0 https://github.com/getkin/kin-openapi?tab=readme-ov-file#v01260.

I updated Nuclei to use this version and made changes to pkg/input/format/openapi/example.go, as version 1.124.0 modified the type of schemas and parameters in the openapi file instance.

Following this update, Nuclei ran without encountering the previous fatal error.

Nuclei's Output:
- Before:
image
- After:
image

## Checklist

- [x ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ehsandeep** [comment]
```
--- FAIL: TestSwaggerAPIParser (0.00s)
    swagger_test.go:22: could not decode openapi 2.0 schema: yaml: unmarshal errors:
          line 27: cannot unmarshal !!str `integer` into openapi3.Types
          line 32: cannot unmarshal !!str `string` into openapi3.Types
FAIL
FAIL	github.com/projectdiscovery/nuclei/v3/pkg/input/formats/swagger	0.059s
```

Failing test.

**Comment by trypa11** [comment]
Hello,

In version 1.124.0, the kin-openapi library modified the type of schemas and parameters within the OpenAPI file instance. Specifically, the Type parameter underwent a change (refer to the update notes here: [kin-openapi v1.124.0](https://github.com/getkin/kin-openapi?tab=readme-ov-file#v01240)). This alteration caused issues when testing Swagger 2.0 files, as the current tests utilize the go-yaml library to decode these files into the OpenAPI 2.0 schema. 

The go-yaml library, however, does not support custom struct types like the Type parameter. Upon investigation, I discovered that the kin-openapi library leverages the invopop/yaml library for unmarshaling YAML files. This library is based on go-yaml but includes enhanced support for custom struct types (as detailed here: [invopop/yaml](https://github.com/invopop/yaml?tab=readme-ov-file)).

Consequently, I replaced the go-yaml library with invopop/yaml in our project. This change resolved the unmarshaling errors encountered during testing, ensuring compatibility with the updated kin-openapi library and allowing for the proper decoding of the Type parameter.

If you need any further refinements or additional details, please let me know!


image

**Comment by trypa11** [comment]
@ehsandeep 
https://github.com/trypa11/nuclei/actions/runs/10326190906
I  successfully ran this test in my forked nuclei, and it completed without any issues. Could you please rerun the actions one more time? If the problem persists, do you have any other suggestions for resolving it?

Thank you for your understanding

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
