### PR TITLE
NkxxkN/multiple requests per template

### PR DESCRIPTION
**Pull request by NkxxkN**
## Description

This PR adds:
 -  Support for multiple requests per templates. Particularly useful for CORS template.
 - Support for configurable headers with BaseURL and Hostname. Also useful for CORS template.

## References

[CORS Template](https://github.com/projectdiscovery/nuclei-templates/pull/49)

## Note

I struggled a bit with the go concurrency and I know that this is a sensitive subject in go. You don't want to mess up with it 😄so make sure to particularly review this part while reviewing the PR. From my testing I think we are good but better be safe than sorry.

### CODE REVIEW

**Comment by Ice3man543** [comment]
Hi @NkxxkN, really nice work on the PR! However, multiple requests are already supported in the templates as of now. The second bit of the pull request with templates in headers are a really good idea however not sure about the first change. I'll take a closer look and let you know asap!

**Comment by NkxxkN** [comment]
Hey @Ice3man543, Forgot to mention that I think your previous PR adding support for redirect broke multiple requests which is why I've added those changes today. My CORS template was working as of yesterday but not anymore this morning :)

**Comment by Ice3man543** [comment]
Hey @NkxxkN, I added header based support in #51 . Aside from that, matchers conditions can now be also specified. However, supporting chained requests is something that will break how things are done the way it's implemented. We can create an issue and track ideas and once we have something solid we can add it. 

Other than that, really nice work on the PR overall. Concurrency is tough in go however it becomes natural after using it for a while. Have fun with go, it's an amazing language. I'm closing this PR and look forward to more contributions from you in future!

**Comment by NkxxkN** [comment]
Hey @Ice3man543! 

Good job on adding the header templating 👍 
Moving the discussion about multiple requests per template to a separate issue https://github.com/projectdiscovery/nuclei/issues/57

**Pull request closed without merging**
