### PR TITLE
fix some json deserialization issues

### PR DESCRIPTION
**Pull request by CodFrm**
## Proposed changes

fix some json deserialization issues

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by Mzack9999 — APPROVED** [review]

**Review by tarunKoyalwar — COMMENTED** [review]
@CodFrm , I fixed a minor bug and added some missing tags along with a unit test . 
currently Unit Test Fails because there is a marshal/unmarshal issue with enum types.

### Problem/Reason 
- In some enums `severity` , `signature` we use `iota` and `iota+1` for initialisation

**Comment by tarunKoyalwar** [comment]
Note: 
This is a  JSON Marshal issue and not Unmarshal. 
@CodFrm  are you only unmarshalling JSON templates ??

**Comment by CodFrm** [comment]
@tarunKoyalwar 
I hope that json and yaml can be converted to each other, but it seems to be difficult now.

while parsing json templates is ok
```go
func TestTemplateStruct(t *testing.T) {
	bin := `{
  "id": "valid-gmail-checker",
  "info": {
    "name": "Valid Google Mail Checker",
    "author": "dievus,dwisiswant0",
    "severity": "info",
    "reference": [
      "https://github.com/dievus/geeMailUserFinder"
    ]
  },
  "self-contained": true,
  "requests": [
    {
      "method": "HEAD",
      "path": [
        "https://mail.google.com/mail/gxlu?email={{email}}"
      ],
      "matchers": [
        {
          "type": "word",
          "part": "header",
          "words": [
            "COMPASS"
          ]
        }
      ]
    }
  ]
}`
	var jsonTemplate Template
	err := json.Unmarshal([]byte(bin), &jsonTemplate)
	require.Nil(t, err, "failed to unmarshal json template")
}
```

**Comment by CodFrm** [comment]
Added the ability to judge an empty string when deserializing, and do nothing if it is empty

```go
	s := strings.Trim(string(data), `"`)
	if s == "" {
		return nil
	}
```

**Comment by tarunKoyalwar** [comment]
@CodFrm , nice catch on the empty string deserialization issue , it seems like we almost have full support to JSON templates. currently it does not omit tags we are looking into a custom enum type so that will be fixed in near future.

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !

**Comment by tarunKoyalwar** [comment]
@CodFrm  by the way is there a specific usecase for this json support ? maybe we can add some helper functions ??

**Comment by CodFrm** [comment]
@tarunKoyalwar We can implement a Network Catalog to read templates from remote servers and JSON is better for network transportation.

**Review by Mzack9999 — APPROVED** [review]
lgtm - `xxxTypeHolder` and `iota` offset will be reworked and simplified in the future

**Pull request merged**
