### PR TITLE
verbose proxy url validation

### PR DESCRIPTION
**Pull request by Mzack9999**

### CODE REVIEW

**Comment by Zeokat** [comment]
Only one comment, you wrote at https://github.com/projectdiscovery/nuclei/pull/72/commits/548395a287c24f002bd16b72fde353d9f13a6241#diff-0e6f1380789f55519238d848092df3abR28 that the proxyURL format should be `http(s)://...` and in my tests, I always had to setup the proxyURL as `http://...` because if i use `https://...` it stopped to work.

I still have pending check Squid proxy with/without authentication, but at this point maybe is safer to point the proxyURL as `http://`.

**Comment by Mzack9999** [comment]
@Zeokat Thanks for reviewing the code and pointing this out, I've made a new commit with only HTTP. Let us know how the tests with proxy go, and thanks for your help!

**Comment by Zeokat** [comment]
@Mzack9999 I can confirm that Squid proxy with/without auth, should be also pointed with proxyURL as `http://`. So i can't see any situation where `https://` proxyURL is needed.

**Comment by Zeokat** [comment]
I run some tests trying to check the proxy validation and discovered some weird behaviours.

All this configurations works when i use a socks5 proxy:

`-proxy-socks-url "socks7://50.50.50.1:520000"`
`-proxy-socks-url "sucks1://50.76.1.240:52000"`
`-proxy-socks-url "http://50.76.1.240:52000"`

This configurations doesn't works and return the expected verbosity error `[FTL] Program exiting: invalid socks proxy format`:

`-proxy-socks-url "50.76.1.240:52000"`
`-proxy-socks-url "://50.76.1.240:asd"`
`-proxy-socks-url "socks5://50.76.1.240:asd"`

This configurations doesn't work and doesn't return the verbosity errors:

`-proxy-socks-url "socks5:///50.76.1.240:52000"` (triple slash)
`-proxy-socks-url "socks5://::52000"`

You can use `https://www.silisoftware.com/tools/ipconverter.php` to get the allowed IP formats.
`-proxy-socks-url "socks5://0x324C01F0:52000"` (Hexadecimal IP)
`-proxy-socks-url "socks5://843842032:52000"` (Integer IP)
`-proxy-socks-url "socks5://0062.0114.0001.0360:52000"` (Octal IP)

Maybe i went a little too far testing this, but you can have an idea if something should be fixed :+1:

**Pull request merged**
