### PR TITLE
Add error log option

### PR DESCRIPTION
**Pull request by zerodivisi0n**
## Proposed changes

Implements error log feature (#1187)

Original issue checklist:
- [x] Updating id to template-path to include template path information instead of id (https://github.com/projectdiscovery/nuclei/commit/933ed2429d533f7d78ce30df4eee51ade0313be9, https://github.com/projectdiscovery/nuclei/commit/463c1c0142968de19e97c9d18667acc1c74bbf71)
- [x] Updating url JSON field input to make it uniform for all types of template (https://github.com/projectdiscovery/nuclei/commit/933ed2429d533f7d78ce30df4eee51ade0313be9)
- [x] Updating HTTP and FILE type error to include only final error information (https://github.com/projectdiscovery/nuclei/commit/1eb0378952b576db290fa15fc87fc6904ace13e5)

Differences from the original issue:
- The absolute path to the template is displayed, not the relative path as in the example. Does this need to be fixed?
- I made the original error message for all protocols since it can be done uniformly in one place. Also, I am doing recursive `Unwrap` to get the last wrapped error. I don't know how bad it is.
- I also did some refactoring to improve the testability of outputs. This is done in the last three commits (https://github.com/projectdiscovery/nuclei/commit/cd2db280bfd5469f5984d1d3f1bb96828cbdb6c8, https://github.com/projectdiscovery/nuclei/commit/b8ebbc27f5a11f6d5edd74a5415bc0041893850e, https://github.com/projectdiscovery/nuclei/commit/bccc8e921b9aa640fd244f9d149ace0723e704ab). If it's unnecessary, I can remove it.

Example of output:
```
$ echo "https://exxmple.com/tcpconfig.html" | ./nuclei -t misconfiguration/tcpconfig.yaml -error-log error.log
$ cat error.log | jq                                                                                                               
{
  "template": "/home/zerodivisi0n/nuclei-templates/misconfiguration/tcpconfig.yaml",
  "input": "https://exxmple.com/tcpconfig.html/tcpconfig.html",
  "error": "no address found for host",
  "type": "http"
}
```

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by ehsandeep — APPROVED** [review]
Everything working well as described in the issue @zerodivisi0n 👏🏻

**Review by Ice3man543 — APPROVED** [review]
The PR looks good to me, very nice work @zerodivisi0n!

**Comment by Ice3man543** [comment]
Regarding showing absolute paths, i guess it's okay for us to show absolute paths since those would be easy to open through the error log. Also unwrapping like that is the accepted way of getting the last error, so It shouldn't be an issue.
The tests for output layer also can be merged!

**Comment by zerodivisi0n** [comment]
@ehsandeep , @Ice3man543 , great! Thanks for the quick review!

**Pull request merged**
