### PR TITLE
Fixing Dockerfile v2

### PR DESCRIPTION
**Pull request by 0x5ECF4ULT**
Hello again.
After my previous PR that fixed a "permission denied" I found out that nuclei just froze when attempting a scan. I don't know what the problem was (guess because "appuser" didn't have a shell). However I fixed it by giving appuser a shell. Now it works again!
Cheers

### CODE REVIEW

**Comment by 0x5ECF4ULT** [comment]
No problems yay!

**Comment by 0x5ECF4ULT** [comment]
Also updated the README now so the new image can be used without raising tons of issues :D

**Comment by 0x5ECF4ULT** [comment]
This would effectively mean that you guys would need to push the new Docker image release out as soon as you merge

**Review by Mzack9999 — APPROVED** [review]

**Comment by bauthard** [comment]
Thank you @0x5ECF4ULT, 

Docker image is updated here https://hub.docker.com/r/projectdiscovery/nuclei

**Comment by 0x5ECF4ULT** [comment]
Thank you @bauthard. Is there any other repo this patch needs to be applied on? I'd like to further contribute to your projects.

**Pull request merged**
