### PR TITLE
implement custom helper logic

### PR DESCRIPTION
**Pull request by TheSecEng**

### CODE REVIEW

**Comment by forgedhallpass** [comment]
Please describe the motivation/use-case for which you've proposed these changes. Who/how/from where should someone invoke `AddHelperFunction`?

**Comment by TheSecEng** [comment]
> Please describe the motivation/use-case for which you've proposed these changes. Who/how/from where should someone invoke `AddHelperFunction`?

Seeing as it points to a "global" `functions` variable. It can be called at any point they want. This really comes into play when nuclei is being leveraged as a package and not the CLI tooling.

At BlackAnvil we are currently implementing a gRPC implementation of Nuclei and wanted to extend the `HelperFunctions` with our own needs. In our custom `Runner` implementation, we call `dsl. AddHelperFunction` several times to add additional helpers that we need to support our custom templates.

**Comment by forgedhallpass** [comment]
Please leave a comment with why the method was created and potentially suppress the unused warning, so that it wouldn't be deleted by mistake in the future.

**Comment by TheSecEng** [comment]
Added comment, usage and return error on duplicate keys

**Pull request merged**
