### PR TITLE
Fix 186 - Experimental progressbar live results

### LINKED ISSUE #186: [issue] Progress bar suppressing run time results
**Describe the bug**

When using nuclei with a progress bar, results are suppressed and displayed once the scan is completed, expected behavior to keep the run time result as it like before, run time results are helpful in case you are running big scans. 
 
**Nuclei version**

`@master`

### PR DESCRIPTION
**Pull request by manuelbua**
This is an experimental implementation that aims to fix #186  and allows for stdout/stderr output to coexists along with the progressbar output: i've stress-tested this with some fast output and it seems to be working fine, please test this and report back any issues you encounter with it, thanks!

### CODE REVIEW

**Comment by bauthard** [comment]
Nice work 🔥 🔥 @manuelbua 

I'm testing this right now and found some issues with printing results in the terminal, here is how you can reproduce it. 

```bash

> chaos -d airbnb.com -bbq -http-url | ./nuclei -t ~/nuclei-templates/technologies/ -pbar

[INF] [jenkins-headers-detect] Loaded template Jenkins Headers Based Detection (@ice3man) [informative]
[INF] [home-assistant] Loaded template Detect Home Assistant (@fabaff) [informative]
[INF] [Github-Enterprise-Detect] Loaded template Detect Github Enterprise (@ehsahil) [informative]
[INF] [clockwork-php-header] Loaded template Clockwork PHP exposure (@organiccrap) [high]
[INF] [ntlm-directories] Loaded template Discovering directories w/ NTLM (@puzzlepeaches) [informative]
[INF] [tech-detect] Loaded template Wappalyzer Technology Detection (@hakluke) [informative]




[33 templates, 599 hosts]   245/56306 0% [>------------------------------------------------------------------------------------------------------------------------------------------]  163.07r/s 1s 5m43s

[33 templates, 599 hosts]   352/56306 1% [>------------------------------------------------------------------------------------------------------------------------------------------]  166.89r/s 2s 5m35s

[33 templates, 599 hosts]   503/56306 1% [>------------------------------------------------------------------------------------------------------------------------------------------]  148.36r/s 3s 6m16s

[33 templates, 599 hosts]   908/56306 2% [=>------------------------------------------------------------------------------------------------------------------------------------------]  96.37r/s 9s 9m34s
[33 templates, 599 hosts]   962/56306 2% [=>----------------------------------------------------------------------------------------------------------------------------------------]  90.09r/s 10s 10m14s
```

Those blank lines are for a valid result. you can see the results if you save the output in a file.

**Comment by manuelbua** [comment]
Thanks for reporting that, i can reproduce some of the behavior, but not the missing output.

Anyway, it just hit me that using `os.Pipe()` as i'm doing now is what was causing the `too many open files` error of some time ago, so i need to think of another way of doing that as well :(

**Comment by manuelbua** [comment]
This is a different approach and should be able to manager output better than the previous version, it defaults to a refresh rate of 8Hz but it can be tweaked, let me know how it works for you.

**Comment by bauthard** [comment]
Hey @manuelbua, this works perfectly, no error till now, as we are creating release today, so we are keeping it as optional for now, so we can give more time for testing, enjoying progress bar with live results, few releases today to look for :D

**Pull request merged**
