### PR TITLE
Add missing ratelimit utils package

### PR DESCRIPTION
**Pull request by root4loot**
## Proposed changes

Added missing utils/ratelimit package. Rel #2902

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by root4loot — COMMENTED** [review]
From https://github.com/projectdiscovery/nuclei/blob/05d607642a11449262fba8d079025dc5325dec8d/v2/pkg/utils/ratelimit/ratelimit.go
https://github.com/projectdiscovery/nuclei/blob/05d607642a11449262fba8d079025dc5325dec8d/v2/pkg/utils/ratelimit/ratelimit_test.go

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
see my reply at https://github.com/projectdiscovery/nuclei/issues/2902#issuecomment-1326835503

**Comment by ehsandeep** [comment]
See https://github.com/projectdiscovery/nuclei/issues/2902#issuecomment-1328058410

**Comment by root4loot** [comment]
@ehsandeep @Mzack9999 see reply [#2902](https://github.com/projectdiscovery/nuclei/issues/2902#issuecomment-1329023271)

**Pull request closed without merging**
