### PR TITLE
fix missing browser init

### LINKED ISSUE #5800: [BUG] Breach of confidentiality?
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

I ran a command and it seems that unintentionally (to me, the user) nuclei is opening 1+ connections to AWS when I run this:

``nuclei -no-interactsh -vv -sa -tlog log  -rl 2 -c 2   -u https://<INTERNAL_TARGET_WITH_FQDN>``

Then, on the scanning machine:

```
prompt> lsof -i -Pn | grep -E 'nuclei|COMMAND'
COMMAND      PID  USER  FD   TYPE DEVICE SIZE/OFF NODE NAME
nuclei    159058 REDCATED 611u  IPv4 349188      0t0  TCP REDACTED:33296->3.78.95.242:465 (ESTABLISHED)
nuclei    159058 REDCATED 611u  IPv4 349188      0t0  TCP REDACTED:40720-> 104.18.36.161:443 (ESTABLISHED)
prompt>
```

Also I see a UDP request after startup to 1.1.1.1:53 . Which fails in this environment but I am wondering what the point is when also the DNS server in the LAN is queried as spotted too.

### Expected Behavior

DO NOT open connections to the cloud unless the user says so. 

### Steps To Reproduce

see above

### Relevant log output

-

### Environment

- OS: Opensuse Leap
- Nuclei: v3.3.5
- Go: doens't matter

### Anything else?

_No response_

### LINKED ISSUE #5880: [BUG] panic SIGSEGV while running  nuclei go library with headless screenshot template
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Getting panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV:segmentation violation code=0x2 addr=0x8 pc=0x1021c5600]

While running nuclei go library with headless template

### Expected Behavior

Run the headless screenshot template and return the output 

### Steps To Reproduce

1. Run the nuclei headless template using nuclei sdk

```go
ctx := context.Background()
	ne, err := nuclei.NewThreadSafeNucleiEngineCtx(ctx,
		// nuclei.WithVerbosity(nuclei.VerbosityOptions{
		// 	Verbose: true,
		// 	Debug:   true,
		// }),
		nuclei.EnableHeadlessWithOpts(&nuclei.HeadlessOpts{
			PageTimeout: 30,
			ShowBrowser: false,
			UseChrome:   false,
		}),
	)
	if err != nil {
		panic(err)
	}
	// setup waitgroup to handle concurrency
	wg := &sync.WaitGroup{}

	// scan 1 = run dns templates on scanme.sh
	wg.Add(1)
	go func() {
		defer wg.Done()
		err = ne.ExecuteNucleiWithOpts([]string{"scanme.sh"}, nuclei.WithTemplateFilters(nuclei.TemplateFilters{IDs: []string{"screenshot"}}))
		if err != nil {
			panic(err)
		}
	}()

	// scan 2 = run http templates on honey.scanme.sh
	wg.Add(1)
	go func() {
		defer wg.Done()
		err = ne.ExecuteNucleiWithOpts([]string{"honey.scanme.sh"}, nuclei.WithTemplateFilters(nuclei.TemplateFilters{IDs: []string{"screenshot"}}))
		if err != nil {
			panic(err)
		}
	}()

	// wait for all scans to finish
	wg.Wait()
	defer ne.Close()
 ```

### Relevant log output

```shell
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1021c5600]

goroutine 5325 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/protocols/headless/engine.(*Browser).UserAgent(...)
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/protocols/headless/engine/engine.go:134
github.com/projectdiscovery/nuclei/v3/pkg/protocols/headless.(*Request).ExecuteWithResults(0x1402424d600, 0x0?, 0x14027855b30, 0x14027855da0, 0x14027855e00)
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/protocols/headless/request.go:50 +0x90
github.com/projectdiscovery/nuclei/v3/pkg/tmplexec/generic.(*Generic).ExecuteWithResults(0x14027f3bef0, 0x14000afbe00)
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/tmplexec/generic/exec.go:61 +0x27c
github.com/projectdiscovery/nuclei/v3/pkg/tmplexec.(*TemplateExecuter).Execute(0x140045fd080, 0x14000afbe00)
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/tmplexec/exec.go:212 +0x33c
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x24cccd0?, 0x40?, 0x14003e2ed40)
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/core/executors.go:139 +0x1a4
created by github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2 in goroutine 5324
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/core/executors.go:115 +0x484
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1021c5600]

goroutine 5249 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/protocols/headless/engine.(*Browser).UserAgent(...)
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/protocols/headless/engine/engine.go:134
github.com/projectdiscovery/nuclei/v3/pkg/protocols/headless.(*Request).ExecuteWithResults(0x1402424d600, 0x0?, 0x14027efc630, 0x14027efc960, 0x14027efc9c0)
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/protocols/headless/request.go:50 +0x90
github.com/projectdiscovery/nuclei/v3/pkg/tmplexec/generic.(*Generic).ExecuteWithResults(0x14027f3bef0, 0x14000c66460)
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/tmplexec/generic/exec.go:61 +0x27c
github.com/projectdiscovery/nuclei/v3/pkg/tmplexec.(*TemplateExecuter).Execute(0x140045fd080, 0x14000c66460)
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/tmplexec/exec.go:212 +0x33c
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x25e03c0?, 0x40?, 0x14004678c80)
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/core/executors.go:139 +0x1a4
created by github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2 in goroutine 5248
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/core/executors.go:115 +0x484
exit status 2
```

### Environment

```markdown
- OS: Mac darwin/arm64
- Nuclei: github.com/projectdiscovery/nuclei/v3 v3.3.7
- Go:  go1.23.1 darwin/arm64
```

### Anything else?

Image

Ref : https://discord.com/channels/695645237418131507/1313145260863393862 (dis

### PR DESCRIPTION
**Pull request by Mzack9999**
## Proposed changes
Closes #5880 

## Example
```console
$ cat example.go
package main

import (
	"context"
	"sync"

	nuclei "github.com/projectdiscovery/nuclei/v3/lib"
)

func main() {

	ctx := context.Background()
	ne, err := nuclei.NewThreadSafeNucleiEngineCtx(ctx,
		// nuclei.WithVerbosity(nuclei.VerbosityOptions{
		// 	Verbose: true,
		// 	Debug:   true,
		// }),
		nuclei.EnableHeadlessWithOpts(&nuclei.HeadlessOpts{
			PageTimeout: 30,
			ShowBrowser: false,
			UseChrome:   false,
		}),
	)
	if err != nil {
		panic(err)
	}
	// setup waitgroup to handle concurrency
	wg := &sync.WaitGroup{}

	// scan 1 = run dns templates on scanme.sh
	wg.Add(1)
	go func() {
		defer wg.Done()
		err = ne.ExecuteNucleiWithOpts([]string{"scanme.sh"}, nuclei.WithTemplateFilters(nuclei.TemplateFilters{IDs: []string{"screenshot"}}))
		if err != nil {
			panic(err)
		}
	}()

	// scan 2 = run http templates on honey.scanme.sh
	wg.Add(1)
	go func() {
		defer wg.Done()
		err = ne.ExecuteNucleiWithOpts([]string{"honey.scanme.sh"}, nuclei.WithTemplateFilters(nuclei.TemplateFilters{IDs: []string{"screenshot"}}))
		if err != nil {
			panic(err)
		}
	}()

	// wait for all scans to finish
	wg.Wait()
	defer ne.Close()
}
$ go run .
$
```

## Summary by CodeRabbit

- **New Features**
	- Added a `Browser` field to enhance execution options within the Nuclei engine.
	- Improved request handling capabilities by integrating a customizable HTTP client.

- **Bug Fixes**
	- Updated error formatting in output for improved clarity in error messages during tests.
	- Adjusted template validation handling to bypass strict checks temporarily.

- **Chores**
	- Updated dependency status and handled version retraction for improved project stability.
	- Modified multi-protocol request test case configuration for refined HTTP matching criteria.

### CODE REVIEW

**Comment by jeyaseelans86** [comment]
Getting new errors now

While running with https:// or http:// protocol 

`err = ne.ExecuteNucleiWithOpts([]string{"https://scanme.sh"}, nuclei.WithTemplateFilters(nuclei.TemplateFilters{IDs: []string{"screenshot"}}))
`

Gives me

``` panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1057c9734]

goroutine 9766 [running]:
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).DialTLS(0x0, {0x107d6de70, 0x140026ee0f0}, {0x106ba6dcb, 0x3}, {0x140083f7181, 0xd})
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/fastdialer@v0.2.10/fastdialer/dialer.go:212 +0x34
github.com/projectdiscovery/nuclei/v3/pkg/protocols/headless/engine.newHttpClient.func1({0x107d6de70?, 0x140026ee0f0?}, {0x106ba6dcb?, 0x1052faa8c?}, {0x140083f7181?, 0x140078f4f00?})
        /Users/jeya-12107/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.3.7/pkg/protocols/headless/engine/http_client.go:52 +0xa8
net/http.(*Transport).customDialTLS(0x140092eea78?, {0x107d6de70?, 0x140026ee0f0?}, {0x106ba6dcb?, 0x30bc93e806994e58?}, {0x140083f7181?, 0x140092eea88?})
        /opt/homebrew/Cellar/go/1.23.1/libexec/src/net/http/transport.go:1418 +0x50
net/http.(*Transport).dialConn(0x14000448300, {0x107d6de70, 0x140026ee0f0}, {{}, 0x0, {0x14006994e58, 0x5}, {0x140083f7181, 0xd}, 0x0})
        /opt/homebrew/Cellar/go/1.23.1/libexec/src/net/http/transport.go:1704 +0x2f0
net/http.(*Transport).dialConnFor(0x14000448300, 0x1400287a9a0)
        /opt/homebrew/Cellar/go/1.23.1/libexec/src/net/http/transport.go:1563 +0x8c
net/http.(*Transport).startDialConnForLocked.func1()
        /opt/homebrew/Cellar/go/1.23.1/libexec/src/net/http/transport.go:1545 +0x34
created by net/http.(*Transport).startDialConnForLocked in goroutine 9765
        /opt/homebrew/Cellar/go/1.23.1/libexec/src/net/http/transport.go:1544 +0x118
exit status 2 ``` 




```

While running without https:// or http:// protocol , Getting this error 

`err = ne.ExecuteNucleiWithOpts([]string{"scanme.sh"}, nuclei.WithTemplateFilters(nuclei.TemplateFilters{IDs: []string{"screenshot"}}))`

```[WRN] [screenshot] Could not execute request for scanme.sh: could not get html element: error occurred executing action: [:RUNTIME] could not navigate to url scanme.sh <- {-32000 Cannot navigate to invalid URL }```

@Mzack9999 Pl check

**Comment by Mzack9999** [comment]
@jeyaseelans86 This should be fixed with latest commit, nice catch!

**Review by dogancanbakir — APPROVED** [review]
LGTM -some tests are failing

**Comment by Mzack9999** [comment]
@coderabbitai resolve

**Comment by Mzack9999** [comment]
@coderabbitai ignore

**Comment by Mzack9999** [comment]
@coderabbitai resolve

**Comment by Mzack9999** [comment]
@coderabbitai ignore

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
