### PR TITLE
Adding stop-resume support

### PR DESCRIPTION
**Pull request by Mzack9999**
## Proposed changes

The PR adds resume support.
- The progression is stored as json in `config.cfg` if the user presses CTRL+C in the terminal
- The `-resume` CLI flag load the latest checkpoint and skips all the target already elaborated 

## Checklist
- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by Ice3man543 — APPROVED** [review]
lgtm! Nice work @Mzack9999!

**Comment by Mzack9999** [comment]
Suggestions from @parrasajad:

- [ ] Move tracking logic at the bottom of `hmap.Scan` as ongoing unfinished templates are skipped on resume
- [ ] Move `resume.cfg` from current folder to nuclei config folder
- [ ]`resume.cfg` can be affected by name collision for multiple running instances (use customizable name via CLI param?)
- Store payloads value to track in-template progress?

**Comment by parrasajad** [comment]
with latest changes it doesn't skip the templates/requests which were completed previously

**Comment by parrasajad** [comment]
lgtm!

**Review by ehsandeep — APPROVED** [review]

**Comment by forgedhallpass** [comment]
@Mzack9999 @ehsandeep 

> [ ] resume.cfg can be affected by name collision for multiple running instances (use customizable name via CLI param?)

What about this? It seems to be a valid point.

**Comment by ehsandeep** [comment]
@forgedhallpass running multiple instances of nuclei from the **same** machine at the same time is not expected use, so it should be fine but if it becomes an issue at some point, we can update it accordingly.

**Comment by forgedhallpass** [comment]
Do we have a validation that prevents it? If not, shouldn't we at least give an error message or something?

**Comment by Mzack9999** [comment]
tracked at https://github.com/projectdiscovery/nuclei/issues/1538

**Pull request merged**
