### PR TITLE
fix url re-encoding issues

### LINKED ISSUE #3292: double url encoding issue in non-unsafe templates
### Nuclei version:

dev | main

### Current Behavior:

```yaml
requests:
  - raw:
    - |+
        GET {{Path}}%0D%0ASet-Cookie:crlfinjection=crlfinjection HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2820.59 Safari/537.36
        Connection: close
```
Nuclei while running this template double encodes the payload and dumps below http request

```console
[INF] [crlf-injection] Dumped HTTP request for https://example.com/foo/%0D%0ASet-Cookie:crlfinjection=crlfinjection

GET /foo/%250D%250ASet-Cookie:crlfinjection=crlfinjection HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2820.59 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip
```

### Expected Behavior:

- If possible nuclei should avoid double url encoding special characters 

### Anything else:

- cause https://github.com/projectdiscovery/utils/blob/main/url/README.md

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
## Proposed changes

- fix url re-encoding issue in `non-unsafe` templates

closes #3292 

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
```console
$ ./nuclei -u scanme.sh -t ~/test/url-encode.yaml -debug

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.8

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.8 (latest)
[INF] Using Nuclei Templates 9.3.6 (latest)
[INF] Templates added in last update: 30
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] [basic-raw-example] Dumped HTTP request for https://scanme.sh/


GET /%0D%0A HTTP/1.1
Host: scanme.sh
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[DBG] [basic-raw-example] Dumped HTTP response https://scanme.sh/


HTTP/1.1 200 OK
Connection: close
Content-Length: 2
Content-Type: text/plain; charset=utf-8
Date: Thu, 09 Feb 2023 13:19:07 GMT

ok
[INF] [basic-raw-example] Dumped HTTP request for https://scanme.sh/
Set-Cookie:crlfinjection=crlfinjection

GET /%0D%0ASet-Cookie:crlfinjection=crlfinjection HTTP/1.1
Host: scanme.sh
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2820.59 Safari/537.36
Connection: close
Accept-Encoding: gzip

[DBG] [basic-raw-example] Dumped HTTP response https://scanme.sh/
Set-Cookie:crlfinjection=crlfinjection

HTTP/1.1 200 OK
Connection: close
Content-Length: 2
Content-Type: text/plain; charset=utf-8
Date: Thu, 09 Feb 2023 13:19:07 GMT

ok
[INF] No results found. Better luck next time!

```

**Comment by tarunKoyalwar** [comment]
Example Template
```yaml
id: basic-raw-example

info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/%0D%0A"

  - raw:
    - |+
        GET %0D%0ASet-Cookie:crlfinjection=crlfinjection HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2820.59 Safari/537.36
        Connection: close

    stop-at-first-match: true
    matchers:
      - type: regex
        regex:
          - '(?m)^(?:Set-Cookie\s*?:(?:\s*?|.*?;\s*?))(crlfinjection=crlfinjection)(?:\s*?)(?:$|;)'%       
```

**Review by Mzack9999 — APPROVED** [review]

**Review by ehsandeep — CHANGES_REQUESTED** [review]
Line break in verbose / debug mode.

```console
[INF] [basic-raw-example] Dumped HTTP request for https://scanme.sh/
Set-Cookie:crlfinjection=crlfinjection
```

**Comment by tarunKoyalwar** [comment]
```console
$ ./nuclei -u scanme.sh -t ~/test/url-encode.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.8

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.8 (latest)
[INF] Using Nuclei Templates 9.3.6 (latest)
[INF] Templates added in last update: 30
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[VER] [basic-raw-example] Sent HTTP request to https://scanme.sh/%0D%0A
[VER] [basic-raw-example] Sent HTTP request to https://scanme.sh/%0D%0ASet-Cookie:crlfinjection=crlfinjection
[INF] No results found. Better luck next time!

```

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
