### PR TITLE
Issue 2987 fuzz options

### PR DESCRIPTION
**Pull request by ShubhamRasal**
```
./nuclei -u "http://127.0.0.1:8082/email?text=important_user&text2=abc" -t ~/workspace/projectdisovery/fuzzing-templates/xss -silent
[reflected-xss] [http] [medium] http://127.0.0.1:8082/email?text=important_user'"><80478&text2=abc
```
Override type and mode using flag: 
```
./nuclei -u "http://127.0.0.1:8082/email?text=important_user&text2=abc" -t ~/workspace/projectdisovery/fuzzing-templates/xss -fm multiple -ft prefix -silent
[reflected-xss] [http] [medium] http://127.0.0.1:8082/email?text='"><78899important_user&text2='"><78899abc
```

### CODE REVIEW

**Review by tarunKoyalwar — APPROVED** [review]
lgtm!

**Review by ehsandeep — CHANGES_REQUESTED** [review]
@ShubhamRasal, Can we add tests for this option as we have for others.

**Review by Mzack9999 — APPROVED** [review]
lgtm - I couldn't find CLI override tests for other parameters such as `AttackType`. @ehsandeep, did you mean to implement functional tests?

**Comment by tarunKoyalwar** [comment]
@ehsandeep @Mzack9999 not sure functional tests but I think we can implement this in integration_test since it has option to pass extra cli args

**Comment by ShubhamRasal** [comment]
Agree with @tarunKoyalwar,  I'll add the integration test to validate override fuzzing options.

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
