### PR TITLE
Update bulk-http-request.go

### PR DESCRIPTION
**Pull request by un-fmunozs**
#224

### CODE REVIEW

**Comment by bauthard** [comment]
Hey @un-fmunozs, 

I've created an issue https://github.com/projectdiscovery/nuclei/issues/226 for connection header, it's an issue with multiple request types, so I will hold this PR before we fix them all, another thing, we are keeping User-agent as default header, with no intention to remove it.

**Comment by bauthard** [comment]
Also before we fix this @un-fmunozs do you mind sharing where this is an issue in the real world? I mean why would you need `Connection: keep-alive` instead of `Connection: close` while running nuclei? 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection

**Comment by un-fmunozs** [comment]
I've not come with an use case yet sorry, but I expected a raw request to include exactly what I put on the template, that's my opinion for Connection and User-Agent.

**Comment by bauthard** [comment]
Thank you @un-fmunozs for the input, unless this is an issue we are keeping it as this way only, I will add details about default header somewhere in the readme so others also know about this.

**Pull request closed without merging**
