### PR TITLE
fix: if Output is set as nil in options, this will crash the application

### PR DESCRIPTION
**Pull request by TheSecEng**
Fixing error where a custom runner implements options without output

### CODE REVIEW

**Comment by ehsandeep** [comment]
Hi @TheSecEng, Thank you for the proposed fix, Can you please point these changes (including other PRs) along with [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch to avoid any conflict changes.

**Comment by TheSecEng** [comment]
Done, also there is likely a better implementation to be done here. Happy to spend time on it if I can get feedback

**Review by Ice3man543 — COMMENTED** [review]
There are more usages of r.options.Output in other protocols like `v2/pkg/protocols/dns`, etc. We need to account for these as well.

**Comment by Ice3man543** [comment]
Another idea to pursue could be create a common function that handles all the results from all protocols, instead of calling `r.options.Output` and tons of other stuff for writing output. Maybe we can do a separate package or function.

**Comment by TheSecEng** [comment]
> Another idea to pursue could be create a common function that handles all the results from all protocols, instead of calling `r.options.Output` and tons of other stuff for writing output. Maybe we can do a separate package or function.

I agree that would be a better approach. This would solve another issue of how to get results from Workflows. As that is currently not possible. With plain templates we can call `ExecuteWithResults` but for Workflows, there is no way to retrieve results logically.

**Comment by TheSecEng** [comment]
Closing to break out into a full solution

**Pull request closed without merging**
