### PR TITLE
Evaluate payload variables

### PR DESCRIPTION
**Pull request by ShubhamRasal**
Fixes:

- #2636 
- #2984 
- #2984
- #3161
- #3479

<details>
<summary> Template </summary>

```
id: test
info:
  name: Auto Discover Information Disclosure
  author: td4b
requests:
  - method: GET
    path:
      - "https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml"
    headers:
      Authorization: Basic {{base64(username + ':' + password)}}
    attack: pitchfork
    payloads:
      username:
        - jon.doe@{{ Hostname }}
      password:
        - dsabkuasbdaobfdugkh
    matchers:
      - type: status
        status:
          - 401
```
</details>

```
❯ ./nuclei -u https://example.com -t test-template.yaml -dreq  -svd 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.1-dev

		projectdiscovery.io


[DBG] Final Protocol request variables: 
	1. password => dsabkuasbdaobfdugkh
	2. Host => example.com
	3. BaseURL => https://example.com
	4. SD => 
	5. Port => 443
	6. Scheme => https
	7. RDN => example.com
	8. RootURL => https://example.com
	9. Path => 
	10. username => jon.doe@example.com
	11. File => 
	12. TLD => com
	13. DN => example
	14. ip => 
	15. FQDN => example.com
	16. Hostname => example.com

[INF] [test] Dumped HTTP request for https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml

GET /autodiscover/autodiscover.xml HTTP/1.1
Host: autodiscover-s.outlook.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2866.71 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Authorization: Basic am9uLmRvZUBleGFtcGxlLmNvbTpkc2Fia3Vhc2JkYW9iZmR1Z2to
Accept-Encoding: gzip

[WRN] [test] Could not execute request for https://example.com: context deadline exceeded
[INF] No results found. Better luck next time!
```

Confirm payload variables are evaluated
```
❯ echo am9uLmRvZUBleGFtcGxlLmNvbTpkc2Fia3Vhc2JkYW9iZmR1Z2to | base64 -d
jon.doe@example.com:dsabkuasbdaobfdugkh
```

### CODE REVIEW

**Review by ehsandeep — APPROVED** [review]

**Review by ehsandeep — CHANGES_REQUESTED** [review]
@ShubhamRasal we can extend `integration_tests/http/variables.yaml` to cover new scenarios covered in this PR?

**Review by tarunKoyalwar — CHANGES_REQUESTED** [review]
Implementation lgtm !

nice catch on moving interactsh payload evalutation to `Make` !!

variables are also supported/used in other protocols apart from http . this PR only adds lazyeval support for http protocol . I think we can make it consistent across all protocols headless,dns,network etc

**Comment by Mzack9999** [comment]
Converting back draft until extensions are implemented

**Review by tarunKoyalwar — APPROVED** [review]
lgtm! 

after discussion with @ShubhamRasal looks like implementing `lazy var` fixed the issue in dns and other protocols

**Review by Mzack9999 — APPROVED** [review]
Implementation: lgtm for one nested level down

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
