### PR TITLE
Misc changes to update logic

### PR DESCRIPTION
**Pull request by Ice3man543**
## Proposed changes

Should close 

- [x] #1196, 
- [x] #1195
- [x] #1194

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by ehsandeep — CHANGES_REQUESTED** [review]
- [ ] https://github.com/projectdiscovery/nuclei/issues/1196

The above issue is still not fixed, to reproduce, make sure you have the default template installed already and run the following:-

```
./nuclei -update-templates -update-directory ./templates

[INF] No new updates found for nuclei templates
```

The expected behavior is to install nuclei template to a given custom directory that is not same as the current default and update the new path as default path in the template config file.

**Comment by Ice3man543** [comment]
@ehsandeep it works correctly as expected for me.

```
> ./nuclei -update-templates -update-directory ./templates

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.5.4-dev

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] nuclei-templates are not installed, installing...
[INF] Successfully downloaded nuclei-templates (v8.6.8) to /Users/ice3man/projectdiscovery/nuclei/v2/cmd/nuclei/templates. GoodLuck!

 > cat ~/.config/nuclei/.templates-config.json 
{"nuclei-templates-directory":"/Users/ice3man/projectdiscovery/nuclei/v2/cmd/nuclei/templates","nuclei-templates-version":"8.6.8","nuclei-version":"2.5.4-dev","nuclei-ignore-hash":"7e404e94b241604ce419690b689c5b6d","nuclei-latest-version":"2.5.3","nuclei-templates-latest-version":"8.6.8"}
```

**Review by ehsandeep — APPROVED** [review]

**Comment by ehsandeep** [comment]
@sullo all the linked issues should be fixed with this PR in the dev version.

**Comment by forgedhallpass** [comment]
Have you also tested for https://github.com/projectdiscovery/nuclei/issues/1324?

**Comment by ehsandeep** [comment]
@forgedhallpass yes, this PR also fixes the issue mentioned in #1324

**Pull request merged**
