### PR TITLE
add response read timeout flag

### LINKED ISSUE #4942: invalid behaviour for big http responses (files)
Hi

I think the problem is connected with #4722 and such code:
```
respChain := httpUtils.NewResponseChain(resp, maxBodylimit)
```

Right now if the response is really big nuclei throws error:

```
 could not generate response chain: error reading response body: could not read response body: http: request body too large
```

### Nuclei version:
v3.2.2

### Current Behavior:
throws error

### Expected Behavior:
correctly handles the file

### Steps To Reproduce:

```
id: fuzz-dirs

info:
  name: fuzz-dirs
  author: savik
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    skip-variables-check: true
    matchers:
      - type: status
        condition: or
        status:
          - 200
          - 201
          - 204
          - 206
          - 304
          - 500
  ```

```
 nuclei -t template.yaml -target https://download.binance.com/electron-desktop/mac/production/binance.dmg --debug
```

Regards

### PR DESCRIPTION
**Pull request by dogancanbakir**
## Proposed changes

Closes  #4942.

test_template.yaml:
```yaml
id: fuzz-dirs

info:
  name: fuzz-dirs
  author: savik
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    skip-variables-check: true
    matchers:
      - type: status
        condition: or
        status:
          - 200
          - 201
          - 204
          - 206
          - 304
          - 500
```

```console
$ go run . -t test_template.yaml -u https://download.binance.com/electron-desktop/mac/production/binance.dmg -rsr 324009984 -rrt 10

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

                projectdiscovery.io

[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loaded 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[fuzz-dirs] [http] [info] https://download.binance.com/electron-desktop/mac/production/binance.dmg

```

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by tarunKoyalwar — CHANGES_REQUESTED** [review]
i think max-http-body-size is meant to be handled gracefully ( without error and only use first 4MB) . but currently it errors which is not expected behaviour 

```console
$ ./nuclei -t fuzz.yaml  -target https://download.binance.com/electron-desktop/mac/production/binance.dmg --debug

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

		projectdiscovery.io

[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loaded 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] [fuzz-dirs] Dumped HTTP request for https://download.binance.com/electron-desktop/mac/production/binance.dmg

GET /electron-desktop/mac/production/binance.dmg HTTP/1.1
Host: download.binance.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:109.0) Gecko/20100101 Firefox/122.0
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[WRN] [fuzz-dirs] Could not execute request for https://download.binance.com/electron-desktop/mac/production/binance.dmg: [:RUNTIME] got err while executing https://download.binance.com/electron-desktop/mac/production/binance.dmg <- could not generate response chain: error reading response body: could not read response body: http: request body too large
[INF] No results found. Better luck next time!
```

keeping the 4MB limit , i think we should handle errors returned by responseChain in protocols/http/http.go more appropriately i.e in this case , we can warn user and use the first 4MB instead of erroring out

**Comment by dogancanbakir** [comment]
depends on https://github.com/projectdiscovery/utils/pull/378

**Comment by dogancanbakir** [comment]
```console
go run . -t test_template.yaml -u https://download.binance.com/electron-desktop/mac/production/binance.dmg 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

                projectdiscovery.io

[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loaded 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[fuzz-dirs] [http] [info] https://download.binance.com/electron-desktop/mac/production/binance.dmg
```

**Review by tarunKoyalwar — CHANGES_REQUESTED** [review]
lgtm ! implementation wise

```console
$  ./nuclei -t a.yaml  -target https://download.binance.com/electron-desktop/mac/production/binance.dmg --debug-req -v -svd             

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v3.2.2 (outdated)
[INF] Current nuclei-templates version: v9.8.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 77
[INF] Templates loaded for current scan: 1
[WRN] Loaded 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[DBG] HTTP Protocol request variables: 
	1. BaseURL => https://download.binance. .... ac/production/binance.dmg
	2. DN => binance
	3. FQDN => download.binance.com
	4. File => binance.dmg
	5. Host => download.binance.com
	6. Hostname => download.binance.com
	7. Input => https://download.binance. .... ac/production/binance.dmg
	8. Path => /electron-desktop/mac/production
	9. Port => 443
	10. RDN => binance.com
	11. RootURL => https://download.binance.com
	12. SD => download
	13. Scheme => https
	14. TLD => com
	15. ip => 

[INF] [fuzz-dirs] Dumped HTTP request for https://download.binance.com/electron-desktop/mac/production/binance.dmg

GET /electron-desktop/mac/production/binance.dmg HTTP/1.1
Host: download.binance.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[VER] [fuzz-dirs] Sent HTTP request to https://download.binance.com/electron-desktop/mac/production/binance.dmg
[DBG] Http Protocol response variables: 
	1. BaseURL => https://download.binance. .... ac/production/binance.dmg
	...
	44. x_nuclei_ignore_error => http: request body too large

[fuzz-dirs:body] [http] [info] https://download.binance.com/electron-desktop/mac/production/binance.dmg [1.048576e+07]
```

> 44. x_nuclei_ignore_error => http: request body too large


## More

- requesting changes in context of
   - merge conflict
   - integration test failure ( most likely flaky test but we should confirm just in case )

**Comment by tarunKoyalwar** [comment]
## minor update
- due to incorrect time unit `response-read-timeout` value was set to 5 ns instead of 5 sec which caused network tests to fail
```
 ./nuclei -h |& grep read-timeout
   -rrt, -response-read-timeout value    response read timeout in seconds (default 5ns)
   -irt, -input-read-timeout value  timeout on input read (default 3m0s)
```

also we have asnmap <-> nuclei unit test , looks like we need to add env secret with pdcp key cc: @ehsandeep @dogancanbakir

**Comment by dogancanbakir** [comment]
oh yes!

**Review by tarunKoyalwar — APPROVED** [review]
lgtm!

the failing test seems to be specific to windows environment for scan-all-ips feature ,  i think we can track and fix it in follow-up pr since it doesn't seem to be related to this and is specific to windows

cc: @dogancanbakir @ehsandeep

**Review by ehsandeep — APPROVED** [review]

**Comment by savushkin-yauheni** [comment]
Hi @dogancanbakir @ehsandeep 
I'm the author of #4942 

Right now we have a bug in final calculation of `maxBodylimit`:

```
	maxBodylimit := MaxBodyRead // 10MB

	gologger.Info().Msgf("1: %s", maxBodylimit)
	if request.MaxSize > 0 {
		maxBodylimit = int64(request.MaxSize)
		gologger.Info().Msgf("2: %s", maxBodylimit)

	}
	if request.options.Options.ResponseReadSize != 0 {
		maxBodylimit = int64(request.options.Options.ResponseReadSize)
		gologger.Info().Msgf("3: %s", maxBodylimit)

	}
```

```
[INF] 1: %!s(int64=4194304)
[INF] 2: %!s(int64=20485760)
[INF] 3: %!s(int64=10485760)
```

So even if I set up`max-size` in template it would be overwritten by such code:

```
if request.options.Options.ResponseReadSize != 0 {
		maxBodylimit = int64(request.options.Options.ResponseReadSize)		
}
```

Regards

**Comment by savushkin-yauheni** [comment]
@dogancanbakir 
But it doesn't make sense. does it mean that we can't control max-size through templates? 
If so, why do we need it at all.

**Comment by dogancanbakir** [comment]
Yes; creating another issue to work on this.

**Pull request merged**
