### PR TITLE
Added dynamic field in info key support

### PR DESCRIPTION
**Pull request by Ice3man543**
This PR adds support for #259 allowing dynamic key value pairs to be placed in `info` block of a template which will be displayed if the user opts for json output on being matched.

Example - 

```
id: cname-service-detector

info:
  name: 3rd party service checker
  author: bauthard
  severity: info
  advisory: https://test-site.com/some-random-advisory.html

dns:
  - name: "{{FQDN}}"
    type: CNAME
    class: inet
    recursion: true
    retries: 5
    matchers-condition: or
    matchers:
      - type: word
        name: zendesk
        words:
          - "zendesk.com"
      - type: word
        name: github
        words:
          - "github.io"
```

This gives the following output - 

```
 ./nuclei -t template.yaml -l list.txt -json

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1.1

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Loading templates...
[INF] [cname-service-detector] 3rd party service checker (@bauthard) [info]
[INF] Using 1 rules (1 templates, 0 workflows)
{"matcher_name":"zendesk","template":"cname-service-detector","type":"dns","matched":"support.hackerone.com","name":"3rd party service checker","author":"bauthard","severity":"info","advisory":"https://test-site.com/some-random-advisory.html"}
{"type":"dns","matched":"docs.hackerone.com","severity":"info","advisory":"https://test-site.com/some-random-advisory.html","name":"3rd party service checker","author":"bauthard","matcher_name":"github","template":"cname-service-detector"}
```

### CODE REVIEW

**Comment by L0uisJ0shua** [comment]
Is this feature removed? I cannot seem to add dynamic field into the template for info block anymore for nuclei custom template.

**Comment by ehsandeep** [comment]
@L0uisJ0shua it's moved under metadata section, for example:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info
  metadata:
    key: value
    x: y
```

**Comment by L0uisJ0shua** [comment]
> @L0uisJ0shua it's moved under metadata section, for example:
> 
> ```yaml
> id: basic-example
> 
> info:
>   name: Test HTTP Template
>   author: pdteam
>   severity: info
>   metadata:
>     key: value
>     x: y
> ```

Should we update the template documentation? I can help with this. The documentation state that dynamic field can be added under the info block, but did not really mentioned specifically under the metadata block.

image

**Comment by ehsandeep** [comment]
@L0uisJ0shua, for sure! Please feel free to open PR with updated docs.

**Pull request merged**
