### PR TITLE
Refactoring variables logic with map + get public ip

### LINKED ISSUE #3852: Add helper to get public ip
### Please describe your feature request:
It would be useful to add the following helpers:
- Public IP (eg `{{public_ip()}}`)

### Describe the use case of this feature:
Ex: authentication mechanism and form filling requiring public IP information

### PR DESCRIPTION
**Pull request by Mzack9999**
## Proposed changes
Adds the new helper function `public_ip()`

Depends on https://github.com/projectdiscovery/dsl/pull/47
Closes #3852 

## Example
```console
$ cat test.yaml
id: test

info:
  name: test
  author: test
  severity: info
  tags: tech

http:
  - method: GET
    path:
      - "{{BaseURL}}/{{public_ip()}}"
$ echo http://192.168.5.1 | go run . -t test.yaml -v
[VER] [test] Sent HTTP request to http://192.168.5.1/xxx.xxx.xxx.xxx
```

## Checklist
- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by dogancanbakir — COMMENTED** [review]
I got different results each time:
```
$ cat test.yaml 
id: test

info:
  name: test
  author: test
  severity: info
  tags: tech

http:
  - method: GET
    path:
      - "{{BaseURL}}/{{public_ip()}}"
```

```
$ echo scanme.sh | go run . -t test.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io

[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[WRN] [test] Could not make http request for https://scanme.sh: unresolved variables found: public_ip%28%29
[INF] No results found. Better luck next time!
```

```
$ echo scanme.sh | go run . -t test.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io

[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[WRN] [test] Could not execute request for scanme.sh: context deadline exceeded
[INF] No results found. Better luck next time!
```

```
$ echo scanme.sh | go run . -t test.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io

[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[VER] [test] Sent HTTP request to https://scanme.sh/42.42.42.42
[INF] No results found. Better luck next time!
```

**Comment by Mzack9999** [comment]
Looks like the third party used to obtain the public ip has heavy rate limiting - Switching it to something else

**Comment by Mzack9999** [comment]
@dogancanbakir thanks for testing - I switched to aws endpoint which seems more stable

**Review by dogancanbakir — APPROVED** [review]
LGTM

```
$ seq 10 | xargs -I{} -P 10 bash -c "echo scanme.sh | go run . -t test.yaml -v"

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io

[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Running httpx on input host
[INF] Running httpx on input host
[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Running httpx on input host
[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1[INF] Current nuclei version: v2.9.6 (latest)

[INF] Targets loaded for current scan: 1[INF] Current nuclei-templates version: v9.5.3 (latest)

[INF] Running httpx on input host
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Running httpx on input host
[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] Found 1 URL from httpx
[INF] Found 1 URL from httpx
[INF] Found 1 URL from httpx
[INF] Found 1 URL from httpx
[INF] Found 1 URL from httpx
[INF] Found 1 URL from httpx
[INF] Found 1 URL from httpx
[INF] Found 1 URL from httpx
[INF] Found 1 URL from httpx
[VER] [test] Sent HTTP request to https://scanme.sh/42.42.42.42
[INF] No results found. Better luck next time!
[VER] [test] Sent HTTP request to https://scanme.sh/42.42.42.42
[INF] No results found. Better luck next time!
[VER] [test] Sent HTTP request to https://scanme.sh/42.42.42.42
[INF] No results found. Better luck next time!
[VER] [test] Sent HTTP request to https://scanme.sh/42.42.42.42
[INF] No results found. Better luck next time!
[VER] [test] Sent HTTP request to https://scanme.sh/42.42.42.42
[INF] No results found. Better luck next time!
[VER] [test] Sent HTTP request to https://scanme.sh/42.42.42.42
[INF] No results found. Better luck next time!
[VER] [test] Sent HTTP request to https://scanme.sh/42.42.42.42
[INF] No results found. Better luck next time!
[VER] [test] Sent HTTP request to https://scanme.sh/42.42.42.42
[INF] No results found. Better luck next time!
[VER] [test] Sent HTTP request to https://scanme.sh/42.42.42.42
[INF] No results found. Better luck next time!
[VER] [test] Sent HTTP request to https://scanme.sh/42.42.42.42
[INF] No results found. Better luck next time!
```

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !

```console
$ echo scanme.sh | ./nuclei -t ~/test-templates/publicip.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

		projectdiscovery.io

[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[VER] [test] Sent HTTP request to https://scanme.sh/103.175.170.178
[INF] No results found. Better luck next time!

```

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
