### PR TITLE
Extending deny list to support filenames and folders

### PR DESCRIPTION
**Pull request by Mzack9999**
## Proposed changes

This PR extends the deny list functionality in file requests in order to support file and directory exclusions

## Checklist
- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by Ice3man543 — APPROVED** [review]
lgtm!

**Review by ehsandeep — CHANGES_REQUESTED** [review]
@Mzack9999 it took some time but here are all the details we required related to file/folder exclusion for the file templates, currently, the 2nd and 5th rules are supported, and others need to be supported.

```yaml
    denylist:
      - /Users/xx/nuclei-templates/cves/ # excludes all the directory / subdirectory under "/Users/xx/nuclei-templates/cves/*"
      - /Users/xx/nuclei-templates/vulnerabilities/jira/jira-unauthenticated-projects.yaml  # excludes specfic file /Users/xx/nuclei-templates/vulnerabilities/jira/jira-unauthenticated-projects.yaml
      - dns/ # excludes $INPUT_PATH/dns/*
      - exposed-panels/cortex-xsoar-login.yaml # excludes $INPUT_PATH/exposed-panels/cortex-xsoar-login.yaml
      - .txt  # excludes all the files with TXT extesioin

      # $INPUT_PATH is what we receive as an input directory/path to perform file scan using "-u" or "list" flag.
      # nuclei -t file/ -u http_data/, here "http_data" is $INPUT_PATH
```

**Review by ehsandeep — APPROVED** [review]
Test fails are expected due to the use of old version of nuclei.

**Comment by forgedhallpass** [comment]
We might want to move the hard-coded

https://github.com/projectdiscovery/nuclei/blob/c4d1b03f5cfb633bad7e49fc8c45fbcbcb37fcb9/v2/pkg/protocols/file/file.go#L70

to the default configuration as well.

**Pull request merged**
