### PR TITLE
Progress tracking logic

### PR DESCRIPTION
**Pull request by Mzack9999**
- Methods refactor
- Counter logic fixes

### CODE REVIEW

**Comment by Mzack9999** [comment]
The original `DecrementRequests` added the failed requests amount instead of subtracting, leading to a double increment. The only fixed protocol is HTTP.
Todo: check the progress logic across all protocols

**Comment by ehsandeep** [comment]
I can confirm this issue is fixed and not reproducible anymore.

**Comment by geeknik** [comment]
In my experience since this was pushed, the stats counter now underflows. Adding up the Errors and Requests doesn't equal 100% either. It would be great if we could know the state of the error as in what kind is it, where is it happening (client or server side), etc., but that is beyond the scope of this bug.

**Comment by Mzack9999** [comment]
I tested again, but it looks like that this behavior happens only when the progress snapshot is done when the scan is not complete yet. I added one final print of the summary upon scan termination.

**Pull request merged**
