### PR TITLE
[WIP] Fuzzing + DSL support in requests

### PR DESCRIPTION
**Pull request by Mzack9999**
- Added Intruder like functionalities (Sniper, Pitch Fork, Cluster Bomb)
- Added placeholders variables (like in burp) + DSL helper functions (similar to hackvector). This should solve #4 and extend it

As of now lot of code is redundant and it only works with raw requests with defined payloads, like the following one:

```
id: dummy-fuzz-raw-with-params

info:
  name: Dummy Raw Request
  author: mzack9999
  severity: none

requests:
  - payloads:
      param_a: /tmp/wordlist_a.txt
      param_b: /tmp/wordlist_b.txt
    attack: clusterbomb # Can be sniper, pitchfork, clusterbomb
    raw:
      - | 
          GET /path1/ HTTP/1.1
          User-Agent: {{param_a}}
          Host: {{Hostname}}
          AnotherHeader: {{base64(md5(param_a))}}
          Accept: */*

          {{html_escape(toupper(param_b))}}
      - | 
          GET /path2/ HTTP/1.1
          User-Agent: mz
          Host: {{Hostname}}
          Accept: a/b
    matchers:
      - type: word
        words: 
          - "anything"
```

### CODE REVIEW

**Comment by bauthard** [comment]
Few additions:- 

+ Validation for the `Payload` input file (missing or not accessible)
+ Print the used attack type/payload input file information on the start. 
+ Ways to display/save payload details on the matched request.

**Comment by Mzack9999** [comment]
Closes #77

**Comment by Mzack9999** [comment]
Closes #75

**Comment by bauthard** [comment]
Everything looks good to me, lots of new features :D

**Comment by Zeokat** [comment]
Seems that this PR needs some deep testing. I will run some tests huntings for bugs at the weekend.

**Pull request merged**
