### PR TITLE
Replacing ccache with generic gcache

### PR DESCRIPTION
**Pull request by Mzack9999**
## Proposed changes
This PR implements the following changes:
- Really stop execution after first interactsh match (previously: only first match was printed as output, but execution continued under the hood)
- Replace ccache with auto-prune gcache (doesn't crash if used after close)
- Drop the need of some lock mechanism to avoid data-race

## Checklist
- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Notes
- The logic needs still a radical rework to avoid contrived intersected callbacks, ideally the flow should look like the following one:
    - Requests invoke `.URL()` and their unique id gets registered
    - Asyncronously interactions are received and matched with the requestId
    - No matching logic/output whatsover should be contained in the interactsh package wrapper (this will avoid endless cases of data race and missed interactions)
    - On request id eviction the matching/extraction/output logic is executed in the caller protocol context

Tracked at https://github.com/projectdiscovery/nuclei/issues/3437 (the current PR implement preparatory changes)

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
coverting this to draft since there seems to be another deadlock

**Comment by tarunKoyalwar** [comment]
@Mzack9999  @ehsandeep , interactsh related integrations tests seems to be uncertain especially with gh actions . sometimes locally I was also getting failed ^ tests . 

- Previous Commit seperates adds/reorders interactsh related integration_test to new group/section and by default we consider **best of 3** as result for these tests

```console
$ for i in {1..10}; do; ./integration-test -protocol interactsh; done    1 ↵
[✓] Test "http/default-matcher-condition.yaml" passed!
[✓] Test "http/interactsh-stop-at-first-match.yaml" passed!
[✓] Test "http/interactsh.yaml" passed!
[✓] Test "http/default-matcher-condition.yaml" passed!
[✓] Test "http/interactsh-stop-at-first-match.yaml" passed!
[✓] Test "http/interactsh.yaml" passed!
[✓] Test "http/default-matcher-condition.yaml" passed!
[✓] Test "http/interactsh-stop-at-first-match.yaml" passed!
[✓] Test "http/interactsh.yaml" passed!
[✓] Test "http/default-matcher-condition.yaml" passed!
[✓] Test "http/interactsh-stop-at-first-match.yaml" passed!
[✓] Test "http/interactsh.yaml" passed!
[✓] Test "http/default-matcher-condition.yaml" passed!
[✓] Test "http/interactsh-stop-at-first-match.yaml" passed!
[✓] Test "http/interactsh.yaml" passed!
[✓] Test "http/default-matcher-condition.yaml" passed!
[✓] Test "http/interactsh-stop-at-first-match.yaml" passed!
[✓] Test "http/interactsh.yaml" passed!
[✓] Test "http/default-matcher-condition.yaml" passed!
[✓] Test "http/interactsh-stop-at-first-match.yaml" passed!
[✓] Test "http/interactsh.yaml" passed!
[✓] Test "http/default-matcher-condition.yaml" passed!
[✓] Test "http/interactsh-stop-at-first-match.yaml" passed!
[✓] Test "http/interactsh.yaml" passed!
[✓] Test "http/default-matcher-condition.yaml" passed!
[✓] Test "http/interactsh-stop-at-first-match.yaml" passed!
[✓] Test "http/interactsh.yaml" passed!
[✓] Test "http/default-matcher-condition.yaml" passed!
[✓] Test "http/interactsh-stop-at-first-match.yaml" passed!
[✓] Test "http/interactsh.yaml" passed!

```

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !

**Comment by tarunKoyalwar** [comment]
interactsh integration test fails after erroring out 3 times in a row . I think it is safe to assume something is wrong with macOS runner https://github.com/projectdiscovery/nuclei/actions/runs/4699355555/jobs/8332719071?pr=3523

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
