### PR TITLE
Add list template tags command

### PR DESCRIPTION
**Pull request by rsrdesarrollo**
## Proposed changes

Add CLI flag '-tgl' to list all the tags available on the templates (similar to -tl but for tags instead of templates)

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by olearycrew** [comment]
Thanks for this contribution @rsrdesarrollo I love this!

**Review by xalgord — COMMENTED** [review]
this feature was much needed ❤️

**Review by ehsandeep — CHANGES_REQUESTED** [review]
- fast processing of tags to reduce load time
- output format update with sorting
- jsonl format support

cc @Ice3man543

**Review by ehsandeep — APPROVED** [review]
```console
$ ./nuclei -tgl -silent -j | head -n 10

{"tag":"cve","count":2416}
{"tag":"panel","count":1122}
{"tag":"wordpress","count":956}
{"tag":"exposure","count":895}
{"tag":"xss","count":890}
{"tag":"wp-plugin","count":836}
{"tag":"osint","count":804}
{"tag":"tech","count":673}
{"tag":"lfi","count":646}
{"tag":"misconfig","count":598}
```

```console
$ ./nuclei -tgl -silent | head -n 10

cve (2416)
panel (1122)
wordpress (956)
exposure (895)
xss (890)
wp-plugin (836)
osint (804)
tech (673)
lfi (646)
misconfig (598)
```

**Pull request merged**
