### PR TITLE
use go-yaml

### LINKED ISSUE #3828: Replace gopkg.in/yaml.v2 with goccy/go-yaml
### Please describe your feature request:
Replacing package `gopkg.in/yaml.v2` with https://github.com/goccy/go-yaml

### Describe the use case of this feature:
It would be helpful to use with `-validate` option to quickly identify template errors with understandable error syntax.

image

### PR DESCRIPTION
**Pull request by dogancanbakir**
## Proposed changes
It would be helpful to use with -validate option to quickly identify template errors with understandable error syntax. Replace package gopkg.in/yaml.v2 with https://github.com/goccy/go-yaml. Closes #3828.

```
$ go run . -t test.yaml -validate

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.9

                projectdiscovery.io

[ERR] Error occurred loading template test.yaml: Could not load template test.yaml: [14:9] unknown field "typo"
  11 |       - "{{BaseURL}}"
  12 | 
  13 |     matchers:
> 14 |       - typo: status
               ^
  15 |         status:
  16 |           - 200
[FTL] Could not validate templates: errors occured during template validation
exit status 1

$ cat test.yaml 
id: test

info:
  name: test
  author: pdteam
  severity: info

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - typo: status
        status:
          - 200
```

## Checklist
- [X] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by dogancanbakir** [comment]
The template validation is failing due to the presence of `\t`, which is not handled correctly by `go-yaml`.  For example:
For this matcher:
```
- type: word
        words:
          - "IN\tCAA"
```

I get `IN\tCAA` when using `yaml.v2`, `IN\\tCAA` when using `go-yaml`.

**Review by ehsandeep — COMMENTED** [review]
@dogancanbakir looks like the library also has color support to highlight errored lines, which would be easy to highlight for the user.

**Comment by dogancanbakir** [comment]
@ehsandeep There seems to be an issue with the `yaml.FormatError` func.
https://github.com/goccy/go-yaml/pull/6/files#diff-373fb23355f8ed601aa2d3c450033ccd8cf067b36ae6255cb9d2af857bf71f55R367 👀

**Review by ehsandeep — CHANGES_REQUESTED** [review]
@RamanaReddy0M @dogancanbakir we can update the matcher in test with additional matcher which will actually match, I will make the changes in template project as well.

**Comment by ehsandeep** [comment]
Closing for now since new lib is not compitable with some of existing syntax in existing templates.

**Pull request closed without merging**
