### PR TITLE
Added ability to set connection header in nuclei tempaltes.

### PR DESCRIPTION
**Pull request by tracertea**
This is associated with this bug.
https://github.com/projectdiscovery/nuclei/issues/226

### CODE REVIEW

**Comment by bauthard** [comment]
Hi @tracertea, 

Just tested this, I can confirm RAW request now allows users to add connection header, but I still notice duplicate header on both template as an example shared in the issue. 

Template used for the test:- 

```
id: testing-http

requests:
  - raw:
      - |
          GET / HTTP/1.1
          Host: {{Hostname}}
          Connection: keep-alive
```

```
echo http://d8mownw4fxs88va8jl5x7el86zcr0g.burpcollaborator.net | ./nuclei -t test.yaml 
```

```
GET / HTTP/1.1
Host: d8mownw4fxs88va8jl5x7el86zcr0g.burpcollaborator.net
User-Agent: Nuclei - Open-source project (github.com/projectdiscovery/nuclei)
Accept: */*
Accept-Language: en
Connection: keep-alive
Accept-Encoding: gzip
Connection: close
```

**Comment by tracertea** [comment]
@bauthard thats interesting i was testing it locally with -debug and without raw requests.

connect.yaml
```
id: connection-check

info:
  name: Connection Check
  author: tracertea
  severity: high

requests:
  - method: GET
    path:
      - "{{BaseURL}}/api/"
    headers:
        Connection:
            "keep-alive"
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
```

```
nuclei -target http://baps965vgkrbi5wip9rrg1lfq6wwkl.burpcollaborator.net -t connect.yaml -json -debug

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] nuclei-templates are not installed, use update-templates flag.
[INF] Loading templates...
[INF] [connection-check] Connection Check (@tracertea) [high]
[INF] Using 1 rules (1 templates, 0 workflows)
[INF] Dumped HTTP request for http://baps965vgkrbi5wip9rrg1lfq6wwkl.burpcollaborator.net (connection-check)

GET /api/ HTTP/1.1
Host: baps965vgkrbi5wip9rrg1lfq6wwkl.burpcollaborator.net
Accept: */*
Accept-Language: en
Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

[INF] Dumped HTTP response for http://baps965vgkrbi5wip9rrg1lfq6wwkl.burpcollaborator.net (connection-check)

HTTP/1.1 200 OK
Content-Length: 53
Content-Type: text/html
Server: Burp Collaborator https://burpcollaborator.net/
X-Collaborator-Version: 4

<html><body>9r6oz3z3jjm65ljuaz2x6xzjigz</body></html>
{"template":"connection-check","type":"http","matched":"http://baps965vgkrbi5wip9rrg1lfq6wwkl.burpcollaborator.net/api/","severity":"high","author":"tracertea","description":""}
```

But reviewing the request received it looks like connection close is being applied...
```
GET /api/ HTTP/1.1
Host: baps965vgkrbi5wip9rrg1lfq6wwkl.burpcollaborator.net
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
Accept: */*
Accept-Language: en
Connection: keep-alive
Accept-Encoding: gzip
Connection: close
```

**Comment by tracertea** [comment]
Not sure this can be fixed through the code changes I made. Its possible that this issue needs to be addressed using rawhttp. I am fine with closing this out until that functionality is implemented.

**Comment by bauthard** [comment]
Hi @tracertea, 

Let's keep it open, we will make sure to get this fixed before the next release, we will update or close the PR after that.

**Comment by bauthard** [comment]
@tracertea this will be fixed with ongoing code refactoring, as such closing this PR, thank you for putting your time to fix the possible bug.

**Comment by bauthard** [comment]
@tracertea this is fixed with https://github.com/projectdiscovery/nuclei/pull/343, now nuclei follows what the user provided in the template if not, default to set `Connection: close`

**Pull request closed without merging**
