### PR TITLE
fix nuclei panic with ratelimit v0.0.5

### LINKED ISSUE #3256: panic in nuclei dev branch with ratelimit v0.0.5
### Nuclei version:

dev

### Current Behavior:

- `.Close()` method in ratelimit closes token channel from v0.0.5
-  nuclei panics in dev version because the ratelimit channel is closed twice 

### Expected Behavior:

- no panic
### Steps To Reproduce:

```console
./nuclei -u scanme.sh -id "tls-version" 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.8

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.8 (latest)
[INF] Using Nuclei Templates 9.3.6 (latest)
[INF] Templates added in last update: 30
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[tls-version] [ssl] [info] scanme.sh [tls13]
panic: close of closed channel

goroutine 1 [running]:
github.com/projectdiscovery/ratelimit.(*Limiter).Stop(0x1024ca3e0?)
	/Users/tarun/go/pkg/mod/github.com/projectdiscovery/ratelimit@v0.0.5/ratelimit.go:77 +0x68
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).Close(0x140000e4620)
	/Users/tarun/Codebase/nuclei/v2/internal/runner/runner.go:349 +0xfc
main.main()
	/Users/tarun/Codebase/nuclei/v2/cmd/nuclei/main.go:111 +0x540
```

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
## Proposed changes

- closes #3256

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
```console
$ ./nuclei -u scanme.sh -id "tls-version" 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.8

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.8 (latest)
[INF] Using Nuclei Templates 9.3.6 (latest)
[INF] Templates added in last update: 30
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[tls-version] [ssl] [info] scanme.sh [tls13]
```

**Comment by tarunKoyalwar** [comment]
```console
$  go run -race  .  -id "tls-version,tech-detect" -u scanme.sh

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.8

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.8 (latest)
[INF] Using Nuclei Templates 9.3.6 (latest)
[INF] Templates added in last update: 30
[INF] Templates loaded for scan: 2
[INF] Targets loaded for scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[tls-version] [ssl] [info] scanme.sh [tls13]
```

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
bump to v0.0.6 + finalize

**Review by Mzack9999 — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]
```console
./nuclei -u scanme.sh -id "tls-version" 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.8

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.8 (latest)
[INF] Using Nuclei Templates 9.3.6 (latest)
[INF] Templates added in last update: 30
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[tls-version] [ssl] [info] scanme.sh [tls13]
```

**Pull request merged**
