### PR TITLE
Option for request/response output in JSON matches

### PR DESCRIPTION
**Pull request by Marmelatze**
For some semi automatic reporting it would be nice to also have the request and the response that nuclei got for a match.

### CODE REVIEW

**Comment by bauthard** [comment]
Hi @Marmelatze, 

This looks good to me, some conflicts with recent changes need to be updated. 

```bash

> echo http://8t2ifxx7jl8m02lhym4at7au7ldl1a.burpcollaborator.net | ./nuclei -t ~/nuclei-templates/security-misconfiguration/basic-cors-flash.yaml -json-requests -json -silent | jq .

{
  "template": "basic-cors-misconfig-flash",
  "type": "http",
  "matched": "http://8t2ifxx7jl8m02lhym4at7au7ldl1a.burpcollaborator.net/crossdomain.xml",
  "severity": "low",
  "author": "nadino",
  "description": "",
  "request": "GET /crossdomain.xml HTTP/1.1\r\nHost: 8t2ifxx7jl8m02lhym4at7au7ldl1a.burpcollaborator.net\r\nConnection: close\r\nAccept: */*\r\nAccept-Language: en\r\nConnection: close\r\nUser-Agent: Nuclei - Open-source project (github.com/projectdiscovery/nuclei)\r\n\r\n",
  "response": "HTTP/1.1 200 OK\r\nContent-Length: 224\r\nContent-Type: text/x-cross-domain-policy\r\nServer: Burp Collaborator https://burpcollaborator.net/\r\nX-Collaborator-Version: 4\r\n\r\n<?xml version=\"1.0\"?><!DOCTYPE cross-domain-policy SYSTEM \"http://www.adobe.com/xml/dtds/cross-domain-policy.dtd\"><cross-domain-policy><allow-access-from domain=\"*\"/><!-- 2e7a2e6ztk8d75xygzp9fpzjsgz --></cross-domain-policy>"
}
```

@Mzack9999 what you think about this, with additional flag `-json-requests` along with `-json`, this will save/print request/response of matched template, as of now only supported for `HTTP` request, do we want to do same for `DNS` as well? or any changes/improvements?

**Comment by Marmelatze** [comment]
I rebased it with the current changes to master

**Comment by bauthard** [comment]
Hi @Marmelatze, 

This is ready to merge, we are finally done with one of the major PR at https://github.com/projectdiscovery/nuclei/pull/168, I will create another issue to support this feature for DNS request as well to add that later. 

let's merge this as soon as rebase the current changes with the master.

**Comment by Marmelatze** [comment]
Cool :) Rebased against current master

**Pull request merged**
