### PR TITLE
Added switch to list available templates

### PR DESCRIPTION
**Pull request by vzamanillo**
`$ nuclei -lt`

### CODE REVIEW

**Comment by bauthard** [comment]
This is a nice addition, I've created an [issue](https://github.com/projectdiscovery/nuclei/issues/203) in the past which almost similar to this intended for other use cases, mostly allows users to list available templates and get the path of templates in case they want to run it, in this PR, I really like the added information (meta info) with the list, @vzamanillo do you think we can keep both features separately or somehow merge them into one without losing features of both? what's your view on this?

**Comment by vzamanillo** [comment]
Hey @bauthard Do you mean to add in addition to the meta information the path of the template?

**Comment by bauthard** [comment]
I find it meta-information useful, but I'm not sure it can align with https://github.com/projectdiscovery/nuclei/issues/203, so I'm just thinking if we can keep the support of both flag or drop one of them.

**Comment by vzamanillo** [comment]
> I find it meta-information useful, but I'm not sure it can align with #203, so I'm just thinking if we can keep the support of both flag or drop one of them.

Ok, let me think about this.

**Comment by vzamanillo** [comment]
I think we can merge both, do you prefer ls or ts switch?

**Comment by bauthard** [comment]
> I think we can merge both, do you prefer `lt` or `ts` switch?

let's keep it `tl` = template list, and `ts` for template search.

**Comment by vzamanillo** [comment]
And why not tl with or without arguments?

**Comment by vzamanillo** [comment]
Ready for testing.

**Review by bauthard — APPROVED** [review]

**Comment by vzamanillo** [comment]
Final list

list

**Review by Mzack9999 — APPROVED** [review]

**Pull request merged**
