### PR TITLE
Adding snapcraft deploy

### PR DESCRIPTION
**Pull request by Mzack9999**
## Proposed changes
This PR adds support for snapcraft deploy

## Checklist
- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by forgedhallpass** [comment]
Please make sure to have an issue associated to your PR, detailing what we want to achieve and why. Please also consider adding links if necessary, so that even people not familiar with a particular technology could quickly understand what this PR is about.

**Comment by Mzack9999** [comment]
abandoned

**Comment by forgedhallpass** [comment]
@Mzack9999 could you please give some high level explanation, why this enhancement is abandoned?

**Comment by Mzack9999** [comment]
It's going to be handled with `snapcraft.yaml` configuration file like https://github.com/projectdiscovery/httpx/blob/master/snapcraft.yaml which integrates automatically with https://snapcraft.io/

**Pull request closed without merging**
