### PR TITLE
Disable Template Locations (#3705)

### PR DESCRIPTION
**Pull request by kchason**
## Proposed changes

Addresses #3705 by allowing environment variables to disable each of the default and custom template locations. This behavior was discussed in #3706.

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by ehsandeep — COMMENTED** [review]
Can we update env variable in format of `DISABLE_NUCLEI_TEMPLATES_$TYPE_DOWNLOAD`?

**Comment by kchason** [comment]
@ehsandeep done in this PR and the documentation PR

**Review by ehsandeep — APPROVED** [review]

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !!

thanks @kchason for PR .
do you perhaps use any vscode extension / tool for spell check  😄   ??

**Comment by kchason** [comment]
Yep! I use JetBrains' [GoLand](https://www.jetbrains.com/go/), it's really nifty so I try to clean up things as I see them

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
