### PR TITLE
Fix 147 support multiple input templates

### PR DESCRIPTION
**Pull request by manuelbua**
Streamlined the `runEnumeration` driver and avoids code duplication as much as possible.

### CODE REVIEW

**Comment by manuelbua** [comment]
This one will supersedes #153 as it already includes proper error reporting.

**Comment by bauthard** [comment]
Hi @manuelbua, is this being worked on or intended to be in the draft for now? happy to test this once done or updated with the current master code.

**Comment by manuelbua** [comment]
Hi @bauthard, yes due to the changes involved i wasn't sure to actually move it out of draft-mode as i don't know your workflow, is it fine to move this out of draft as soon as I pull the current master into this? Thanks for the head up.

**Comment by bauthard** [comment]
Hi @manuelbua, 

I'm testing this PR now, got this working, and have two feedbacks. 

1. `./nuclei -t  ~/nuclei-templates/files/ -t ~/nuclei-templates/files/panels/`

```
[INF] [wordpress-user-enumaration] Loaded template Wordpress user enumeration (@Manas_Harsh) [informative]
[INF] No results found for template [wordpress-user-enumaration]. Happy hacking!
[INF] [telerik-fileupload-detect] Loaded template Detect Telerik Web UI fileupload handler (@organiccrap) [low]
[INF] No results found for template [telerik-fileupload-detect]. Happy hacking!
[INF] [wadl-files] Loaded template wadl file disclosure (@0xrudra) [informative]
[INF] No results found for template [wadl-files]. Happy hacking!
[INF] [elasticsearch] Loaded template ElasticSearch Information Disclosure (@Shine) [low]
[INF] No results found for template [elasticsearch]. Happy hacking!
```

Notice `No results` after each template executes even it's executing from the directory, unlike the master branch where all the template executes before displaying `No results` in case of no results. 

2. `./nuclei -t files/`

```
$ echo https://2jm7jnv9o8z56k1kt8aaaehjjap2dr.burpcollaborator.net | ./nuclei -t files/

                       __     _ 
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ / 
   / / / / /_/ / /__/ /  __/ /  
  /_/ /_/\__,_/\___/_/\___/_/   v2									  

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[ERR] Could not stat 'files/': stat files/: no such file or directory
[FTL] Error, no templates were found.
```

In Nuclei 2.0, we've added relative path support, which is missing in this case https://github.com/projectdiscovery/nuclei/pull/115

**Comment by manuelbua** [comment]
1. I see, so you mean to just don't show which template didn't produce results, show only a single no results message when there 0 global results?
2. Can you run it with the `-v` flag? I cannot replicate this (on macOS) until i symlink a folder, in that case i've got a similar error.
Also on my branch that's not a fatal so it won't be logged without a `-v`, i will make that fatal as well.

on **master**:
```
ln -s realdir test
$ echo 'http://localhost:9999' | nuclei -t test/ -v
..
[INF] Found template in current directory: /Users/manuel/dev/go/projectdiscovery/templates-test/test
[FTL] Could not find templates in directory '/Users/manuel/dev/go/projectdiscovery/templates-test/test': cannot Walk non-directory: /Users/manuel/dev/go/projectdiscovery/templates-test/test
```

on **mine**:
```
$ echo 'http://localhost:9999' | nuclei -t test/ -v
..
[INF] Found template in current directory: /Users/manuel/dev/go/projectdiscovery/templates-test/test
[WRN] Could not find templates in directory '/Users/manuel/dev/go/projectdiscovery/templates-test/test': cannot Walk non-directory: /Users/manuel/dev/go/projectdiscovery/templates-test/test
[FTL] Error, no templates were found.
```

**Comment by manuelbua** [comment]
Also messages here at https://github.com/projectdiscovery/nuclei/blob/master/v2/internal/runner/update.go#L305 are possibly misleading? Looks like it should say "Found template path" instead?

**Comment by manuelbua** [comment]
Only way to replicate your exact error in 2. is with a non-existent path:
```
$ echo 'http://localhost:9999' | nuclei -t doesntexist
..
[ERR] Could not stat 'doesntexist': stat doesntexist: no such file or directory
[FTL] Error, no templates were found.
```

**Comment by bauthard** [comment]
Hi @manuelbua 

I'm running on mac, with default settings and no symlink, in 1st case, even the directory does not exist, it checks for 2nd path using path defined in `.nuclei-config.json ` file, unlike in 2nd case (this PR), checks for the existence of `folder/file` in the current directory only. 


```bash
$ echo http://whh63llv79waoq95masyhvyiv911pq.burpcollaborator.net | nuclei -t examples/ -silent
[http-multiple-matcher-condition:burp] [http] http://whh63llv79waoq95masyhvyiv911pq.burpcollaborator.net/test.txt


$ echo http://whh63llv79waoq95masyhvyiv911pq.burpcollaborator.net | ./nuclei -t examples/ -silent
[FTL] Error, no templates were found.
```


```bash
$ cat ~/.nuclei-config.json 
{"templates-directory":"/Users/bauthard/nuclei-templates","current-version":"2.0.4","last-checked":"2020-07-19T11:58:21.609937+05:30"}
```

**Comment by bauthard** [comment]
Works perfectly @manuelbua 

@Mzack9999 please confirm this when possible.

**Comment by bauthard** [comment]
Thank you @manuelbua for the support and PR.

**Pull request merged**
