### PR TITLE
Initial adoption of golangci-lint for continuous integration

### PR DESCRIPTION
**Pull request by vzamanillo**
`golangci-lint-action` It's the official `GitHub` action for `golangci-lint` from it's authors. The action runs `golangci-lint` and reports issues from linters.

`golangci-lint` is a fast Go linters runner. It runs linters in parallel, uses caching, supports `yaml` config, has integrations with all major IDE and has dozens of linters included.

Including this action into the workflow would increment the project code quality and could prevent possible future leaks and/or failures setting a minimum of checks and rules, I think it could be very favorable.

A list of available linters on the [official documentation](https://golangci-lint.run/usage/linters/)

There are several linters that I have disabled because for now it is a lot of work to correct the errors, for example

- `funlen`: Detection of long functions.
- `gocyclo`: Calculates cyclomatic complexities.
- `gosec`: Inspects source code for security problems.
- `lll`: Line length linter, used to enforce line length in files.

and I have added some directives to skip the checks with (`nolint`) because they need a small refactor but I think it's fine for now, we can improve it in the future.

Enabled linters:

- `bodyclose`
- `deadcode`
- `dogsled`
- `dupl`
- `errcheck`
- `exhaustive`
- `gochecknoinits`
- `goconst`
- `gocritic`
- `gofmt`
- `goimports`
- `golint`
- `gomnd`
- `goprintffuncname`
- `gosimple`
- `govet`
- `ineffassign`
- `interfacer`
- `maligned`
- `misspell`
- `nakedret`
- `noctx`
- `nolintlint`
- `rowserrcheck`
- `scopelint`
- `staticcheck`
- `structcheck`
- `stylecheck`
- `typecheck`
- `unconvert`
- `unparam`
- `unused`
- `varcheck`
- `whitespace`

Fixes memory leak processing custom workflows with multiple URL from stdin reported on #242

I hope this will be helpful.

### CODE REVIEW

**Comment by vzamanillo** [comment]
I think this is no working because no GOMOD defined for nuclei

On subfinder:

```
  GOTOOLDIR="/opt/hostedtoolcache/go/1.14.7/x64/pkg/tool/linux_amd64"
  GCCGO="gccgo"
  AR="ar"
  CC="gcc"
  CXX="g++"
  CGO_ENABLED="1"
  GOMOD="/home/runner/work/subfinder/subfinder/go.mod"
  CGO_CFLAGS="-g -O2"
  CGO_CPPFLAGS=""
  CGO_CXXFLAGS="-g -O2"
  CGO_FFLAGS="-g -O2"
  CGO_LDFLAGS="-g -O2"
  PKG_CONFIG="pkg-config"
  GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build489397561=/tmp/go-build -gno-record-gcc-switches"
```
On nuclei

```
  GOTOOLDIR="/opt/hostedtoolcache/go/1.15.0/x64/pkg/tool/linux_amd64"
  GCCGO="gccgo"
  AR="ar"
  CC="gcc"
  CXX="g++"
  CGO_ENABLED="1"
  GOMOD=""
  CGO_CFLAGS="-g -O2"
  CGO_CPPFLAGS=""
  CGO_CXXFLAGS="-g -O2"
  CGO_FFLAGS="-g -O2"
  CGO_LDFLAGS="-g -O2"
  PKG_CONFIG="pkg-config"
  GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build317864595=/tmp/go-build -gno-record-gcc-switches"
  
```

**Comment by vzamanillo** [comment]
`go.mod` exists, but is not placed on the projects root.

**Comment by vzamanillo** [comment]
Oh yeah!

**Comment by vzamanillo** [comment]
I think this is ready to be tested before merging.

**Comment by bauthard** [comment]
Hi @vzamanillo, 

Everything looks good to me, one thing I've noticed is a change of path for `main.go`

Previous: location:- `v2/cmd/nuclei`

In this PR:- `cmd/nuclei` 

Can you update that, otherwise it will break installations and release automation?

**Comment by bauthard** [comment]
I see you updated the release files as well accordingly, do you think updating the path is something mandatory in order to work with `golangci-lint`?

**Comment by vzamanillo** [comment]
> I see you updated the release files as well accordingly, do you think updating the path is something mandatory in order to work with `golangci-lint`?

It is not mandatory but it is more easy to change the module definition on `mod.go`

```
module github.com/projectdiscovery/nuclei/v2
module github.com/projectdiscovery/nuclei/v3
whatever...
```

than changing the project folder structure when you upgrade your version next time.

And this way we can automate the semantic versioning with tools like https://github.com/marwan-at-work/mod in an easy way.

**Comment by Ice3man543** [comment]
This looks good to me @vzamanillo! Let's merge this now! Thank you for the amazing work.

**Comment by Ice3man543** [comment]
This has been merged manually! Thanks for the PR.

**Comment by vzamanillo** [comment]
> This has been merged manually! Thanks for the PR.

Thank you!! I think this is a good improvement.

**Pull request merged**
