### PR TITLE
Allow to set HTTP timeout

### PR DESCRIPTION
**Pull request by wk8**
## Proposed changes

Users may want to use a shorter timeout than the 30s default.

## Checklist

- [X] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [X] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by wk8** [comment]
@Mzack9999 would appreciate a review on this one as well, thanks a lot :)

**Comment by Mzack9999** [comment]
@wk8 The default timeout should be 10s for all protocols (including http, defined via `-timeout`). Did you face any situation in which you needed to define different timeouts for different protocols? I'm just trying to understand more about the specific use case, and see if we can implement a more generic solution that would fit also other protocols. Thanks!

**Comment by wk8** [comment]
@Mzack9999 I don't think the default timeout was being applied here, but I could be wrong?

**Comment by tarunKoyalwar** [comment]
@wk8 , yeah we apply default timeouts when intializing pool clients for various protocols (see protocolinit package) for http it is done in `pkg/protocols/http/httpclientpool` package and it is stored in `types.Timeout`

```console
$ nuclei -h timeout
Nuclei is a fast, template based vulnerability scanner focusing
on extensive configurability, massive extensibility and ease of use.

Usage:
  nuclei [flags]

Flags:
   -timeout int  time to wait in seconds before timeout (default 10)
```

we use this timeout when initializing http clients (both raw & normal ) see
https://github.com/projectdiscovery/nuclei/blob/619396a6b8a8aeaac50e38f5f21be74cc0f91e2c/pkg/protocols/http/httpclientpool/clientpool.go#L141-L143
https://github.com/projectdiscovery/nuclei/blob/619396a6b8a8aeaac50e38f5f21be74cc0f91e2c/pkg/protocols/http/httpclientpool/clientpool.go#L290-L292

as @Mzack9999 suggested , unless there is a specific situation / use-case where http timeout needs to be configured but not others , i think we can close this as it is already supported.

closing this PR now , feel free to re-open this PR or new issue if you think otherwise. 

Thanks

**Pull request closed without merging**
