### PR TITLE
Rate limit per target

### PR DESCRIPTION
**Pull request by CasperGN**
Introducing `-rl` flag for controlling `rate-limiting` of client requests per second.
The Limiter is based on the `rate.Limiter` and appended to the `runner` per target. Illustrative testing done here:  
  
```
... Just showing amount of templates below ...
[INF] Using 142 rules (142 templates, 0 workflows)
...
[cgn@localhost nuclei]$ date; ./nuclei -target some_single_target -t ../nuclei-templates/cves/ -t ../nuclei-templates/files/ -t ../nuclei-templates/generic-detections/ -rl 120 -silent; date
lør 12 sep 17:25:52 CEST 2020
lør 12 sep 17:26:14 CEST 2020
[cgn@localhost nuclei]$ date; ./nuclei -target some_single_target -t ../nuclei-templates/cves/ -t ../nuclei-templates/files/ -t ../nuclei-templates/generic-detections/ -rl 170 -silent; date
lør 12 sep 17:26:29 CEST 2020
lør 12 sep 17:26:29 CEST 2020
[cgn@localhost nuclei]$ date; ./nuclei -target some_single_target -t ../nuclei-templates/cves/ -t ../nuclei-templates/files/ -t ../nuclei-templates/generic-detections/ -rl 90 -silent; date
lør 12 sep 17:26:53 CEST 2020
lør 12 sep 17:27:45 CEST 2020
```
And with multiple targets:
```
[cgn@localhost nuclei]$ wc -l targets.txt 
193 targets.txt
[cgn@localhost nuclei]$ date; ./nuclei -l targets.txt -t ../nuclei-templates/cves/ -t ../nuclei-templates/files/ -t ../nuclei-templates/generic-detections/ -rl 120 -silent; date
lør 12 sep 17:36:20 CEST 2020
lør 12 sep 17:36:42 CEST 2020
[cgn@localhost nuclei]$ date; ./nuclei -l targets.txt -t ../nuclei-templates/cves/ -t ../nuclei-templates/files/ -t ../nuclei-templates/generic-detections/ -rl 170 -silent; date
lør 12 sep 17:42:39 CEST 2020
lør 12 sep 17:42:39 CEST 2020
[cgn@localhost nuclei]$ date; ./nuclei -l targets.txt -t ../nuclei-templates/cves/ -t ../nuclei-templates/files/ -t ../nuclei-templates/generic-detections/ -rl 90 -silent; date
lør 12 sep 17:42:44 CEST 2020
lør 12 sep 17:43:36 CEST 2020
```
And without specifying `-rl` the default limit is set to `9999999` to avoid limiting.
```
[cgn@localhost nuclei]$ date; ./nuclei -l targets.txt -t ../nuclei-templates/cves/ -t ../nuclei-templates/files/ -t ../nuclei-templates/generic-detections/ -silent; date
lør 12 sep 17:44:05 CEST 2020
lør 12 sep 17:44:06 CEST 2020
```

Let me know what you think.

**Edit:** The overall goal is to be able to control the amount of requests per second per target. Ideally this would lead to:  
1 target with `-rl 10` -> total of 10 requests per second  
10 targets with `-rl 10` -> total of 100 requests per second 

This would make it easier to honor rate-limits on BugBounty programs.

Most of the testing has been conducted as such:
```
[cgn@localhost nuclei]$ subfinder -silent -d "large_BB_program.com" -oD . -o large_BB_program.txt
[cgn@localhost nuclei]$ sed -i 's/^/https:\/\//g' large_BB_program.txt
[cgn@localhost nuclei]$ nuclei -l large_BB_program.txt -t ../nuclei-templates/security-misconfiguration/ -pba -silent
... observe r/s
[cgn@localhost nuclei]$ nuclei -l large_BB_program.txt -t ../nuclei-templates/security-misconfiguration/ -pba -silent -rl 20
... observe r/s
[cgn@localhost nuclei]$ nuclei -target $(head -1 large_BB_program.txt) -t ../nuclei-templates/security-misconfiguration/ -pba -silent
... observe r/s
[cgn@localhost nuclei]$ nuclei -target $(head -1 large_BB_program.txt) -t ../nuclei-templates/security-misconfiguration/ -pba -silent -rl 20
... observe r/s
```

Cheers!
/ Casper

### CODE REVIEW

**Comment by CasperGN** [comment]
@bauthard could you add WIP tag?
There's something off with the timing..

/ Casper

**Comment by CasperGN** [comment]
I think the runner is the best place to have the ratelimit since otherwise several templates supplied by `-t` would yield increased queries against the same target. When using the runner the ratelimit is set on the target overall and not the context of the template or httpexecutor.
When using `-pbar` i seem to consistently stay around or below the supplied rate. 
I'd recon this could be put back on review.

/ Casper

**Comment by CasperGN** [comment]
@toufik-airane as per DMs :-)

/ Casper

**Comment by CasperGN** [comment]
@bauthard and @toufik-airane 
Whenever you get time to look at this. Removed the WIP flag after some more testing.

/ Casper

**Review by Mzack9999 — APPROVED** [review]

**Pull request merged**
