### PR TITLE
Add payload in dns protocol

### PR DESCRIPTION
**Pull request by ShubhamRasal**
<details> <summary>  Template </summary> 

```yaml
id: dns-attack

info:
  name: basic dns template
  author: pdteam
  severity: info


dns:
  - name: "{{subdomain_wordlist}}.{{FQDN}}"
    type: A

    attack: batteringram
    payloads:
      subdomain_wordlist: 
      - one
      - docs
      - drive
    
    matchers:
      - type: word
        words:
          - "IN\tA"

    extractors:
      - type: regex
        group: 1
        regex:
          - "IN\tA\t(.+)"
```
</details>

### command
```console
❯ ./nuclei -u https://google.com -t templates/dns-payload.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.3-dev

		projectdiscovery.io

[INF] Current nuclei version: v2.9.3-dev (development)
[INF] Current nuclei-templates version: 9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[dns-attack] [dns] [info] google.com. [172.217.160.174]
[dns-attack] [dns] [info] google.com. [142.250.182.206]
[dns-attack] [dns] [info] google.com. [142.250.199.174]
```

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by ehsandeep — CHANGES_REQUESTED** [review]
- [x] matched at to include complete dns name in json/cli output
- [x] removed trailing dot in dns name output

**Review by ehsandeep — CHANGES_REQUESTED** [review]
- [x] Minor issue with stats calculation with payloads.
- [x] debug / verbose mode should also reflect queried dns name instead of input.

```console
echo google.com | ./nuclei -t test.yaml -stats -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.3-dev

		projectdiscovery.io

[INF] Current nuclei version: v2.9.3-dev (development)
[INF] Current nuclei-templates version: v9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[VER] [dns-attack] Sent DNS request to google.com.
[VER] [dns-attack] Sent DNS request to google.com.
[VER] [dns-attack] Sent DNS request to google.com.
[VER] [dns-attack] Sent DNS request to google.com.
[VER] [dns-attack] Sent DNS request to google.com.
[0:00:05] | Templates: 1 | Hosts: 1 | RPS: 1 | Matched: 0 | Errors: 3 | Requests: 8/1 (800%)
```

**Comment by ShubhamRasal** [comment]
```console
❯ ./nuclei -u https://google.com -t templates/dns-payload.yaml -stats  -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.3-dev

		projectdiscovery.io

[INF] Current nuclei version: v2.9.3-dev (outdated)
[INF] Current nuclei-templates version: 9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[VER] [dns-attack] Sent DNS request to one.google.com
[dns-attack] [dns] [info] one.google.com [142.250.183.14]
[VER] [dns-attack] Sent DNS request to docs.google.com
[dns-attack] [dns] [info] docs.google.com [142.251.42.14]
[VER] [dns-attack] Sent DNS request to drive.google.com
[dns-attack] [dns] [info] drive.google.com [142.250.192.110]
[0:00:00] | Templates: 1 | Hosts: 1 | RPS: 51 | Matched: 3 | Errors: 0 | Requests: 3/3 (100%)
```

**Review by tarunKoyalwar — APPROVED** [review]
lgtm!

```console
$  ./nuclei -u google.com -t ~/test-templates/dnspayload.yaml       

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.3-dev

		projectdiscovery.io

[INF] Current nuclei version: v2.9.3-dev (outdated)
[INF] Current nuclei-templates version: v9.4.3 (latest)
[INF] New templates added in latest release: 18
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[dns-attack] [dns] [info] one.google.com [142.251.42.110]
[dns-attack] [dns] [info] docs.google.com [142.250.183.174]
[dns-attack] [dns] [info] drive.google.com [142.250.183.206]

```

**Review by ehsandeep — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
