### PR TITLE
Gitlab Custom Templates

### PR DESCRIPTION
**Pull request by kchason**
## Proposed changes
This addresses https://github.com/projectdiscovery/nuclei/issues/3569 by adding a new custom template provider for downloading nuclei templates from GitLab repositories.

It downloads `.yaml` files recursively from the repository and stores them locally under `/path/to/nuclei-templates/gitlab/<project-slug>/<filename.yaml>`. It supports self-hosted as well as GitLab.com repositories and the requirements for the personal access token are in the documentation (below).

The documentation for this new provider has been submitted as a pull request in the Nuclei documentation repo: https://github.com/projectdiscovery/nuclei-docs/pull/143

image

As automated testing of this function would require an authenticated service, the following manual testing was performed with two private GitLab repositories.

**Missing Variables**
image

**Downloading from a Repository**
image

**Downloading from two Repositories**
image

**Repository Listings**
image
image

**Local Directory Listing**
image

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by ehsandeep — CHANGES_REQUESTED** [review]
Merge conflict

**Comment by kchason** [comment]
@ehsandeep in updating the PR to include the updates from `dev` it appears that the template logic broke during the last commit. The `runner.customTemplates` property is being updated appropriately, but it's never referenced in the execution anymore so the custom providers don't get called.

Debugging shows the value of https://github.com/projectdiscovery/nuclei/blob/dev/v2/internal/runner/runner.go#L129 is set appropriately with the GitLab configuration (and others as appropriate). 

From what I can see, it looks like the deleted loops in `v2/internal/runner/update.go` weren't migrated to another location in the codebase.

```go
for _, ct := range r.customTemplates {
	ct.Update(r.templatesConfig.TemplatesDirectory, ctx)
}
```
https://github.com/projectdiscovery/nuclei/commit/bf08913cd056dd946378d85828741106e146b2c4#diff-a7420f10300c14cb6771618fa371e605c756a2c23f6abc090b149d219cafbe81L108

```go
for _, ct := range r.customTemplates {
    ct.Download(r.templatesConfig.TemplatesDirectory, ctx)
}
```
https://github.com/projectdiscovery/nuclei/commit/bf08913cd056dd946378d85828741106e146b2c4#diff-a7420f10300c14cb6771618fa371e605c756a2c23f6abc090b149d219cafbe81L180

**Comment by tarunKoyalwar** [comment]
@kchason , I will update the logic shortly in this PR itself

**Comment by tarunKoyalwar** [comment]
```console
$ ./nuclei -tv
[INF] Public nuclei-templates version: v9.4.2 (/Users/tarun/nuclei-templates)
[INF] Custom S3 templates location: /Users/tarun/nuclei-templates/github
[INF] Custom Github templates location: /Users/tarun/nuclei-templates/github 
[INF] Custom Gitlab templates location: /Users/tarun/nuclei-templates/gitlab 
[INF] Custom Azure templates location: /Users/tarun/nuclei-templates/azure 
```

**Comment by tarunKoyalwar** [comment]
```console
$ GITHUB_TEMPLATE_REPO=ehsandeep/nuclei-templates ./nuclei -ut

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.2-dev

		projectdiscovery.io

[INF] No new updates found for nuclei templates
[INF] Repo ehsandeep/nuclei-templates cloned successfully at /Users/tarun/nuclei-templates/github/nuclei-templates
```
```
$ ./nuclei 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.2-dev

		projectdiscovery.io

[INF] Current nuclei version: v2.9.2-dev (development)
[INF] Current nuclei-templates version: v9.4.2 (latest)
[INF] New templates added in latest release: 78
[INF] Templates loaded for current scan: 10801
[INF] No results found. Better luck next time!

```

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !

```console
$ GITLAB_REPOSITORY_IDS=42098078 ./nuclei -ut

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.2-dev

		projectdiscovery.io

[INF] No new updates found for nuclei templates
[INF] GitLab project 'nuclei-templates' (42098078) cloned successfully
[INF] 2 templates downloaded from 1 GitLab project(s) to: /Users/tarun/nuclei-templates/gitlab
```
```console
$  ./nuclei -tv
[INF] Public nuclei-templates version: v9.4.2 (/Users/tarun/nuclei-templates)
[INF] Custom Github templates location: /Users/tarun/nuclei-templates/github 
[INF] Custom Gitlab templates location: /Users/tarun/nuclei-templates/gitlab 

```

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
