### PR TITLE
register goja func to check udp port 

### PR DESCRIPTION
**Pull request by RamanaReddy0M**
## Proposed changes
- closes: #5396 

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by RamanaReddy0M** [comment]
## Before:
__Tempalte:__
```yaml
id: tftp-detect

info:
  name: TFTP Service - Detection
  author: pussycat0x
  severity: info
  description: |
    Detect TFTP Service.
  metadata:
    verified: true
    max-request: 1
    shodan-query: "port:69"
  tags: js,tftp,udp,network
javascript:
  - pre-condition: |
      isPortOpenWithNetwork(Host,Port,Network);
    code: |
      let packet = bytes.NewBuffer();
      let message = "1.txt"
      let data = message;
      packet.WriteString(data)
      let c = require("nuclei/net");
      let conn = c.Open('udp', `${Host}:${Port}`);
      conn.SendHex(packet.Hex());
      let resp = conn.RecvString(256);
      resp;

    args:
      Host: "{{Host}}"
      Port: 69
      Network: udp

    matchers:
      - type: word
        words:
          - "Unknown transfer ID"
# digest: 4a0a00473045022100c512c1a23c479681469c4b6a1e1e7a5740dfee043f58cb2a1d79767822cbb32802203dfa42884afa515fb2ac6dd0e0075422bc1f3ece618c6538164c8b9b09062e46:922c64590222798bb761d5b6d8e72950
```
```console
✗ go run . -t port-detect.yaml -u 201.194.192.183 -v -debug

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.0-dev

                projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.3.0-dev (development)
[INF] Current nuclei-templates version: v9.9.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 75
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 1
[DBG] [tftp-detect] Executing Precondition for request
[DBG]  [tftp-detect] Javascript Code:

        isPortOpen(Host, Port);

[WRN] [tftp-detect] Could not execute request for 201.194.192.183: [tftp-detect:RUNTIME] could not execute pre-condition: dial tcp 201.194.192.183:69: connect: connection refused
[INF] No results found. Better luck next time!
```

## After
__Tempalte:__
```yaml
id: tftp-detect

info:
  name: TFTP Service - Detection
  author: pussycat0x
  severity: info
  description: |
    Detect TFTP Service.
  metadata:
    verified: true
    max-request: 1
    shodan-query: "port:69"
  tags: js,tftp,udp,network
javascript:
  - pre-condition: |
      isPortOpenWithNetwork(Host,Port,Network);
    code: |
      let packet = bytes.NewBuffer();
      let message = "1.txt"
      let data = message;
      packet.WriteString(data)
      let c = require("nuclei/net");
      let conn = c.Open('udp', `${Host}:${Port}`);
      conn.SendHex(packet.Hex());
      let resp = conn.RecvString(256);
      resp;

    args:
      Host: "{{Host}}"
      Port: 69
      Network: udp

    matchers:
      - type: word
        words:
          - "Unknown transfer ID"
# digest: 4a0a00473045022100c512c1a23c479681469c4b6a1e1e7a5740dfee043f58cb2a1d79767822cbb32802203dfa42884afa515fb2ac6dd0e0075422bc1f3ece618c6538164c8b9b09062e46:922c64590222798bb761d5b6d8e72950
```

```console
✗ go run . -t port-detect.yaml -u 201.194.192.183 -v -debug

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.0-dev

                projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.3.0-dev (development)
[INF] Current nuclei-templates version: v9.9.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 75
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[DBG] [tftp-detect] Executing Precondition for request
[DBG]  [tftp-detect] Javascript Code:

        isPortOpenWithNetwork(Host, Port, Network);

[DBG] [tftp-detect] Precondition for request was satisfied
[VER] [tftp-detect] Sent Javascript request to 201.194.192.183:69
[DBG] [tftp-detect] Dumped Javascript request for 201.194.192.183:69:
Variables:
        1. Host => 201.194.192.183
        2. Network => udp
        3. Port => 69 address=201.194.192.183:69
[DBG]  [tftp-detect] Javascript Code:

        let packet = bytes.NewBuffer();
        let message = "1.txt"
        let data = message;
        packet.WriteString(data)
        let c = require("nuclei/net");
        let conn = c.Open('udp', `${Host}:${Port}`);
        conn.SendHex(packet.Hex());
        let resp = conn.RecvString(256);
        resp;

[DBG] [tftp-detect] Dumped Javascript response for 201.194.192.183:69:
        1. response => Illegal TFTP operation.
        2. success => true address=201.194.192.183:69
[INF] No results found. Better luck next time!
```

**Review by tarunKoyalwar — COMMENTED** [review]
implementation lgtm ! 

```
./nuclei  -u 201.194.192.183 -t a.yaml -debug 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.0-dev

		projectdiscovery.io

[INF] Current nuclei version: v3.3.0-dev (development)
[INF] Current nuclei-templates version: v9.9.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 75
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[DBG] [tftp-detect] Executing Precondition for request
[DBG]  [tftp-detect] Javascript Code:

	isPortOpenWithNetwork(Host, Port, Network);

[DBG] [tftp-detect] Precondition for request was satisfied
[DBG] [tftp-detect] Dumped Javascript request for 201.194.192.183:69:
Variables:
 	1. Host => 201.194.192.183
	2. Network => udp
	3. Port => 69 address=201.194.192.183:69
[DBG]  [tftp-detect] Javascript Code:

	let packet = bytes.NewBuffer();
	let message = "1.txt"
	let data = message;
	packet.WriteString(data)
	let c = require("nuclei/net");
	let conn = c.Open('udp', `${Host}:${Port}`);
	conn.SendHex(packet.Hex());
	let resp = conn.RecvString(256);
	resp;

[DBG] [tftp-detect] Dumped Javascript response for 201.194.192.183:69:
	1. response => Illegal TFTP operation.
	2. success => true address=201.194.192.183:69
[INF] No results found. Better luck next time!
```

**Review by tarunKoyalwar — CHANGES_REQUESTED** [review]
tagging @ehsandeep @princechaddha  since this involves change/design with templates
---
instead of 
```js
isPortOpenWithNetwork(Host,Port,Network);
```
i propose 
```javascript
isUDPPortOpen(Host,Port)
```

we already have `isPortOpen()` which default to tcp and since there is only one alternative value `isUDPPortOpen` seems simple compared to adding new argument for network selection

**Comment by princechaddha** [comment]
`isUDPPortOpen(Host,Port)` looks good.

**Review by tarunKoyalwar — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
