### PR TITLE
move runner outside of internal to pkg

### PR DESCRIPTION
**Pull request by gsilvapt**
## Proposed changes

Hi team,

I'm working on a project where we are trying to build a wrapper for the nuclei runner, facilitating the option and flags logic, but we cannot proceed right now because the runner lives in `internal/` and we cannot import it.
This change moves the runner out of that directory into `pkg/`, compliant with go's recommended package structure, so we (and others) can use the runner directly in third-party tools.

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by gsilvapt** [comment]
Some help on the errors above, please?

**Comment by anykno** [comment]
similar situation we are facing, still working on ???

**Comment by gsilvapt** [comment]
> similar situation we are facing, still working on ???

Hello 👋 the errors I'm getting with the Windows builds are strange and I never had the take to pick this up again.

Since now there are conflicts, I'll try fixing them (should be applying the changes in the new location) and hope that fixes the windows builds. If not, I'll try to dedicate some time to that too to see if I can find anything I can do to fix it.

**Comment by Ice3man543** [comment]
@gsilvapt it is not expected for the runner to be part of the public nuclei interface since it is subject to changes and no stable public API.

Instead, for programs wishing to use nuclei in an embedded manner, they should use `pkg/` packages instead of `internal/runner`.

Example below - https://github.com/projectdiscovery/nuclei/blob/master/DESIGN.md#using-nuclei-from-go-code

Closing the issue as not planned. Let me know if you have any questions!

**Comment by gsilvapt** [comment]
Thanks for getting back to me and the docs, @Ice3man543.

**Pull request closed without merging**
