### PR TITLE
Adding SNI override via request annotations

### PR DESCRIPTION
**Pull request by Mzack9999**
## Proposed changes
This PR implements SNI override via request annotations. The annotations has a syntax like `@tls-sni:value`. if `value` is equal to `request.host` then the value of the `Host` header is used as SNI name.

## Checklist
- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Correlated PRs
- https://github.com/projectdiscovery/fastdialer/pull/35
- https://github.com/projectdiscovery/nuclei-docs/pull/37

## Example
```console
$ cat t.yaml
id: example

info:
  name: example
  author: pdteam
  severity: info

requests:
  - raw:
      # request.host => copy the value of Host header
      # any other value is copied literally
      - |
        @tls-sni:request.host
        GET / HTTP/1.1
        Host: test
        Origin: {{BaseURL}}

    matchers:
      - type: word
        words:
          - "test ok"
$ echo https://192.168.1.1 | go run . -t t.yaml
```

## Improvements
- SNI for SSL Templates
- SNI for Network templates

### CODE REVIEW

**Review by Ice3man543 — COMMENTED** [review]
Do we also intend to support http variables in SNI field @ehsandeep @Mzack9999? As I see in the issue the user also asked for global vars in SNI field which is not supported here.

**Comment by Mzack9999** [comment]
@Ice3man543 I think it would make things quite complex. The specific case used the exact value of the `Host` header, which can be done using the particular value `request.host`, which will pull the value at runtime after the expression evaluation.

**Comment by 0xAwali** [comment]
Hi @Mzack9999 I checked this one but it's not work when using unsafe: true because nuclei will send @tls-sni:request.host in the request otherwise it work correctly so maybe if you add -sni option too , that will solve unsafe: true problem , plus if anyone found target use specific SNI , he will can run nuclei templates e.g.
`echo "https://target" | nuclei -sni "specific-SNI" -H "Host: specific-SNI"  -t /nuclei-templates`

**Review by ehsandeep — CHANGES_REQUESTED** [review]
- [x] merge conflict
- [ ] doesn't work with `unsafe: true`; this applies to [CLI flag support](https://github.com/projectdiscovery/nuclei/pull/1964) as well. => follow up ticket
- [x] CLI option should override request annotation

**Review by ehsandeep — APPROVED** [review]

**Comment by ehsandeep** [comment]
> Hi @Mzack9999 I checked this one but it's not work when using unsafe: true because nuclei will send @tls-sni:request.host in the request otherwise it work correctly so maybe if you add -sni option too , that will solve unsafe: true problem , plus if anyone found target use specific SNI , he will can run nuclei templates e.g. `echo "https://target" | nuclei -sni "specific-SNI" -H "Host: specific-SNI" -t /nuclei-templates`

Thanks for pointing this out, including `unsafe: true` there are other protocols that needs to be supported and getting tracked here - https://github.com/projectdiscovery/nuclei/issues/1984

**Pull request merged**
