### PR TITLE
Workflow Support

### PR DESCRIPTION
**Pull request by Mzack9999**

### CODE REVIEW

**Comment by Mzack9999** [comment]
Notes:
- As of now templates must be added to workflow with absolute paths
- Directory support is not yet implemented

**Comment by Mzack9999** [comment]
Sample workflow

```yaml
id: workflow-example
info:
  name: Simple Workflow
  author: mzack9999
variables:
  webserver: some/path/nuclei-templates/technologies/web-server.yaml
  cve1: some/path/nuclei-templates/cves/cve1.yaml
  cve2: some/path/nuclei-templates/cves/cve2.yaml
  cve3: some/path/nuclei-templates/cves/cve3.yaml
logic: 
    |
  if webserver() {
    cve1()
    cve2()
    cve3()
  }
```

**Comment by bauthard** [comment]
let's merge this after undergoing a change in another branch and document update.

**Comment by Mzack9999** [comment]
Listing to-do before merge:
- [ ] Rebase master
- [ ] Update docs

**Comment by Ice3man543** [comment]
@Mzack9999 I'll have a look and refactor some stuff, i do think we can change the variable thing somehow to allow more flexibility since the current model seems a bit complex. I'll check the code out and make a review of changes we can do. Really good work and very ingenius idea of using the scripting language.

**Comment by Mzack9999** [comment]
I think it's good to merge

**Comment by hakluke** [comment]
This is badass, nice work

**Comment by dwisiswant0** [comment]
Whoop! :clap:

**Pull request merged**
