### PR TITLE
resolves project-discovery/nuclei#822 - Add severity label to GitHub reporter

### PR DESCRIPTION
**Pull request by revblock**
Add a Severity label when creating a GitHub issue.

This is my first time contributing to this project. I wasn't sure if the string format should be in the formatting package or if it's fine in the function itself. Happy to make any changes though.

Thanks,

### CODE REVIEW

**Comment by forgedhallpass** [comment]
Hello @revblock,

Thank you, and congrats to your first contribution!

Even though the issue title only mentions **GitHub**, I believe for the sake of completeness and uniformity we could also do it for the **GitLab** and **Jira** integrations as well. @ehsandeep @Ice3man543  what do you think?

**Comment by revblock** [comment]
@forgedhallpass I'm happy to do that, I can take a look this weekend and get it sorted 👍

**Comment by forgedhallpass** [comment]
The only thing that we need to test out whether creating new labels are permitted through all the APIs or not.

**Comment by revblock** [comment]
@forgedhallpass I've added the label to the GitLab and Jira reporters.

I've tested this against the cloud versions of both of these. Unfortunately, I don't have access to the on-prem versions to test against but as far as I'm aware the functionality is the same in both.

One thing I did notice testing this was the example `issue-tracker-config.yaml` for GitLab isn't correct. It says `project-id` which is right for GitLab but in the code it's still looking for `ProjectName` so it doesn't seem to work. I'll raise this as a seperate issue though.

Thanks,

**Review by forgedhallpass — APPROVED** [review]

**Review by Ice3man543 — APPROVED** [review]
lgtm!

**Pull request merged**
