### PR TITLE
(feat) add Gitea reporting platform support

### PR DESCRIPTION
**Pull request by leonjza**
## Proposed changes

This PR adds [Gitea](https://about.gitea.com/) support as a Nuclei reporting destination to automatically create tickets for new issues.

Under the hood it uses the official Gitea [go-sdk](https://gitea.com/gitea/go-sdk). Unlike GitHub and GitLab, issue labels need to be resolved to ID's, so I had to implement a special method for that to support this feature. Happy for feedback on that given that I am not sure on the performance impact this has. In my local test environment it was acceptable.

An example run showing issues created on a Gitea instance are shown in the following screenshot.

image

An example configuration file to use with the `-rc` flag looks something like this:

```yaml
gitea:
  base-url: https://gitea.lab.local/
  token: <the token>
  project-owner: lab
  project-name: nuclei-testing
  issue-label: nuclei
```

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by dogancanbakir — CHANGES_REQUESTED** [review]
Issue creation works:
image

But `duplicate-issue-check: true` doesn't work. Also, let's update the example file at https://github.com/projectdiscovery/nuclei/blob/dev/cmd/nuclei/issue-tracker-config.yaml.

**Comment by leonjza** [comment]
@dogancanbakir thanks for the review! I've done some work addressing the requested changes and tested the duplicate issue creation quite extensively now.

Would you mind testing again and letting me know? Below is a screenshot of three runs with `duplicate-issue-check: true`.

image

**Comment by leonjza** [comment]
Not sure but it looks like the CI failures seem unrelated to this change?

**Comment by ehsandeep** [comment]
> Not sure but it looks like the CI failures seem unrelated to this change?

it's unrelated, some issues with GitHub CI for interactsh tests.

**Comment by leonjza** [comment]
Just a friendly bump on this one to see if there is anything else needed from me thats blocking landing this one?

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
