### PR TITLE
Issue 3033 deny list

### LINKED ISSUE #3033: Deny List Error
Hi, I am trying to create a custom template and run my repo against it. 

When I try to exclude the tests folder in my repo, the nuclei throws error. 

**Template:**
Screenshot 2022-12-13 at 5 18 36 PM

**Error:**

```
INF] Using Nuclei Engine 2.8.3 (latest)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13cd71d]

goroutine 33 [running]:
[github.com/projectdiscovery/nuclei/v2/pkg/operators.(*Operators).GetMatchersCondition(..](http://github.com/projectdiscovery/nuclei/v2/pkg/operators.(*Operators).GetMatchersCondition(..).)
/home/nuclei/v2/pkg/operators/operators.go:69
[github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).findMatchesWithReader(0xc000219680](http://github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).findMatchesWithReader(0xc000219680), {0x2d703c0, 0xc00094a5e8}, {0xc001c18ee5, 0x5}, {0xc001385dd0, 0x11}, 0xc000129bc0?, 0xc000935388?)
/home/nuclei/v2/pkg/protocols/file/request.go:205 +0x13d
[github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).processReader(0xc000219680](http://github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).processReader(0xc000219680), {0x2d70a80?, 0xc0004e3870}, {0xc001385dd0, 0x11}, {0xc001c18ee5, 0x5}, 0x2025e00?, 0xc00036ac30?)
/home/nuclei/v2/pkg/protocols/file/request.go:189 +0x105
[github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).processFile(0xc000219680](http://github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).processFile(0xc000219680), {0xc001385dd0, 0x11}, {0xc001c18ee5, 0x5}, 0x38?)
/home/nuclei/v2/pkg/protocols/file/request.go:184 +0x505
[github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).ExecuteWithResults.func1.1(0xc001c324e0](http://github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).ExecuteWithResults.func1.1(0xc001c324e0)?, 0xc000219680, 0xc001c324a0, 0xc001babf20, 0xc001babf50, {0xc001385dd0, 0x11})
/home/nuclei/v2/pkg/protocols/file/request.go:139 +0xd14
[github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).ExecuteWithResults.func1({0xc001385dd0](http://github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).ExecuteWithResults.func1(%7B0xc001385dd0), 0x11})
/home/nuclei/v2/pkg/protocols/file/request.go:156 +0x8e
[github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).findDirectoryMatches.func1({0xc001385dd0](http://github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).findDirectoryMatches.func1(%7B0xc001385dd0), 0x11}, {0x2d81ce0?, 0xc001bf7dc0?}, {0x0?, 0x0?})
/home/nuclei/v2/pkg/protocols/file/find.go:103 +0xe3
path/filepath.walkDir({0xc001385dd0, 0x11}, {0x2d81ce0, 0xc001bf7dc0}, 0xc000935b90)
/usr/local/go/src/path/filepath/path.go:398 +0x5c
path/filepath.walkDir({0xc001c18ee5, 0x5}, {0x2d81d18, 0xc001b3b8e0}, 0xc000935b90)
/usr/local/go/src/path/filepath/path.go:420 +0x2aa
path/filepath.WalkDir({0xc001c18ee5, 0x5}, 0xc000917b90)
/usr/local/go/src/path/filepath/path.go:484 +0xb0
[github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).findDirectoryMatches(0xc001c18ee5](http://github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).findDirectoryMatches(0xc001c18ee5)?, {0xc001c18ee5?, 0x5?}, 0xc001c324e0?, 0xc000917d38?)
/home/nuclei/v2/pkg/protocols/file/find.go:89 +0x65
[github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).getInputPaths(0xc000219680](http://github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).getInputPaths(0xc000219680), {0xc001c18ee5, 0x5}, 0x30?)
/home/nuclei/v2/pkg/protocols/file/find.go:43 +0x187
[github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).ExecuteWithResults(0xc000219680](http://github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).ExecuteWithResults(0xc000219680), 0xc001c324a0, 0x3?, 0xc001babf20, 0xc001babf50)
/home/nuclei/v2/pkg/protocols/file/request.go:50 +0x145
[github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc00083d160](http://github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc00083d160), 0xc001c32440)
/home/nuclei/v2/pkg/protocols/common/executer/executer.go:80 +0x3b0
[github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x146b0ca](http://github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x146b0ca)?, 0x0?, 0xc001c32380)
/home/nuclei/v2/pkg/core/execute.go:146 +0x182
created by [github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2](http://github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2)
/home/nuclei/v2/pkg/core/execute.go:131 +0x745
```

Can someone please guide me on how to exclude certain folders from the target directories?

### PR DESCRIPTION
**Pull request by Mzack9999**
## Proposed changes
Closes #3033 

## Checklist
- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by tarunKoyalwar — CHANGES_REQUESTED** [review]
@Mzack9999  issue doesnot seems to be fixed .

**Comment by tarunKoyalwar** [comment]
### Results of Template without `-denylist` 

```sh
echo $HOME/test | ./nuclei -t ~/test/deny-copy.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4-dev

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4-dev (development)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] No results found. Better luck next time!

```

### Template 
```yaml
id: basic-auth-creds

info:
  name: Basic Auth Credentials
  author: gaurang
  severity: high
  tags: token,file,auth

file:
  - extensions:
      - all

    extractors:
      - type: regex
        regex:
          - "[a-zA-Z]{3,10}://[^/\\s:@]{3,20}:[^/\\s:@]{3,20}@.{1,100}[\"'\\s]"
```

**Comment by tarunKoyalwar** [comment]
## Results of template with denylist

```sh
echo $HOME/test | ./nuclei -t ~/test/deny-list.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4-dev

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4-dev (development)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x100eb0c38]

goroutine 56 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/operators.(*Operators).GetMatchersCondition(...)
	/Users/tarun/Codebase/nuclei/v2/pkg/operators/operators.go:69
github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).findMatchesWithReader(0x1400044b9e0, {0x1026e62c0, 0x140005b85e8}, {0x14000305848, 0x11}, {0x1400085c870, 0x27}, 0x10013b41c?, 0x1400052b260?)
	/Users/tarun/Codebase/nuclei/v2/pkg/protocols/file/request.go:205 +0xd8
github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).processReader(0x1400044b9e0, {0x1026e6960?, 0x14000010238}, {0x1400085c870, 0x27}, {0x14000305848, 0x11}, 0x48?, 0x140005af478?)
	/Users/tarun/Codebase/nuclei/v2/pkg/protocols/file/request.go:189 +0xbc
github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).processFile(0x1400044b9e0, {0x1400085c870, 0x27}, {0x14000305848, 0x11}, 0x80?)
	/Users/tarun/Codebase/nuclei/v2/pkg/protocols/file/request.go:184 +0x368
github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).ExecuteWithResults.func1.1(0x1400007ee60?, 0x1400044b9e0, 0x1400007ee20, 0x14000902150, 0x140009021e0, {0x1400085c870, 0x27})
	/Users/tarun/Codebase/nuclei/v2/pkg/protocols/file/request.go:139 +0x9c8
github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).ExecuteWithResults.func1({0x1400085c870, 0x27})
	/Users/tarun/Codebase/nuclei/v2/pkg/protocols/file/request.go:156 +0x88
github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).findDirectoryMatches.func1({0x1400085c870, 0x27}, {0x1026f79a0?, 0x140009dbb00?}, {0x0?, 0x0?})
	/Users/tarun/Codebase/nuclei/v2/pkg/protocols/file/find.go:103 +0xc0
path/filepath.walkDir({0x1400085c870, 0x27}, {0x1026f79a0, 0x140009dbb00}, 0x140005afb78)
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/path/filepath/path.go:398 +0x44
path/filepath.walkDir({0x14000305848, 0x11}, {0x1026f79d8, 0x140008fddd0}, 0x140005afb78)
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/path/filepath/path.go:420 +0x228
path/filepath.WalkDir({0x14000305848, 0x11}, 0x140004f8b78)
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/path/filepath/path.go:484 +0xb4
github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).findDirectoryMatches(0x14000305848?, {0x14000305848?, 0x11?}, 0x100aeaebc?, 0x140004f8d28?)
	/Users/tarun/Codebase/nuclei/v2/pkg/protocols/file/find.go:89 +0x58
github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).getInputPaths(0x1400044b9e0, {0x14000305848, 0x11}, 0x30?)
	/Users/tarun/Codebase/nuclei/v2/pkg/protocols/file/find.go:43 +0x110
github.com/projectdiscovery/nuclei/v2/pkg/protocols/file.(*Request).ExecuteWithResults(0x1400044b9e0, 0x1400007ee20, 0x14000e16638?, 0x14000902150, 0x140009021e0)
	/Users/tarun/Codebase/nuclei/v2/pkg/protocols/file/request.go:50 +0x104
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0x1400007e4a0, 0x1400007ecc0)
	/Users/tarun/Codebase/nuclei/v2/pkg/protocols/common/executer/executer.go:80 +0x384
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x0?, 0x0?, 0x1400007ea40)
	/Users/tarun/Codebase/nuclei/v2/pkg/core/execute.go:146 +0x144
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
	/Users/tarun/Codebase/nuclei/v2/pkg/core/execute.go:131 +0x610
```

```yaml
id: basic-auth-creds

info:
  name: Basic Auth Credentials
  author: gaurang
  severity: high
  tags: token,file,auth

file:
  - extensions:
      - all

  - denylist:
      - test
      - experimental
      - qa

    extractors:
      - type: regex
        regex:
          - "[a-zA-Z]{3,10}://[^/\\s:@]{3,20}:[^/\\s:@]{3,20}@.{1,100}[\"'\\s]"
```

**Review by tarunKoyalwar — APPROVED** [review]
lgtm!

```sh
 echo $HOME/test | ./nuclei -t deny-template.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4-dev

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4-dev (development)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] No results found. Better luck next time!

```

**Review by ehsandeep — APPROVED** [review]
@Mzack9999 we can resolve the conflict and merge this PR.

**Pull request merged**
