### PR TITLE
feat: add new ms flag and new fields in the output JSON

### LINKED ISSUE #1133: New fields to include in JSON output
**Describe the solution you'd like**

New fields to include in JSON output:

- [x]  **template**: `{{template-file-with-path}}`
- [x] **template-url**: `https://github.com/projectdiscovery/nuclei-templates/blob/master/{{template-file-with-path}}`
- [x] **matcher-status**: `{{matched-status}}` - boolean (returns only when `matcher-status/ms` flag is used)

New CLI flag to add:

- [x] **matcher-status/ms** - boolean flag

**Notes:-**

- `template`, `template-url` field will be added as part of default JSON output.
- `matcher-status` field is optional and will be only added into JSON output if the required CLI flag is specified.
- Validation: `matcher-status/ms` CLI flag can be only used with `-json` flag.

Example JSON output:-

<details>
<summary> output with true match </summary>

```console
echo https://example.com | ./nuclei -t misconfiguration/http-missing-security-headers.yaml -json -ms

{
  "template": "misconfiguration/http-missing-security-headers.yaml",
  "template-id": "http-missing-security-headers",
  "template-url": "https://github.com/projectdiscovery/nuclei-templates/blob/master/misconfiguration/http-missing-security-headers.yaml",
  "info": {
    "name": "HTTP Missing Security Headers",
    "author": [
      "socketz",
      "geeknik",
      "g4l1t0",
      "convisoappsec",
      "kurohost",
      "dawid-czarnecki"
    ],
    "tags": [
      "misconfig",
      "generic"
    ],
    "description": "It searches for missing security headers, but obviously, could be so less generic and could be useless for Bug Bounty.",
    "reference": null,
    "severity": "info"
  },
  "matcher-name": "access-control-allow-credentials",
  "type": "http",
  "host": "https://example.com",
  "matched-at": "https://example.com",
  "matched-status": true,
  "timestamp": "2021-10-17T06:54:47.293154+05:30",
  "curl-command": "curl -X 'GET' -d '' -H 'Accept: */*' -H 'Accept-Language: en' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/44.0.2403.155 Safari/537.36' 'https://example.com'"
}
```
</details>

<details>
<summary> output with failed match </summary>

```console
echo https://example.com | ./nuclei -t vulnerabilities/apache/apache-solr-file-read.yaml -json -ms

{
  "template": "vulnerabilities/apache/apache-solr-file-read.yaml",
  "template-id": "apache-solr-file-read",
  "template-url": "https://github.com/projectdiscovery/nuclei-templates/blob/master/vulnerabilities/apache/apache-solr-file-read.yaml",
  "info": {
    "name": "Apache Solr <= 8.8.1 Arbitrary File Read",
    "author": [
      "DhiyaneshDk"
    ],
    "tags": [
      "apache",
      "solr",
      "lfi"
    ],
      "reference": [
        "https://twitter.com/Al1ex4/status/1382981479727128580",
        "https://nsfocusglobal.com/apache-solr-arbitrary-file-read-and-ssrf-vulnerability-threat-alert/",
        "https://twitter.com/sec715/status/1373472323538362371"
      ],
    "severity": "high"
  },
  "type": "http",
  "host": "https://example.com",
  "matched-status": false,
  "timestamp": "2021-10-17T06:54:47.293154+05:30",
}
```
</details>

Related Issues that will also resolved with this addition:

- https://github.com/projectdiscovery/nuclei/issues/725

### PR DESCRIPTION
**Pull request by pmareke**
Fixes #1133 

Done:
New fields to include in JSON output:

* [x] template: {{template-file-with-path}}
* [x] template-url: https://github.com/projectdiscovery/nuclei-templates/blob/master/{{template-file-with-path}}
* [x] matcher-status: {{matched-status}} - boolean (returns only when matcher-status/ms flag is used)
* [x] matcher-status/ms - boolean flag

Steps to test the changes:

`nuclei -t ~/nuclei-templates/technologies/tech-detect.yaml -target https://hackberry.xyz -json`
`nuclei -t ~/nuclei-templates/technologies/tech-detect.yaml -target https://hackberry.xyz -json -ms`

Signed-off-by: pedro.lopez.mareque@gmail.com

### CODE REVIEW

**Comment by pmareke** [comment]
Hi @ehsandeep, this solution is working but I'm not sure if it's the best approach, please fell free to comment on it ok?

**Comment by pmareke** [comment]
> ./nuclei -t vulnerabilities/apache/apache-solr-file-read.yaml -u https://example.com -ms

I'm not sure how are you trying the PR but this commands works different on my branch

image

You're using ms without json which is not allow it.

**Comment by ehsandeep** [comment]
@pmareke if possible, let's jump on discord, thank you.

**Comment by ehsandeep** [comment]
@pmareke closing this PR as it has been handled here - https://github.com/projectdiscovery/nuclei/pull/1258

**Comment by ehsandeep** [comment]
@pmareke this is now completed and merged at https://github.com/projectdiscovery/nuclei/pull/1272, just in case you wanted to have a look at the code, thanks again.

**Comment by pmareke** [comment]
Thanks @ehsandeep, I'll do!

**Pull request closed without merging**
