### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
## Proposed changes

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/nuclei/actions/runs/5705171531#summary-15459544539

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/nuclei/actions/runs/5705175675#summary-15459553779

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by ehsandeep — COMMENTED** [review]
@jsoref, thank you for making all the changes and maintaining this project; looks like we also can add this workflow in the nuclei project to avoid these mistakes in the future as well.

do you think you can also add this workflow in this PR?

**Comment by jsoref** [comment]
I tend to prefer to do the workflow in a followup PR (I think mostly because I'm afraid of drift between when the PR is originally authored, reviewed, and merged), but if you'd like to do it here, I can.

**Comment by ehsandeep** [comment]
@jsoref makes sense, let's do it in the follow-up PR.

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !

doesn't seem like there are any breaking changes to SDK , unless they are using 
https://github.com/projectdiscovery/nuclei/blob/90a126ca1d3aebbb44c86b275647b66132ec4345/v2/pkg/types/types.go#L347-L351
directly from SDK (less likely )

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
