### PR TITLE
Add description to Template files

### PR DESCRIPTION
**Pull request by ankh2054**
To describe the test being performed.

### CODE REVIEW

**Comment by Mzack9999** [comment]
Thanks for the PR!

**Comment by ankh2054** [comment]
My pleasure. Thank you for a great product :)

**Comment by bauthard** [comment]
Hi @ankh2054, 

Again thank you for your support, do you think is it possible for you to add an example with PR in our [guide document](https://github.com/projectdiscovery/nuclei-templates/blob/master/GUIDE.md) which helps users to write a new template, so they can make use of this as well, otherwise, we can get it updated before next release of nuclei.

**Comment by ankh2054** [comment]
sure done - https://github.com/projectdiscovery/nuclei-templates/pull/240

**Pull request merged**
