### PR TITLE
fix(authx): avoid override secrets

### PR DESCRIPTION
**Pull request by dwisiswant0**
## Proposed changes

Avoid overriding secrets.

## Proof

**Template**:

```yaml
# secret-file-requests.yaml
id: secret-file-requests

info:
  name: secret-file-requests
  author: dwisiswant0
  severity: info
  description: secret-file-requests
  tags: test

http:
  - raw:
    - | # foo:default
      GET / HTTP/1.1
      Host: {{Hostname}}
      X-Secret-Type: basicauth
      Authorization: Basic Zm9vOmRlZmF1bHQK

    - |
      GET / HTTP/1.1
      Host: {{Hostname}}
      X-Secret-Type: bearertoken
      Authorization: Bearer default

    - |
      GET / HTTP/1.1
      Host: {{Hostname}}
      X-Secret-Type: cookie
      Cookie: foo=default

    - |
      GET /?foo=default HTTP/1.1
      Host: {{Hostname}}
      X-Secret-Type: query

    - |
      GET / HTTP/1.1
      Host: {{Hostname}}
      X-Secret-Type: header
      foo: default
```

**Secret File content**:

```yaml
# secret-file.yaml
static:
  - type: basicauth
    domains:
      - basicauth.oast.fun
    username: foo
    password: OVERRIDEN

  - type: bearertoken
    domains:
      - bearertoken.oast.fun
    token: OVERRIDEN

  - type: cookie
    domains:
      - cookie.oast.fun
    cookies:
      - key: foo
        value: OVERRIDEN
        # raw: "foo=OVERRIDEN"

  - type: query
    domains:
      - query.oast.fun
    params:
      - key: foo
        value: OVERRIDEN

  - type: header
    domains:
      - header.oast.fun
    headers:
      - key: foo
        value: OVERRIDEN
```

**Command**:

```
go run cmd/nuclei/main.go -duc -debug-req -sf secret-file.yaml -t secret-file-requests.yaml -u https://{basicauth,bearertoken,query,header,cookie}.oast.fun
```

> [!NOTE]
> If you spot an OVERRIDEN value in the dumped HTTP request, it means that a hardcoded secret value has been overridden or replaced from the Secret File.

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by tarunKoyalwar — COMMENTED** [review]
i am not sure if this is right approach , 

from what i can understand user wants to avoid sending auth data when it is not required i.e HEAD , OPTIONS http methods . 

apart from that i don't see a usecase where we don't want to override

we support many input sources ( proxify , burpsuite saved items being one of them ) . in proxy logs it is most likely that it will have credentials ( expired ones in most cases) and we would want to replace them in most /general scenarios, even for basicAuth replacing them does no harm

we can avoid sending them on OPTIONS , HEAD http request methods and for custom or non-general scenarios based on use case of user we can add more filters ( ex: maybe method or path based regex filter )

cc: @ehsandeep

**Comment by dwisiswant0** [comment]
@tarunKoyalwar - the issue author concern is "[...] Authorization header either gets inserted or overridden".

> [...] avoid sending them on OPTIONS , HEAD http request methods

But, I think the _special conditions_ you mentioned are unnecessary since they don't really impact the server.

> [...] we can add more filters ( ex: maybe method or path based regex filter )

Although I'm down with this.

I'm turning this into a draft and working on a workaround by adding an `overwrite` field. This seems like the best approach for this issue instead of adding a more sophisticated filter right now.

**Comment by dwisiswant0** [comment]
**UPDATE**: Changing the base branch and removing the closing issue keywords.

**Comment by CodeStuffBreakThings** [comment]
Hi all,
I just tested out the changes made by @dwisiswant0 and can confirm that when I specify the Authorization header in the raw HTTP request, that takes precedence over the Authorization header that gets inserted by the secret header. And if I remove the Authorization header from the raw HTTP request, the Authorization header from the secret file gets inserted as expected which satisfies my use case: In my scenario, I have 4 raw HTTP requests that need sent; one using a bogus credential pair for basic auth, and 3 that use the actual basic authentication credentials from the secret file.
Thank you so much for your help with this!

**Pull request merged**
