### PR TITLE
switch dependency for kerberos js module (ropnop/gorkb5 -> jcmturner/gokrb5)

### LINKED ISSUE #4646: remove unneeded dependency for kerberos js module
It's not really a feature, but it's a dependency issue for the kerberos js module: at the moment, the module `github.com/ropnop/gokrb5` is used to handle functionalities concerning Kerberos.

The [README.md](https://github.com/ropnop/gokrb5/blob/729746023c02496cb7f43ab64108a37aeca8d6e3/README.md) of that repo states:

> I had to export some functions in order to get my tool [kerbrute](https://github.com/ropnop/kerbrute) to work, so I forked the package. You don't want to use this probably.

But new and updated features are missing from the upstream ([jcmturner's gokrb5](https://github.com/jcmturner/gokrb5)). In the PR that will reference this issue I found a way to export the function needed by [kerbrute](https://github.com/ropnop/kerbrute) without using a fork of the module.

### PR DESCRIPTION
**Pull request by 5amu**
## Proposed changes

Closes #4646 

I updated the `KerberosClient` object to contain the real kerberos client from `gokrb5`:

```go
type KerberosClient struct {
	client *kclient.Client
}
```

So that in file `sendtokdc.go` the struct can have the method `SendToKDC()` exposed to `EnumerateUser`. The behavior stays the same, except now there is one less dependency to the project and (as `github.com/jcmturner` is used by `github.com/go-ldap/ldap/v3` under the hood).

I tested the behavior with the template:

```yaml
id: get-service-ticket

info:
  name: test
  author: 5amu
  severity: info

javascript:
  - args:
      DomainController: "{{Host}}"
    code: |
      krb = require("nuclei/kerberos");
      client = krb.KerberosClient();
      ticket = client.GetServiceTicket(template.Domain, DomainController, template.Username, template.Password, "roastme", "DC01/ldap");
      to_json(ticket);
    extractors:
      - type: json
        json:
          - '.Hash'
```

And here's the result

```
go run .\cmd\nuclei\main.go -u dc01.lab.local -t .\test-krb5.yaml -var Username=victim -var Password=Trust_Me_Br0 -var Domain=LAB.LOCAL -debug

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.5

                projectdiscovery.io

[WRN] Found 12 template[s] loaded with deprecated paths, update before v3 for continued support.
[INF] Current nuclei version: v3.1.5 (latest)
[INF] Current nuclei-templates version: v9.7.3 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 46
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[DBG] [get-service-ticket] Dumped Javascript request for dc01.lab.local:
Variables:
        1. DomainController => dc01.lab.local
        2. Port =>  address=dc01.lab.local
[DBG]  [get-service-ticket] Javascript Code:

        krb = require("nuclei/kerberos");
        client = krb.KerberosClient();
        ticket = client.GetServiceTicket(template.Domain, DomainController, template.Username, template.Password, "roastme", "DC01/ldap");
        to_json(ticket);

[DBG] [get-service-ticket] Dumped Javascript response for dc01.lab.local:
        1. response => {   "Ticket": {     "TktV .... 22c02fc896b11d34c34752" }
        2. success => true address=dc01.lab.local
[get-service-ticket] [javascript] [info] dc01.lab.local ["$krb5tgs$23$*roastme$LAB.LOCAL$DC01/ldap*$9bfaad122883d29d01a7b87a09769fde$f771b64413184d86e886f8d101c6ebd3c99a1dc54edd23ff6959caea26c6de0fe960ebd45af4b4a70b8d5051269f71e2b818c41bcc9391768a377fa01ad83fce2ad6795fc574daa7c3e1dc8877b753637a02378fae8c0300f093a612954bacfb6ba881eb712060eb91ec2c3e3d2fca79d9839f8e8ce8f52b27a4c189cb3b014df5ab8caf560e484ac90379de7439c5eadaf189e5828ce80f42ab50136db5d0c44010a87a7c272282cc0e8b204ce5bab464f73fba22569c3105302643463cecb39801ba29edd4377553f41648d17ee86013ae252366901658212862f94bf55eec2e9d910c21875d2cb93cc1d4d92baeaeab168b5a44e4106771167de4008ce94c958ef913806c9a20ef8fd61ff53dccd19996688482b38d7f474292946a79886a4aa89831c2cdf9c47fb5b9f0aefeaacc2db8192d9609528618fe770c1bf65174a25677f34f97c4bbd3646c1ed2bbed969d8656ad4783e9f321b5a649f70481d89a3b3a8984959376d4c12bbd1d7b232e8021f1e8a56908d7f6cbbd678bbcfa57967bf5b4f496b402c6a1f0a06e9191a8232240a594b109c4484c287cb1913f8f2c8480c5d2b4a3cc3742a73661549ffde4ec45e9bf697d6cb090815fed6f329cd57b94e22a6f5542635e6f60fd6f475cb926a314e359fe748c7a20c5e88eae864e1be3de0c1b2b033e9fa69aeefb76f107df2301f51b562ba9ed4af52334cebd75b7dd6b807c70aff6a83395a1765ff563034e35cf3557b2d0d7a7f11cef7ae1533ab3040d41422f03d1c64d1a6455635630685aef5abe8f4dde90f5ff4a0f99912ddc85a92f17ad75ea656438e929d0ee0ab6396dc13e354fff7f8f5f02b9df96adff41ab8b7991d745546893ab7ebb08c65de6add5b4a000a5a74b6d32fb6600b1e7315ef51ec6b880048ed0e95375a22059d45409bceedbfda321bd50234ff1bcfe9ffba4cd5be90431e9a8897a9ce8c5b945774050621325625e85fc1404a3c5869d003e1dc401a5618c149331b15ca2f12803bca76d598eaa23ca71aad4a72906eb9382454f7cc04f1b7e64ac896ff8828666ecf4687d3a6d2f23231d88c1190e3ebb73a616fd487bb87b55b069a48248576b49f19177a0977a076e2d507f3bb3547b91fc23bdfbce458612812ae8fb5d092a8ad961561cf37ccdec08ec7e31a93e0ee0b48e8ccad458fe7b343de216a53b8c2bbc3ab7f90267cf78b4d5c17097bebbafd40907704bd125916a176f2022c02fc896b11d34c34752"]
```

**NB**: The change reflected on `go.mod` and `go.sum`, please be careful.

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by olearycrew** [comment]
@5amu thanks for this contribution!

**Comment by pussycat0x** [comment]
@tarunKoyalwar   lgtm!

**Review by pussycat0x — APPROVED** [review]

**Comment by tarunKoyalwar** [comment]
@5amu , thanks and everything looks good , just decided to do some refactoring to keep public api simple and  use fastdialer instead of net.Conn ( added some cool helper utils to throw errors , create constructors and stuff)

```
ticket = client.GetServiceTicket(template.Domain, DomainController, template.Username, template.Password, "roastme", "DC01/ldap");
```
^ will be converted to 

```javascript
const client = new kerberos.Client(domain,controller)
const ticket = client.GetServiceTicket({Username: template.Username,Password: template.Password,Target: "roastme",SPN: "DC01/ldap"})
```
aka
```javascript
const client = new kerberos.Client(domain, controller)
const ticket = client.GetServiceTicket({
    Username: template.Username,
    Password: template.Password,
    Target: "roastme",
    SPN: "DC01/ldap"
})
```

this will not be a breaking change (we will keep existing ones) but this is recommended because new options/args can be added without breaking anything and this also adds code readability + intellisense if you use it any IDE

**Review by tarunKoyalwar — APPROVED** [review]
lgtm ! tested it locally everything seems to working also added fastdialer + network policy . 

thanks for pr @5amu , i just refactored kerberos struct / types to make it more easy to write js templates by leveraging autocomplete etc ( mostly adding a constructor throwing errors etc) . so if you have any nuclei templates written using this module you will need to update it after next release .

**Pull request merged**
